/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from './training-details';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/element';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from 'ionic-angular/navigation/nav-controller';
import * as import9 from '../../pipes/objectToArray';
import * as import10 from 'ionic-angular/navigation/nav-params';
import * as import11 from '@angular/core/src/metadata/view';
import * as import12 from '@angular/core/src/linker/component_factory';
import * as import13 from '../../node_modules/ionic-angular/components/toolbar/toolbar.ngfactory';
import * as import14 from '../../node_modules/ionic-angular/components/navbar/navbar.ngfactory';
import * as import15 from '../../node_modules/ionic-angular/components/toolbar/toolbar-title.ngfactory';
import * as import16 from '../../node_modules/ionic-angular/components/toolbar/toolbar-item.ngfactory';
import * as import17 from '@angular/core/src/linker/query_list';
import * as import18 from '../../node_modules/ionic-angular/components/button/button.ngfactory';
import * as import19 from '../../node_modules/ionic-angular/components/icon/icon.ngfactory';
import * as import20 from '../../node_modules/ionic-angular/components/content/content.ngfactory';
import * as import21 from '../../node_modules/@angular/common/src/directives/ng_for.ngfactory';
import * as import22 from '../../node_modules/@angular/common/src/directives/ng_if.ngfactory';
import * as import23 from 'ionic-angular/config/config';
import * as import24 from '@angular/core/src/linker/element_ref';
import * as import25 from 'ionic-angular/navigation/view-controller';
import * as import26 from 'ionic-angular/components/app/app';
import * as import27 from 'ionic-angular/components/toolbar/toolbar';
import * as import28 from 'ionic-angular/util/keyboard';
import * as import29 from '@angular/core/src/zone/ng_zone';
import * as import30 from 'ionic-angular/components/tabs/tabs';
import * as import31 from '@angular/core/src/linker/template_ref';
import * as import32 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import33 from 'ionic-angular/components/toolbar/toolbar-title';
import * as import34 from 'ionic-angular/components/icon/icon';
import * as import35 from 'ionic-angular/components/button/button';
import * as import36 from 'ionic-angular/components/toolbar/toolbar-item';
import * as import37 from 'ionic-angular/components/navbar/navbar';
import * as import38 from '@angular/common/src/directives/ng_for';
import * as import39 from '@angular/common/src/directives/ng_if';
import * as import40 from 'ionic-angular/components/content/content';
import * as import41 from '../../node_modules/ionic-angular/components/card/card.ngfactory';
import * as import42 from 'ionic-angular/components/card/card';
export class Wrapper_TrainingDetailsPage {
  context:import0.TrainingDetailsPage;
  changed:boolean;
  constructor(p0:any,p1:any,p2:any) {
    this.changed = false;
    this.context = new import0.TrainingDetailsPage(p0,p1,p2);
  }
  detectChangesInternal(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this.changed;
    this.changed = false;
    return changed;
  }
}
var renderType_TrainingDetailsPage_Host:import2.RenderComponentType = (null as any);
class _View_TrainingDetailsPage_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _TrainingDetailsPage_0_4:Wrapper_TrainingDetailsPage;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_TrainingDetailsPage_Host0,renderType_TrainingDetailsPage_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.selectOrCreateHostElement('page-training-details',rootSelector,(null as any));
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_TrainingDetailsPage0(this.viewUtils,this.injector(0),this._appEl_0);
    this._TrainingDetailsPage_0_4 = new Wrapper_TrainingDetailsPage(this.parentInjector.get(import8.NavController),this.parentInjector.get(import9.ObjectToArray),this.parentInjector.get(import10.NavParams));
    this._appEl_0.initComponent(this._TrainingDetailsPage_0_4.context,([] as any[]),compView_0);
    compView_0.create(this._TrainingDetailsPage_0_4.context,this.projectableNodes,(null as any));
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.TrainingDetailsPage) && (0 === requestNodeIndex))) { return this._TrainingDetailsPage_0_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._TrainingDetailsPage_0_4.detectChangesInternal(this,this._el_0,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_TrainingDetailsPage_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  if ((renderType_TrainingDetailsPage_Host === (null as any))) { (renderType_TrainingDetailsPage_Host = viewUtils.createRenderComponentType('',0,import11.ViewEncapsulation.None,([] as any[]),{})); }
  return new _View_TrainingDetailsPage_Host0(viewUtils,parentInjector,declarationEl);
}
export const TrainingDetailsPageNgFactory:import12.ComponentFactory<import0.TrainingDetailsPage> = new import12.ComponentFactory<import0.TrainingDetailsPage>('page-training-details',viewFactory_TrainingDetailsPage_Host0,import0.TrainingDetailsPage);
const styles_TrainingDetailsPage:any[] = ([] as any[]);
var renderType_TrainingDetailsPage:import2.RenderComponentType = (null as any);
class _View_TrainingDetailsPage0 extends import1.AppView<import0.TrainingDetailsPage> {
  _el_0:any;
  _Header_0_3:import13.Wrapper_Header;
  _text_1:any;
  _el_2:any;
  /*private*/ _appEl_2:import3.AppElement;
  _Navbar_2_4:import14.Wrapper_Navbar;
  _text_3:any;
  _el_4:any;
  /*private*/ _appEl_4:import3.AppElement;
  _ToolbarTitle_4_4:import15.Wrapper_ToolbarTitle;
  _text_5:any;
  _text_6:any;
  _el_7:any;
  _ToolbarItem_7_3:import16.Wrapper_ToolbarItem;
  _query_Button_7_0:import17.QueryList<any>;
  _text_8:any;
  _el_9:any;
  /*private*/ _appEl_9:import3.AppElement;
  _Button_9_4:import18.Wrapper_Button;
  _text_10:any;
  _el_11:any;
  _Icon_11_3:import19.Wrapper_Icon;
  _text_12:any;
  _text_13:any;
  _text_14:any;
  _text_15:any;
  _text_16:any;
  _el_17:any;
  /*private*/ _appEl_17:import3.AppElement;
  _Content_17_4:import20.Wrapper_Content;
  _text_18:any;
  _el_19:any;
  _text_20:any;
  _el_21:any;
  _text_22:any;
  _text_23:any;
  _el_24:any;
  _text_25:any;
  _anchor_26:any;
  /*private*/ _appEl_26:import3.AppElement;
  _TemplateRef_26_5:any;
  _NgFor_26_6:import21.Wrapper_NgFor;
  _text_27:any;
  _anchor_28:any;
  /*private*/ _appEl_28:import3.AppElement;
  _TemplateRef_28_5:any;
  _NgIf_28_6:import22.Wrapper_NgIf;
  _text_29:any;
  _text_30:any;
  _text_31:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_5:any;
  /*private*/ _expr_6:any;
  /*private*/ _expr_7:any;
  /*private*/ _expr_8:any;
  _pipe_objectToArray_0:import9.ObjectToArray;
  _pipe_objectToArray_0_0:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_TrainingDetailsPage0,renderType_TrainingDetailsPage,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'ion-header',(null as any));
    this._Header_0_3 = new import13.Wrapper_Header(this.parentInjector.get(import23.Config),new import24.ElementRef(this._el_0),this.renderer,this.parentInjector.get(import25.ViewController,(null as any)));
    this._text_1 = this.renderer.createText(this._el_0,'\n\n  ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'ion-navbar',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','toolbar');
    this._appEl_2 = new import3.AppElement(2,0,this,this._el_2);
    var compView_2:any = import14.viewFactory_Navbar0(this.viewUtils,this.injector(2),this._appEl_2);
    this._Navbar_2_4 = new import14.Wrapper_Navbar(this.parentInjector.get(import26.App),this.parentInjector.get(import25.ViewController,(null as any)),this.parentInjector.get(import8.NavController,(null as any)),this.parentInjector.get(import23.Config),new import24.ElementRef(this._el_2),this.renderer);
    this._appEl_2.initComponent(this._Navbar_2_4.context,([] as any[]),compView_2);
    this._text_3 = this.renderer.createText((null as any),'\n\n    ',(null as any));
    this._el_4 = this.renderer.createElement((null as any),'ion-title',(null as any));
    this._appEl_4 = new import3.AppElement(4,2,this,this._el_4);
    var compView_4:any = import15.viewFactory_ToolbarTitle0(this.viewUtils,this.injector(4),this._appEl_4);
    this._ToolbarTitle_4_4 = new import15.Wrapper_ToolbarTitle(this.parentInjector.get(import23.Config),new import24.ElementRef(this._el_4),this.renderer,this.parentInjector.get(import27.Toolbar,(null as any)),this._Navbar_2_4.context);
    this._appEl_4.initComponent(this._ToolbarTitle_4_4.context,([] as any[]),compView_4);
    this._text_5 = this.renderer.createText((null as any),'Training Details',(null as any));
    compView_4.create(this._ToolbarTitle_4_4.context,[([] as any[]).concat([this._text_5])],(null as any));
    this._text_6 = this.renderer.createText((null as any),'\n\n    ',(null as any));
    this._el_7 = this.renderer.createElement((null as any),'ion-buttons',(null as any));
    this.renderer.setElementAttribute(this._el_7,'end','');
    this._ToolbarItem_7_3 = new import16.Wrapper_ToolbarItem(this.parentInjector.get(import23.Config),new import24.ElementRef(this._el_7),this.renderer,this.parentInjector.get(import27.Toolbar,(null as any)),this._Navbar_2_4.context);
    this._query_Button_7_0 = new import17.QueryList<any>();
    this._text_8 = this.renderer.createText(this._el_7,'\n     ',(null as any));
    this._el_9 = this.renderer.createElement(this._el_7,'button',(null as any));
    this.renderer.setElementAttribute(this._el_9,'ion-button','');
    this._appEl_9 = new import3.AppElement(9,7,this,this._el_9);
    var compView_9:any = import18.viewFactory_Button0(this.viewUtils,this.injector(9),this._appEl_9);
    this._Button_9_4 = new import18.Wrapper_Button((null as any),'',this.parentInjector.get(import23.Config),new import24.ElementRef(this._el_9),this.renderer);
    this._appEl_9.initComponent(this._Button_9_4.context,([] as any[]),compView_9);
    this._text_10 = this.renderer.createText((null as any),'\n       ',(null as any));
    this._el_11 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_11,'ios','ios-add');
    this.renderer.setElementAttribute(this._el_11,'md','md-add');
    this.renderer.setElementAttribute(this._el_11,'role','img');
    this._Icon_11_3 = new import19.Wrapper_Icon(this.parentInjector.get(import23.Config),new import24.ElementRef(this._el_11),this.renderer);
    this._text_12 = this.renderer.createText((null as any),'\n     ',(null as any));
      compView_9.create(this._Button_9_4.context,[([] as any[]).concat([
        this._text_10,
        this._el_11,
        this._text_12
      ]
    )],(null as any));
    this._text_13 = this.renderer.createText(this._el_7,'\n   ',(null as any));
    this._text_14 = this.renderer.createText((null as any),'\n\n  ',(null as any));
    compView_2.create(this._Navbar_2_4.context,[
      ([] as any[]),
      ([] as any[]),
      ([] as any[]).concat([this._el_7]),
      ([] as any[]).concat([
        this._text_3,
        this._el_4,
        this._text_6,
        this._text_14
      ]
      )
    ]
    ,(null as any));
    this._text_15 = this.renderer.createText(this._el_0,'\n\n',(null as any));
    this._text_16 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._el_17 = this.renderer.createElement(parentRenderNode,'ion-content',(null as any));
    this.renderer.setElementAttribute(this._el_17,'padding','');
    this._appEl_17 = new import3.AppElement(17,(null as any),this,this._el_17);
    var compView_17:any = import20.viewFactory_Content0(this.viewUtils,this.injector(17),this._appEl_17);
    this._Content_17_4 = new import20.Wrapper_Content(this.parentInjector.get(import23.Config),new import24.ElementRef(this._el_17),this.renderer,this.parentInjector.get(import26.App),this.parentInjector.get(import28.Keyboard),this.parentInjector.get(import29.NgZone),this.parentInjector.get(import25.ViewController,(null as any)),this.parentInjector.get(import30.Tabs,(null as any)));
    this._appEl_17.initComponent(this._Content_17_4.context,([] as any[]),compView_17);
    this._text_18 = this.renderer.createText((null as any),'\n\n  ',(null as any));
    this._el_19 = this.renderer.createElement((null as any),'h6',(null as any));
    this._text_20 = this.renderer.createText(this._el_19,'',(null as any));
    this._el_21 = this.renderer.createElement(this._el_19,'br',(null as any));
    this._text_22 = this.renderer.createText(this._el_19,'',(null as any));
    this._text_23 = this.renderer.createText((null as any),'\n\n  ',(null as any));
    this._el_24 = this.renderer.createElement((null as any),'div',(null as any));
    this._text_25 = this.renderer.createText(this._el_24,'\n\n    ',(null as any));
    this._anchor_26 = this.renderer.createTemplateAnchor(this._el_24,(null as any));
    this._appEl_26 = new import3.AppElement(26,24,this,this._anchor_26);
    this._TemplateRef_26_5 = new import31.TemplateRef_(this._appEl_26,viewFactory_TrainingDetailsPage1);
    this._NgFor_26_6 = new import21.Wrapper_NgFor(this._appEl_26.vcRef,this._TemplateRef_26_5,this.parentInjector.get(import32.IterableDiffers),this.ref);
    this._text_27 = this.renderer.createText(this._el_24,'\n\n    ',(null as any));
    this._anchor_28 = this.renderer.createTemplateAnchor(this._el_24,(null as any));
    this._appEl_28 = new import3.AppElement(28,24,this,this._anchor_28);
    this._TemplateRef_28_5 = new import31.TemplateRef_(this._appEl_28,viewFactory_TrainingDetailsPage2);
    this._NgIf_28_6 = new import22.Wrapper_NgIf(this._appEl_28.vcRef,this._TemplateRef_28_5);
    this._text_29 = this.renderer.createText(this._el_24,'\n\n  ',(null as any));
    this._text_30 = this.renderer.createText((null as any),'\n\n',(null as any));
    compView_17.create(this._Content_17_4.context,[
      ([] as any[]),
      ([] as any[]).concat([
        this._text_18,
        this._el_19,
        this._text_23,
        this._el_24,
        this._text_30
      ]
      ),
      ([] as any[])
    ]
    ,(null as any));
    this._text_31 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this._expr_1 = import7.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_9,'click',this.eventHandler(this._handle_click_9_0.bind(this)));
    this._expr_5 = import7.UNINITIALIZED;
    this._expr_6 = import7.UNINITIALIZED;
    this._expr_7 = import7.UNINITIALIZED;
    this._expr_8 = import7.UNINITIALIZED;
    this._pipe_objectToArray_0 = new import9.ObjectToArray();
    this._pipe_objectToArray_0_0 = import4.pureProxy1(this._pipe_objectToArray_0.transform.bind(this._pipe_objectToArray_0));
    this.init(([] as any[]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._text_13,
      this._text_14,
      this._text_15,
      this._text_16,
      this._el_17,
      this._text_18,
      this._el_19,
      this._text_20,
      this._el_21,
      this._text_22,
      this._text_23,
      this._el_24,
      this._text_25,
      this._anchor_26,
      this._text_27,
      this._anchor_28,
      this._text_29,
      this._text_30,
      this._text_31
    ]
    ,[disposable_0],([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import33.ToolbarTitle) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 5)))) { return this._ToolbarTitle_4_4.context; }
    if (((token === import34.Icon) && (11 === requestNodeIndex))) { return this._Icon_11_3.context; }
    if (((token === import35.Button) && ((9 <= requestNodeIndex) && (requestNodeIndex <= 12)))) { return this._Button_9_4.context; }
    if (((token === import36.ToolbarItem) && ((7 <= requestNodeIndex) && (requestNodeIndex <= 13)))) { return this._ToolbarItem_7_3.context; }
    if (((token === import37.Navbar) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 14)))) { return this._Navbar_2_4.context; }
    if (((token === import27.Header) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 15)))) { return this._Header_0_3.context; }
    if (((token === import31.TemplateRef) && (26 === requestNodeIndex))) { return this._TemplateRef_26_5; }
    if (((token === import38.NgFor) && (26 === requestNodeIndex))) { return this._NgFor_26_6.context; }
    if (((token === import31.TemplateRef) && (28 === requestNodeIndex))) { return this._TemplateRef_28_5; }
    if (((token === import39.NgIf) && (28 === requestNodeIndex))) { return this._NgIf_28_6.context; }
    if (((token === import40.Content) && ((17 <= requestNodeIndex) && (requestNodeIndex <= 30)))) { return this._Content_17_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const valUnwrapper:any = new import7.ValueUnwrapper();
    this._Header_0_3.detectChangesInternal(this,this._el_0,throwOnChange);
    this._Navbar_2_4.detectChangesInternal(this,this._el_2,throwOnChange);
    if (this._ToolbarTitle_4_4.detectChangesInternal(this,this._el_4,throwOnChange)) { this._appEl_4.componentView.markAsCheckOnce(); }
    this._ToolbarItem_7_3.detectChangesInternal(this,this._el_7,throwOnChange);
    if (this._Button_9_4.detectChangesInternal(this,this._el_9,throwOnChange)) { this._appEl_9.componentView.markAsCheckOnce(); }
    const currVal_3:any = 'ios-add';
    this._Icon_11_3.check_ios(currVal_3,throwOnChange,false);
    const currVal_4:any = 'md-add';
    this._Icon_11_3.check_md(currVal_4,throwOnChange,false);
    this._Icon_11_3.detectChangesInternal(this,this._el_11,throwOnChange);
    if (this._Content_17_4.detectChangesInternal(this,this._el_17,throwOnChange)) { this._appEl_17.componentView.markAsCheckOnce(); }
    valUnwrapper.reset();
    const currVal_9:any = valUnwrapper.unwrap(import4.castByValue(this._pipe_objectToArray_0_0,this._pipe_objectToArray_0.transform)(this.context.training.Sessions));
    this._NgFor_26_6.check_ngForOf(currVal_9,throwOnChange,valUnwrapper.hasWrappedValue);
    this._NgFor_26_6.detectChangesInternal(this,this._anchor_26,throwOnChange);
    const currVal_10:boolean = !((this.context.training == (null as any))? (null as any): this.context.training.Sessions);
    this._NgIf_28_6.check_ngIf(currVal_10,throwOnChange,false);
    this._NgIf_28_6.detectChangesInternal(this,this._anchor_28,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_7_0.dirty) {
        this._query_Button_7_0.reset([this._Button_9_4.context]);
        this._ToolbarItem_7_3.context._buttons = this._query_Button_7_0;
        this._query_Button_7_0.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._Button_9_4.context.ngAfterContentInit(); }
    }
    const currVal_0:any = this._Navbar_2_4.context._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setElementProperty(this._el_2,'hidden',currVal_0);
      this._expr_0 = currVal_0;
    }
    const currVal_1:any = this._Navbar_2_4.context._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementClass(this._el_2,'statusbar-padding',currVal_1);
      this._expr_1 = currVal_1;
    }
    const currVal_5:any = this._Icon_11_3.context._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this.renderer.setElementClass(this._el_11,'hide',currVal_5);
      this._expr_5 = currVal_5;
    }
    const currVal_6:any = this._Content_17_4.context._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this.renderer.setElementClass(this._el_17,'statusbar-padding',currVal_6);
      this._expr_6 = currVal_6;
    }
    const currVal_7:any = import4.interpolate(1,'',this.context.training.Title,' ');
    if (import4.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this.renderer.setText(this._text_20,currVal_7);
      this._expr_7 = currVal_7;
    }
    const currVal_8:any = import4.interpolate(1,' ',this.context.training.Date,'');
    if (import4.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this.renderer.setText(this._text_22,currVal_8);
      this._expr_8 = currVal_8;
    }
    this.detectViewChildrenChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._Navbar_2_4.context.ngAfterViewInit(); } }
  }
  destroyInternal():void {
    this._Icon_11_3.context.ngOnDestroy();
    this._Content_17_4.context.ngOnDestroy();
  }
  private _handle_click_9_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.goToAddSession()) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_TrainingDetailsPage0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<import0.TrainingDetailsPage> {
  if ((renderType_TrainingDetailsPage === (null as any))) { (renderType_TrainingDetailsPage = viewUtils.createRenderComponentType('',0,import11.ViewEncapsulation.None,styles_TrainingDetailsPage,{})); }
  return new _View_TrainingDetailsPage0(viewUtils,parentInjector,declarationEl);
}
class _View_TrainingDetailsPage1 extends import1.AppView<any> {
  _el_0:any;
  _Card_0_3:import41.Wrapper_Card;
  _text_1:any;
  _el_2:any;
  _CardHeader_2_3:import41.Wrapper_CardHeader;
  _text_3:any;
  _text_4:any;
  _el_5:any;
  _CardContent_5_3:import41.Wrapper_CardContent;
  _text_6:any;
  _el_7:any;
  /*private*/ _appEl_7:import3.AppElement;
  _Button_7_4:import18.Wrapper_Button;
  _text_8:any;
  _text_9:any;
  _text_10:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_TrainingDetailsPage1,renderType_TrainingDetailsPage,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'ion-card',(null as any));
    this._Card_0_3 = new import41.Wrapper_Card(this.parent.parentInjector.get(import23.Config),new import24.ElementRef(this._el_0),this.renderer);
    this._text_1 = this.renderer.createText(this._el_0,'\n\n      ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'ion-card-header',(null as any));
    this._CardHeader_2_3 = new import41.Wrapper_CardHeader(this.parent.parentInjector.get(import23.Config),new import24.ElementRef(this._el_2),this.renderer);
    this._text_3 = this.renderer.createText(this._el_2,'',(null as any));
    this._text_4 = this.renderer.createText(this._el_0,'\n\n      ',(null as any));
    this._el_5 = this.renderer.createElement(this._el_0,'ion-card-content',(null as any));
    this._CardContent_5_3 = new import41.Wrapper_CardContent(this.parent.parentInjector.get(import23.Config),new import24.ElementRef(this._el_5),this.renderer);
    this._text_6 = this.renderer.createText(this._el_5,'',(null as any));
    this._el_7 = this.renderer.createElement(this._el_5,'button',(null as any));
    this.renderer.setElementAttribute(this._el_7,'clear','');
    this.renderer.setElementAttribute(this._el_7,'ion-button','');
    this.renderer.setElementAttribute(this._el_7,'right','');
    this.renderer.setElementAttribute(this._el_7,'small','');
    this._appEl_7 = new import3.AppElement(7,5,this,this._el_7);
    var compView_7:any = import18.viewFactory_Button0(this.viewUtils,this.injector(7),this._appEl_7);
    this._Button_7_4 = new import18.Wrapper_Button((null as any),'',this.parent.parentInjector.get(import23.Config),new import24.ElementRef(this._el_7),this.renderer);
    this._appEl_7.initComponent(this._Button_7_4.context,([] as any[]),compView_7);
    this._text_8 = this.renderer.createText((null as any),' View ',(null as any));
    compView_7.create(this._Button_7_4.context,[([] as any[]).concat([this._text_8])],(null as any));
    this._text_9 = this.renderer.createText(this._el_5,'\n      ',(null as any));
    this._text_10 = this.renderer.createText(this._el_0,'\n\n    ',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this._expr_1 = import7.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_7,'click',this.eventHandler(this._handle_click_7_0.bind(this)));
    this.init(([] as any[]).concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._text_9,
      this._text_10
    ]
    ,[disposable_0],([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import42.CardHeader) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 3)))) { return this._CardHeader_2_3.context; }
    if (((token === import35.Button) && ((7 <= requestNodeIndex) && (requestNodeIndex <= 8)))) { return this._Button_7_4.context; }
    if (((token === import42.CardContent) && ((5 <= requestNodeIndex) && (requestNodeIndex <= 9)))) { return this._CardContent_5_3.context; }
    if (((token === import42.Card) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 10)))) { return this._Card_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._Card_0_3.detectChangesInternal(this,this._el_0,throwOnChange);
    this._CardHeader_2_3.detectChangesInternal(this,this._el_2,throwOnChange);
    this._CardContent_5_3.detectChangesInternal(this,this._el_5,throwOnChange);
    const currVal_3:any = '';
    this._Button_7_4.check_small(currVal_3,throwOnChange,false);
    const currVal_4:any = '';
    this._Button_7_4.check_clear(currVal_4,throwOnChange,false);
    if (this._Button_7_4.detectChangesInternal(this,this._el_7,throwOnChange)) { this._appEl_7.componentView.markAsCheckOnce(); }
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._Button_7_4.context.ngAfterContentInit(); } }
    const currVal_0:any = import4.interpolate(1,'\n        ',this.context.$implicit.Title,'\n      ');
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setText(this._text_3,currVal_0);
      this._expr_0 = currVal_0;
    }
    const currVal_1:any = import4.interpolate(1,'\n        ',this.context.$implicit.Description,'\n        ');
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setText(this._text_6,currVal_1);
      this._expr_1 = currVal_1;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  private _handle_click_7_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.context.sessionDetails()) !== false);
    return (true && pd_0);
  }
}
function viewFactory_TrainingDetailsPage1(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  return new _View_TrainingDetailsPage1(viewUtils,parentInjector,declarationEl);
}
class _View_TrainingDetailsPage2 extends import1.AppView<any> {
  _text_0:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_TrainingDetailsPage2,renderType_TrainingDetailsPage,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._text_0 = this.renderer.createText((null as any),'\n      No hay sesiones de entrenamiento\n    ',(null as any));
    this.init(([] as any[]).concat([this._text_0]),[this._text_0],([] as any[]),([] as any[]));
    return (null as any);
  }
}
function viewFactory_TrainingDetailsPage2(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  return new _View_TrainingDetailsPage2(viewUtils,parentInjector,declarationEl);
}