/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from './signup';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/element';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from 'ionic-angular/navigation/nav-controller';
import * as import9 from '@angular/forms/src/form_builder';
import * as import10 from '../../providers/auth-data';
import * as import11 from 'ionic-angular/components/loading/loading';
import * as import12 from 'ionic-angular/components/alert/alert';
import * as import13 from '@angular/core/src/metadata/view';
import * as import14 from '@angular/core/src/linker/component_factory';
import * as import15 from '../../node_modules/ionic-angular/components/toolbar/toolbar.ngfactory';
import * as import16 from '../../node_modules/ionic-angular/components/navbar/navbar.ngfactory';
import * as import17 from '../../node_modules/ionic-angular/components/toolbar/toolbar-title.ngfactory';
import * as import18 from '../../node_modules/ionic-angular/components/content/content.ngfactory';
import * as import19 from '../../node_modules/@angular/forms/src/directives/reactive_directives/form_group_directive.ngfactory';
import * as import20 from '../../node_modules/@angular/forms/src/directives/ng_control_status.ngfactory';
import * as import21 from '../../node_modules/ionic-angular/components/item/item.ngfactory';
import * as import22 from '@angular/core/src/linker/query_list';
import * as import23 from '../../node_modules/ionic-angular/components/label/label.ngfactory';
import * as import24 from '../../node_modules/@angular/forms/src/directives/reactive_directives/form_control_name.ngfactory';
import * as import25 from '../../node_modules/ionic-angular/components/input/input.ngfactory';
import * as import26 from '../../node_modules/ionic-angular/components/button/button.ngfactory';
import * as import27 from 'ionic-angular/config/config';
import * as import28 from '@angular/core/src/linker/element_ref';
import * as import29 from 'ionic-angular/navigation/view-controller';
import * as import30 from 'ionic-angular/components/app/app';
import * as import31 from 'ionic-angular/components/toolbar/toolbar';
import * as import32 from 'ionic-angular/util/keyboard';
import * as import33 from '@angular/core/src/zone/ng_zone';
import * as import34 from 'ionic-angular/components/tabs/tabs';
import * as import35 from 'ionic-angular/util/form';
import * as import36 from 'ionic-angular/components/item/item-reorder';
import * as import37 from 'ionic-angular/platform/platform';
import * as import38 from 'ionic-angular/components/toolbar/toolbar-title';
import * as import39 from 'ionic-angular/components/navbar/navbar';
import * as import40 from 'ionic-angular/components/label/label';
import * as import41 from '@angular/forms/src/directives/reactive_directives/form_control_name';
import * as import42 from '@angular/forms/src/directives/ng_control';
import * as import43 from '@angular/forms/src/directives/ng_control_status';
import * as import44 from 'ionic-angular/components/input/input';
import * as import45 from 'ionic-angular/components/item/item';
import * as import46 from 'ionic-angular/components/button/button';
import * as import47 from '@angular/forms/src/directives/reactive_directives/form_group_directive';
import * as import48 from '@angular/forms/src/directives/control_container';
import * as import49 from 'ionic-angular/components/content/content';
export class Wrapper_SignupPage {
  context:import0.SignupPage;
  changed:boolean;
  constructor(p0:any,p1:any,p2:any,p3:any,p4:any) {
    this.changed = false;
    this.context = new import0.SignupPage(p0,p1,p2,p3,p4);
  }
  detectChangesInternal(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this.changed;
    this.changed = false;
    return changed;
  }
}
var renderType_SignupPage_Host:import2.RenderComponentType = (null as any);
class _View_SignupPage_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _SignupPage_0_4:Wrapper_SignupPage;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_SignupPage_Host0,renderType_SignupPage_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.selectOrCreateHostElement('ng-component',rootSelector,(null as any));
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_SignupPage0(this.viewUtils,this.injector(0),this._appEl_0);
    this._SignupPage_0_4 = new Wrapper_SignupPage(this.parentInjector.get(import8.NavController),this.parentInjector.get(import9.FormBuilder),this.parentInjector.get(import10.AuthData),this.parentInjector.get(import11.LoadingController),this.parentInjector.get(import12.AlertController));
    this._appEl_0.initComponent(this._SignupPage_0_4.context,([] as any[]),compView_0);
    compView_0.create(this._SignupPage_0_4.context,this.projectableNodes,(null as any));
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.SignupPage) && (0 === requestNodeIndex))) { return this._SignupPage_0_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._SignupPage_0_4.detectChangesInternal(this,this._el_0,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_SignupPage_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  if ((renderType_SignupPage_Host === (null as any))) { (renderType_SignupPage_Host = viewUtils.createRenderComponentType('',0,import13.ViewEncapsulation.None,([] as any[]),{})); }
  return new _View_SignupPage_Host0(viewUtils,parentInjector,declarationEl);
}
export const SignupPageNgFactory:import14.ComponentFactory<import0.SignupPage> = new import14.ComponentFactory<import0.SignupPage>('ng-component',viewFactory_SignupPage_Host0,import0.SignupPage);
const styles_SignupPage:any[] = ([] as any[]);
var renderType_SignupPage:import2.RenderComponentType = (null as any);
class _View_SignupPage0 extends import1.AppView<import0.SignupPage> {
  _text_0:any;
  _el_1:any;
  _Header_1_3:import15.Wrapper_Header;
  _text_2:any;
  _el_3:any;
  /*private*/ _appEl_3:import3.AppElement;
  _Navbar_3_4:import16.Wrapper_Navbar;
  _text_4:any;
  _el_5:any;
  /*private*/ _appEl_5:import3.AppElement;
  _ToolbarTitle_5_4:import17.Wrapper_ToolbarTitle;
  _text_6:any;
  _text_7:any;
  _text_8:any;
  _text_9:any;
  _el_10:any;
  /*private*/ _appEl_10:import3.AppElement;
  _Content_10_4:import18.Wrapper_Content;
  _text_11:any;
  _el_12:any;
  _FormGroupDirective_12_3:import19.Wrapper_FormGroupDirective;
  _ControlContainer_12_4:any;
  _NgControlStatusGroup_12_5:import20.Wrapper_NgControlStatusGroup;
  _text_13:any;
  _el_14:any;
  /*private*/ _appEl_14:import3.AppElement;
  _Item_14_4:import21.Wrapper_Item;
  _ItemContent_14_5:import21.Wrapper_ItemContent;
  _query_Label_14_0:import22.QueryList<any>;
  _query_Button_14_1:import22.QueryList<any>;
  _query_Icon_14_2:import22.QueryList<any>;
  _text_15:any;
  _el_16:any;
  _Label_16_3:import23.Wrapper_Label;
  _text_17:any;
  _text_18:any;
  _el_19:any;
  /*private*/ _appEl_19:import3.AppElement;
  _FormControlName_19_4:import24.Wrapper_FormControlName;
  _NgControl_19_5:any;
  _NgControlStatus_19_6:import20.Wrapper_NgControlStatus;
  _TextInput_19_7:import25.Wrapper_TextInput;
  _text_20:any;
  _text_21:any;
  _el_22:any;
  /*private*/ _appEl_22:import3.AppElement;
  _Item_22_4:import21.Wrapper_Item;
  _ItemContent_22_5:import21.Wrapper_ItemContent;
  _query_Label_22_0:import22.QueryList<any>;
  _query_Button_22_1:import22.QueryList<any>;
  _query_Icon_22_2:import22.QueryList<any>;
  _text_23:any;
  _el_24:any;
  _Label_24_3:import23.Wrapper_Label;
  _text_25:any;
  _text_26:any;
  _el_27:any;
  /*private*/ _appEl_27:import3.AppElement;
  _FormControlName_27_4:import24.Wrapper_FormControlName;
  _NgControl_27_5:any;
  _NgControlStatus_27_6:import20.Wrapper_NgControlStatus;
  _TextInput_27_7:import25.Wrapper_TextInput;
  _text_28:any;
  _text_29:any;
  _el_30:any;
  /*private*/ _appEl_30:import3.AppElement;
  _Item_30_4:import21.Wrapper_Item;
  _ItemContent_30_5:import21.Wrapper_ItemContent;
  _query_Label_30_0:import22.QueryList<any>;
  _query_Button_30_1:import22.QueryList<any>;
  _query_Icon_30_2:import22.QueryList<any>;
  _text_31:any;
  _el_32:any;
  _Label_32_3:import23.Wrapper_Label;
  _text_33:any;
  _text_34:any;
  _el_35:any;
  /*private*/ _appEl_35:import3.AppElement;
  _FormControlName_35_4:import24.Wrapper_FormControlName;
  _NgControl_35_5:any;
  _NgControlStatus_35_6:import20.Wrapper_NgControlStatus;
  _TextInput_35_7:import25.Wrapper_TextInput;
  _text_36:any;
  _text_37:any;
  _el_38:any;
  /*private*/ _appEl_38:import3.AppElement;
  _Item_38_4:import21.Wrapper_Item;
  _ItemContent_38_5:import21.Wrapper_ItemContent;
  _query_Label_38_0:import22.QueryList<any>;
  _query_Button_38_1:import22.QueryList<any>;
  _query_Icon_38_2:import22.QueryList<any>;
  _text_39:any;
  _el_40:any;
  _Label_40_3:import23.Wrapper_Label;
  _text_41:any;
  _text_42:any;
  _el_43:any;
  /*private*/ _appEl_43:import3.AppElement;
  _FormControlName_43_4:import24.Wrapper_FormControlName;
  _NgControl_43_5:any;
  _NgControlStatus_43_6:import20.Wrapper_NgControlStatus;
  _TextInput_43_7:import25.Wrapper_TextInput;
  _text_44:any;
  _text_45:any;
  _el_46:any;
  /*private*/ _appEl_46:import3.AppElement;
  _Item_46_4:import21.Wrapper_Item;
  _ItemContent_46_5:import21.Wrapper_ItemContent;
  _query_Label_46_0:import22.QueryList<any>;
  _query_Button_46_1:import22.QueryList<any>;
  _query_Icon_46_2:import22.QueryList<any>;
  _text_47:any;
  _el_48:any;
  _Label_48_3:import23.Wrapper_Label;
  _text_49:any;
  _text_50:any;
  _el_51:any;
  /*private*/ _appEl_51:import3.AppElement;
  _FormControlName_51_4:import24.Wrapper_FormControlName;
  _NgControl_51_5:any;
  _NgControlStatus_51_6:import20.Wrapper_NgControlStatus;
  _TextInput_51_7:import25.Wrapper_TextInput;
  _text_52:any;
  _text_53:any;
  _el_54:any;
  /*private*/ _appEl_54:import3.AppElement;
  _Button_54_4:import26.Wrapper_Button;
  _text_55:any;
  _text_56:any;
  _text_57:any;
  _text_58:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_7:any;
  /*private*/ _expr_8:any;
  /*private*/ _expr_9:any;
  /*private*/ _expr_10:any;
  /*private*/ _expr_11:any;
  /*private*/ _expr_12:any;
  /*private*/ _expr_14:any;
  /*private*/ _expr_15:any;
  /*private*/ _expr_16:any;
  /*private*/ _expr_17:any;
  /*private*/ _expr_18:any;
  /*private*/ _expr_19:any;
  /*private*/ _expr_23:any;
  /*private*/ _expr_24:any;
  /*private*/ _expr_25:any;
  /*private*/ _expr_26:any;
  /*private*/ _expr_27:any;
  /*private*/ _expr_28:any;
  /*private*/ _expr_32:any;
  /*private*/ _expr_33:any;
  /*private*/ _expr_34:any;
  /*private*/ _expr_35:any;
  /*private*/ _expr_36:any;
  /*private*/ _expr_37:any;
  /*private*/ _expr_41:any;
  /*private*/ _expr_42:any;
  /*private*/ _expr_43:any;
  /*private*/ _expr_44:any;
  /*private*/ _expr_45:any;
  /*private*/ _expr_46:any;
  /*private*/ _expr_50:any;
  /*private*/ _expr_51:any;
  /*private*/ _expr_52:any;
  /*private*/ _expr_53:any;
  /*private*/ _expr_54:any;
  /*private*/ _expr_55:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_SignupPage0,renderType_SignupPage,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._text_0 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_1 = this.renderer.createElement(parentRenderNode,'ion-header',(null as any));
    this._Header_1_3 = new import15.Wrapper_Header(this.parentInjector.get(import27.Config),new import28.ElementRef(this._el_1),this.renderer,this.parentInjector.get(import29.ViewController,(null as any)));
    this._text_2 = this.renderer.createText(this._el_1,'\n\n  ',(null as any));
    this._el_3 = this.renderer.createElement(this._el_1,'ion-navbar',(null as any));
    this.renderer.setElementAttribute(this._el_3,'class','toolbar');
    this._appEl_3 = new import3.AppElement(3,1,this,this._el_3);
    var compView_3:any = import16.viewFactory_Navbar0(this.viewUtils,this.injector(3),this._appEl_3);
    this._Navbar_3_4 = new import16.Wrapper_Navbar(this.parentInjector.get(import30.App),this.parentInjector.get(import29.ViewController,(null as any)),this.parentInjector.get(import8.NavController,(null as any)),this.parentInjector.get(import27.Config),new import28.ElementRef(this._el_3),this.renderer);
    this._appEl_3.initComponent(this._Navbar_3_4.context,([] as any[]),compView_3);
    this._text_4 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_5 = this.renderer.createElement((null as any),'ion-title',(null as any));
    this._appEl_5 = new import3.AppElement(5,3,this,this._el_5);
    var compView_5:any = import17.viewFactory_ToolbarTitle0(this.viewUtils,this.injector(5),this._appEl_5);
    this._ToolbarTitle_5_4 = new import17.Wrapper_ToolbarTitle(this.parentInjector.get(import27.Config),new import28.ElementRef(this._el_5),this.renderer,this.parentInjector.get(import31.Toolbar,(null as any)),this._Navbar_3_4.context);
    this._appEl_5.initComponent(this._ToolbarTitle_5_4.context,([] as any[]),compView_5);
    this._text_6 = this.renderer.createText((null as any),'signup',(null as any));
    compView_5.create(this._ToolbarTitle_5_4.context,[([] as any[]).concat([this._text_6])],(null as any));
    this._text_7 = this.renderer.createText((null as any),'\n  ',(null as any));
    compView_3.create(this._Navbar_3_4.context,[
      ([] as any[]),
      ([] as any[]),
      ([] as any[]),
      ([] as any[]).concat([
        this._text_4,
        this._el_5,
        this._text_7
      ]
      )
    ]
    ,(null as any));
    this._text_8 = this.renderer.createText(this._el_1,'\n\n',(null as any));
    this._text_9 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._el_10 = this.renderer.createElement(parentRenderNode,'ion-content',(null as any));
    this.renderer.setElementAttribute(this._el_10,'class','signup');
    this.renderer.setElementAttribute(this._el_10,'padding','');
    this._appEl_10 = new import3.AppElement(10,(null as any),this,this._el_10);
    var compView_10:any = import18.viewFactory_Content0(this.viewUtils,this.injector(10),this._appEl_10);
    this._Content_10_4 = new import18.Wrapper_Content(this.parentInjector.get(import27.Config),new import28.ElementRef(this._el_10),this.renderer,this.parentInjector.get(import30.App),this.parentInjector.get(import32.Keyboard),this.parentInjector.get(import33.NgZone),this.parentInjector.get(import29.ViewController,(null as any)),this.parentInjector.get(import34.Tabs,(null as any)));
    this._appEl_10.initComponent(this._Content_10_4.context,([] as any[]),compView_10);
    this._text_11 = this.renderer.createText((null as any),'\n\n  ',(null as any));
    this._el_12 = this.renderer.createElement((null as any),'form',(null as any));
    this.renderer.setElementAttribute(this._el_12,'novalidate','');
    this._FormGroupDirective_12_3 = new import19.Wrapper_FormGroupDirective((null as any),(null as any));
    this._ControlContainer_12_4 = this._FormGroupDirective_12_3.context;
    this._NgControlStatusGroup_12_5 = new import20.Wrapper_NgControlStatusGroup(this._ControlContainer_12_4);
    this._text_13 = this.renderer.createText(this._el_12,'\n\n    ',(null as any));
    this._el_14 = this.renderer.createElement(this._el_12,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_14,'class','item item-block');
    this._appEl_14 = new import3.AppElement(14,12,this,this._el_14);
    var compView_14:any = import21.viewFactory_Item0(this.viewUtils,this.injector(14),this._appEl_14);
    this._Item_14_4 = new import21.Wrapper_Item(this.parentInjector.get(import35.Form),this.parentInjector.get(import27.Config),new import28.ElementRef(this._el_14),this.renderer,this.parentInjector.get(import36.ItemReorder,(null as any)));
    this._ItemContent_14_5 = new import21.Wrapper_ItemContent();
    this._query_Label_14_0 = new import22.QueryList<any>();
    this._query_Button_14_1 = new import22.QueryList<any>();
    this._query_Icon_14_2 = new import22.QueryList<any>();
    this._appEl_14.initComponent(this._Item_14_4.context,([] as any[]),compView_14);
    this._text_15 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_16 = this.renderer.createElement((null as any),'ion-label',(null as any));
    this.renderer.setElementAttribute(this._el_16,'stacked','');
    this._Label_16_3 = new import23.Wrapper_Label(this.parentInjector.get(import27.Config),new import28.ElementRef(this._el_16),this.renderer,(null as any),'',(null as any),(null as any));
    this._text_17 = this.renderer.createText(this._el_16,'Email',(null as any));
    this._text_18 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_19 = this.renderer.createElement((null as any),'ion-input',(null as any));
    this.renderer.setElementAttribute(this._el_19,'formControlName','email');
    this.renderer.setElementAttribute(this._el_19,'placeholder','Your email address');
    this.renderer.setElementAttribute(this._el_19,'type','email');
    this._appEl_19 = new import3.AppElement(19,14,this,this._el_19);
    var compView_19:any = import25.viewFactory_TextInput0(this.viewUtils,this.injector(19),this._appEl_19);
    this._FormControlName_19_4 = new import24.Wrapper_FormControlName(this._ControlContainer_12_4,(null as any),(null as any),(null as any));
    this._NgControl_19_5 = this._FormControlName_19_4.context;
    this._NgControlStatus_19_6 = new import20.Wrapper_NgControlStatus(this._NgControl_19_5);
    this._TextInput_19_7 = new import25.Wrapper_TextInput(this.parentInjector.get(import27.Config),this.parentInjector.get(import35.Form),this._Item_14_4.context,this.parentInjector.get(import30.App),this.parentInjector.get(import37.Platform),new import28.ElementRef(this._el_19),this.renderer,this._Content_10_4.context,this.parentInjector.get(import8.NavController,(null as any)),this._NgControl_19_5);
    this._appEl_19.initComponent(this._TextInput_19_7.context,([] as any[]),compView_19);
    compView_19.create(this._TextInput_19_7.context,([] as any[]),(null as any));
    this._text_20 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._query_Label_14_0.reset([this._Label_16_3.context]);
    this._Item_14_4.context.contentLabel = this._query_Label_14_0.first;
    compView_14.create(this._Item_14_4.context,[
      ([] as any[]),
      ([] as any[]).concat([this._el_16]),
      ([] as any[]).concat([
        this._text_15,
        this._text_18,
        this._text_20
      ]
      ),
      ([] as any[]).concat([this._el_19]),
      ([] as any[])
    ]
    ,(null as any));
    this._text_21 = this.renderer.createText(this._el_12,'\n\n    ',(null as any));
    this._el_22 = this.renderer.createElement(this._el_12,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_22,'class','item item-block');
    this._appEl_22 = new import3.AppElement(22,12,this,this._el_22);
    var compView_22:any = import21.viewFactory_Item0(this.viewUtils,this.injector(22),this._appEl_22);
    this._Item_22_4 = new import21.Wrapper_Item(this.parentInjector.get(import35.Form),this.parentInjector.get(import27.Config),new import28.ElementRef(this._el_22),this.renderer,this.parentInjector.get(import36.ItemReorder,(null as any)));
    this._ItemContent_22_5 = new import21.Wrapper_ItemContent();
    this._query_Label_22_0 = new import22.QueryList<any>();
    this._query_Button_22_1 = new import22.QueryList<any>();
    this._query_Icon_22_2 = new import22.QueryList<any>();
    this._appEl_22.initComponent(this._Item_22_4.context,([] as any[]),compView_22);
    this._text_23 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_24 = this.renderer.createElement((null as any),'ion-label',(null as any));
    this.renderer.setElementAttribute(this._el_24,'stacked','');
    this._Label_24_3 = new import23.Wrapper_Label(this.parentInjector.get(import27.Config),new import28.ElementRef(this._el_24),this.renderer,(null as any),'',(null as any),(null as any));
    this._text_25 = this.renderer.createText(this._el_24,'Password',(null as any));
    this._text_26 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_27 = this.renderer.createElement((null as any),'ion-input',(null as any));
    this.renderer.setElementAttribute(this._el_27,'formControlName','password');
    this.renderer.setElementAttribute(this._el_27,'placeholder','Your password');
    this.renderer.setElementAttribute(this._el_27,'type','password');
    this._appEl_27 = new import3.AppElement(27,22,this,this._el_27);
    var compView_27:any = import25.viewFactory_TextInput0(this.viewUtils,this.injector(27),this._appEl_27);
    this._FormControlName_27_4 = new import24.Wrapper_FormControlName(this._ControlContainer_12_4,(null as any),(null as any),(null as any));
    this._NgControl_27_5 = this._FormControlName_27_4.context;
    this._NgControlStatus_27_6 = new import20.Wrapper_NgControlStatus(this._NgControl_27_5);
    this._TextInput_27_7 = new import25.Wrapper_TextInput(this.parentInjector.get(import27.Config),this.parentInjector.get(import35.Form),this._Item_22_4.context,this.parentInjector.get(import30.App),this.parentInjector.get(import37.Platform),new import28.ElementRef(this._el_27),this.renderer,this._Content_10_4.context,this.parentInjector.get(import8.NavController,(null as any)),this._NgControl_27_5);
    this._appEl_27.initComponent(this._TextInput_27_7.context,([] as any[]),compView_27);
    compView_27.create(this._TextInput_27_7.context,([] as any[]),(null as any));
    this._text_28 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._query_Label_22_0.reset([this._Label_24_3.context]);
    this._Item_22_4.context.contentLabel = this._query_Label_22_0.first;
    compView_22.create(this._Item_22_4.context,[
      ([] as any[]),
      ([] as any[]).concat([this._el_24]),
      ([] as any[]).concat([
        this._text_23,
        this._text_26,
        this._text_28
      ]
      ),
      ([] as any[]).concat([this._el_27]),
      ([] as any[])
    ]
    ,(null as any));
    this._text_29 = this.renderer.createText(this._el_12,'\n\n    ',(null as any));
    this._el_30 = this.renderer.createElement(this._el_12,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_30,'class','item item-block');
    this._appEl_30 = new import3.AppElement(30,12,this,this._el_30);
    var compView_30:any = import21.viewFactory_Item0(this.viewUtils,this.injector(30),this._appEl_30);
    this._Item_30_4 = new import21.Wrapper_Item(this.parentInjector.get(import35.Form),this.parentInjector.get(import27.Config),new import28.ElementRef(this._el_30),this.renderer,this.parentInjector.get(import36.ItemReorder,(null as any)));
    this._ItemContent_30_5 = new import21.Wrapper_ItemContent();
    this._query_Label_30_0 = new import22.QueryList<any>();
    this._query_Button_30_1 = new import22.QueryList<any>();
    this._query_Icon_30_2 = new import22.QueryList<any>();
    this._appEl_30.initComponent(this._Item_30_4.context,([] as any[]),compView_30);
    this._text_31 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_32 = this.renderer.createElement((null as any),'ion-label',(null as any));
    this.renderer.setElementAttribute(this._el_32,'stacked','');
    this._Label_32_3 = new import23.Wrapper_Label(this.parentInjector.get(import27.Config),new import28.ElementRef(this._el_32),this.renderer,(null as any),'',(null as any),(null as any));
    this._text_33 = this.renderer.createText(this._el_32,'Username',(null as any));
    this._text_34 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_35 = this.renderer.createElement((null as any),'ion-input',(null as any));
    this.renderer.setElementAttribute(this._el_35,'formControlName','username');
    this.renderer.setElementAttribute(this._el_35,'placeholder','Your username');
    this.renderer.setElementAttribute(this._el_35,'type','text');
    this._appEl_35 = new import3.AppElement(35,30,this,this._el_35);
    var compView_35:any = import25.viewFactory_TextInput0(this.viewUtils,this.injector(35),this._appEl_35);
    this._FormControlName_35_4 = new import24.Wrapper_FormControlName(this._ControlContainer_12_4,(null as any),(null as any),(null as any));
    this._NgControl_35_5 = this._FormControlName_35_4.context;
    this._NgControlStatus_35_6 = new import20.Wrapper_NgControlStatus(this._NgControl_35_5);
    this._TextInput_35_7 = new import25.Wrapper_TextInput(this.parentInjector.get(import27.Config),this.parentInjector.get(import35.Form),this._Item_30_4.context,this.parentInjector.get(import30.App),this.parentInjector.get(import37.Platform),new import28.ElementRef(this._el_35),this.renderer,this._Content_10_4.context,this.parentInjector.get(import8.NavController,(null as any)),this._NgControl_35_5);
    this._appEl_35.initComponent(this._TextInput_35_7.context,([] as any[]),compView_35);
    compView_35.create(this._TextInput_35_7.context,([] as any[]),(null as any));
    this._text_36 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._query_Label_30_0.reset([this._Label_32_3.context]);
    this._Item_30_4.context.contentLabel = this._query_Label_30_0.first;
    compView_30.create(this._Item_30_4.context,[
      ([] as any[]),
      ([] as any[]).concat([this._el_32]),
      ([] as any[]).concat([
        this._text_31,
        this._text_34,
        this._text_36
      ]
      ),
      ([] as any[]).concat([this._el_35]),
      ([] as any[])
    ]
    ,(null as any));
    this._text_37 = this.renderer.createText(this._el_12,'\n\n    ',(null as any));
    this._el_38 = this.renderer.createElement(this._el_12,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_38,'class','item item-block');
    this._appEl_38 = new import3.AppElement(38,12,this,this._el_38);
    var compView_38:any = import21.viewFactory_Item0(this.viewUtils,this.injector(38),this._appEl_38);
    this._Item_38_4 = new import21.Wrapper_Item(this.parentInjector.get(import35.Form),this.parentInjector.get(import27.Config),new import28.ElementRef(this._el_38),this.renderer,this.parentInjector.get(import36.ItemReorder,(null as any)));
    this._ItemContent_38_5 = new import21.Wrapper_ItemContent();
    this._query_Label_38_0 = new import22.QueryList<any>();
    this._query_Button_38_1 = new import22.QueryList<any>();
    this._query_Icon_38_2 = new import22.QueryList<any>();
    this._appEl_38.initComponent(this._Item_38_4.context,([] as any[]),compView_38);
    this._text_39 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_40 = this.renderer.createElement((null as any),'ion-label',(null as any));
    this.renderer.setElementAttribute(this._el_40,'stacked','');
    this._Label_40_3 = new import23.Wrapper_Label(this.parentInjector.get(import27.Config),new import28.ElementRef(this._el_40),this.renderer,(null as any),'',(null as any),(null as any));
    this._text_41 = this.renderer.createText(this._el_40,'Name',(null as any));
    this._text_42 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_43 = this.renderer.createElement((null as any),'ion-input',(null as any));
    this.renderer.setElementAttribute(this._el_43,'formControlName','name');
    this.renderer.setElementAttribute(this._el_43,'placeholder','Your name');
    this.renderer.setElementAttribute(this._el_43,'type','text');
    this._appEl_43 = new import3.AppElement(43,38,this,this._el_43);
    var compView_43:any = import25.viewFactory_TextInput0(this.viewUtils,this.injector(43),this._appEl_43);
    this._FormControlName_43_4 = new import24.Wrapper_FormControlName(this._ControlContainer_12_4,(null as any),(null as any),(null as any));
    this._NgControl_43_5 = this._FormControlName_43_4.context;
    this._NgControlStatus_43_6 = new import20.Wrapper_NgControlStatus(this._NgControl_43_5);
    this._TextInput_43_7 = new import25.Wrapper_TextInput(this.parentInjector.get(import27.Config),this.parentInjector.get(import35.Form),this._Item_38_4.context,this.parentInjector.get(import30.App),this.parentInjector.get(import37.Platform),new import28.ElementRef(this._el_43),this.renderer,this._Content_10_4.context,this.parentInjector.get(import8.NavController,(null as any)),this._NgControl_43_5);
    this._appEl_43.initComponent(this._TextInput_43_7.context,([] as any[]),compView_43);
    compView_43.create(this._TextInput_43_7.context,([] as any[]),(null as any));
    this._text_44 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._query_Label_38_0.reset([this._Label_40_3.context]);
    this._Item_38_4.context.contentLabel = this._query_Label_38_0.first;
    compView_38.create(this._Item_38_4.context,[
      ([] as any[]),
      ([] as any[]).concat([this._el_40]),
      ([] as any[]).concat([
        this._text_39,
        this._text_42,
        this._text_44
      ]
      ),
      ([] as any[]).concat([this._el_43]),
      ([] as any[])
    ]
    ,(null as any));
    this._text_45 = this.renderer.createText(this._el_12,'\n\n    ',(null as any));
    this._el_46 = this.renderer.createElement(this._el_12,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_46,'class','item item-block');
    this._appEl_46 = new import3.AppElement(46,12,this,this._el_46);
    var compView_46:any = import21.viewFactory_Item0(this.viewUtils,this.injector(46),this._appEl_46);
    this._Item_46_4 = new import21.Wrapper_Item(this.parentInjector.get(import35.Form),this.parentInjector.get(import27.Config),new import28.ElementRef(this._el_46),this.renderer,this.parentInjector.get(import36.ItemReorder,(null as any)));
    this._ItemContent_46_5 = new import21.Wrapper_ItemContent();
    this._query_Label_46_0 = new import22.QueryList<any>();
    this._query_Button_46_1 = new import22.QueryList<any>();
    this._query_Icon_46_2 = new import22.QueryList<any>();
    this._appEl_46.initComponent(this._Item_46_4.context,([] as any[]),compView_46);
    this._text_47 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_48 = this.renderer.createElement((null as any),'ion-label',(null as any));
    this.renderer.setElementAttribute(this._el_48,'stacked','');
    this._Label_48_3 = new import23.Wrapper_Label(this.parentInjector.get(import27.Config),new import28.ElementRef(this._el_48),this.renderer,(null as any),'',(null as any),(null as any));
    this._text_49 = this.renderer.createText(this._el_48,'Surname',(null as any));
    this._text_50 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_51 = this.renderer.createElement((null as any),'ion-input',(null as any));
    this.renderer.setElementAttribute(this._el_51,'formControlName','surname');
    this.renderer.setElementAttribute(this._el_51,'placeholder','Your surname');
    this.renderer.setElementAttribute(this._el_51,'type','text');
    this._appEl_51 = new import3.AppElement(51,46,this,this._el_51);
    var compView_51:any = import25.viewFactory_TextInput0(this.viewUtils,this.injector(51),this._appEl_51);
    this._FormControlName_51_4 = new import24.Wrapper_FormControlName(this._ControlContainer_12_4,(null as any),(null as any),(null as any));
    this._NgControl_51_5 = this._FormControlName_51_4.context;
    this._NgControlStatus_51_6 = new import20.Wrapper_NgControlStatus(this._NgControl_51_5);
    this._TextInput_51_7 = new import25.Wrapper_TextInput(this.parentInjector.get(import27.Config),this.parentInjector.get(import35.Form),this._Item_46_4.context,this.parentInjector.get(import30.App),this.parentInjector.get(import37.Platform),new import28.ElementRef(this._el_51),this.renderer,this._Content_10_4.context,this.parentInjector.get(import8.NavController,(null as any)),this._NgControl_51_5);
    this._appEl_51.initComponent(this._TextInput_51_7.context,([] as any[]),compView_51);
    compView_51.create(this._TextInput_51_7.context,([] as any[]),(null as any));
    this._text_52 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._query_Label_46_0.reset([this._Label_48_3.context]);
    this._Item_46_4.context.contentLabel = this._query_Label_46_0.first;
    compView_46.create(this._Item_46_4.context,[
      ([] as any[]),
      ([] as any[]).concat([this._el_48]),
      ([] as any[]).concat([
        this._text_47,
        this._text_50,
        this._text_52
      ]
      ),
      ([] as any[]).concat([this._el_51]),
      ([] as any[])
    ]
    ,(null as any));
    this._text_53 = this.renderer.createText(this._el_12,'\n\n    ',(null as any));
    this._el_54 = this.renderer.createElement(this._el_12,'button',(null as any));
    this.renderer.setElementAttribute(this._el_54,'block','');
    this.renderer.setElementAttribute(this._el_54,'ion-button','');
    this.renderer.setElementAttribute(this._el_54,'type','submit');
    this._appEl_54 = new import3.AppElement(54,12,this,this._el_54);
    var compView_54:any = import26.viewFactory_Button0(this.viewUtils,this.injector(54),this._appEl_54);
    this._Button_54_4 = new import26.Wrapper_Button((null as any),'',this.parentInjector.get(import27.Config),new import28.ElementRef(this._el_54),this.renderer);
    this._appEl_54.initComponent(this._Button_54_4.context,([] as any[]),compView_54);
    this._text_55 = this.renderer.createText((null as any),'\n      Create an Account\n    ',(null as any));
    compView_54.create(this._Button_54_4.context,[([] as any[]).concat([this._text_55])],(null as any));
    this._text_56 = this.renderer.createText(this._el_12,'\n  ',(null as any));
    this._text_57 = this.renderer.createText((null as any),'\n\n',(null as any));
    compView_10.create(this._Content_10_4.context,[
      ([] as any[]),
      ([] as any[]).concat([
        this._text_11,
        this._el_12,
        this._text_57
      ]
      ),
      ([] as any[])
    ]
    ,(null as any));
    this._text_58 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this._expr_1 = import7.UNINITIALIZED;
    this._expr_2 = import7.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_12,'submit',this.eventHandler(this._handle_submit_12_0.bind(this)));
    var disposable_1:Function = this.renderer.listen(this._el_12,'reset',this.eventHandler(this._handle_reset_12_1.bind(this)));
    this._expr_7 = import7.UNINITIALIZED;
    this._expr_8 = import7.UNINITIALIZED;
    this._expr_9 = import7.UNINITIALIZED;
    this._expr_10 = import7.UNINITIALIZED;
    this._expr_11 = import7.UNINITIALIZED;
    this._expr_12 = import7.UNINITIALIZED;
    this._expr_14 = import7.UNINITIALIZED;
    this._expr_15 = import7.UNINITIALIZED;
    this._expr_16 = import7.UNINITIALIZED;
    this._expr_17 = import7.UNINITIALIZED;
    this._expr_18 = import7.UNINITIALIZED;
    this._expr_19 = import7.UNINITIALIZED;
    this._expr_23 = import7.UNINITIALIZED;
    this._expr_24 = import7.UNINITIALIZED;
    this._expr_25 = import7.UNINITIALIZED;
    this._expr_26 = import7.UNINITIALIZED;
    this._expr_27 = import7.UNINITIALIZED;
    this._expr_28 = import7.UNINITIALIZED;
    this._expr_32 = import7.UNINITIALIZED;
    this._expr_33 = import7.UNINITIALIZED;
    this._expr_34 = import7.UNINITIALIZED;
    this._expr_35 = import7.UNINITIALIZED;
    this._expr_36 = import7.UNINITIALIZED;
    this._expr_37 = import7.UNINITIALIZED;
    this._expr_41 = import7.UNINITIALIZED;
    this._expr_42 = import7.UNINITIALIZED;
    this._expr_43 = import7.UNINITIALIZED;
    this._expr_44 = import7.UNINITIALIZED;
    this._expr_45 = import7.UNINITIALIZED;
    this._expr_46 = import7.UNINITIALIZED;
    this._expr_50 = import7.UNINITIALIZED;
    this._expr_51 = import7.UNINITIALIZED;
    this._expr_52 = import7.UNINITIALIZED;
    this._expr_53 = import7.UNINITIALIZED;
    this._expr_54 = import7.UNINITIALIZED;
    this._expr_55 = import7.UNINITIALIZED;
    this.init(([] as any[]),[
      this._text_0,
      this._el_1,
      this._text_2,
      this._el_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._text_7,
      this._text_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._el_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._el_16,
      this._text_17,
      this._text_18,
      this._el_19,
      this._text_20,
      this._text_21,
      this._el_22,
      this._text_23,
      this._el_24,
      this._text_25,
      this._text_26,
      this._el_27,
      this._text_28,
      this._text_29,
      this._el_30,
      this._text_31,
      this._el_32,
      this._text_33,
      this._text_34,
      this._el_35,
      this._text_36,
      this._text_37,
      this._el_38,
      this._text_39,
      this._el_40,
      this._text_41,
      this._text_42,
      this._el_43,
      this._text_44,
      this._text_45,
      this._el_46,
      this._text_47,
      this._el_48,
      this._text_49,
      this._text_50,
      this._el_51,
      this._text_52,
      this._text_53,
      this._el_54,
      this._text_55,
      this._text_56,
      this._text_57,
      this._text_58
    ]
    ,[
      disposable_0,
      disposable_1
    ]
    ,([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import38.ToolbarTitle) && ((5 <= requestNodeIndex) && (requestNodeIndex <= 6)))) { return this._ToolbarTitle_5_4.context; }
    if (((token === import39.Navbar) && ((3 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._Navbar_3_4.context; }
    if (((token === import31.Header) && ((1 <= requestNodeIndex) && (requestNodeIndex <= 8)))) { return this._Header_1_3.context; }
    if (((token === import40.Label) && ((16 <= requestNodeIndex) && (requestNodeIndex <= 17)))) { return this._Label_16_3.context; }
    if (((token === import41.FormControlName) && (19 === requestNodeIndex))) { return this._FormControlName_19_4.context; }
    if (((token === import42.NgControl) && (19 === requestNodeIndex))) { return this._NgControl_19_5; }
    if (((token === import43.NgControlStatus) && (19 === requestNodeIndex))) { return this._NgControlStatus_19_6.context; }
    if (((token === import44.TextInput) && (19 === requestNodeIndex))) { return this._TextInput_19_7.context; }
    if (((token === import45.Item) && ((14 <= requestNodeIndex) && (requestNodeIndex <= 20)))) { return this._Item_14_4.context; }
    if (((token === import45.ItemContent) && ((14 <= requestNodeIndex) && (requestNodeIndex <= 20)))) { return this._ItemContent_14_5.context; }
    if (((token === import40.Label) && ((24 <= requestNodeIndex) && (requestNodeIndex <= 25)))) { return this._Label_24_3.context; }
    if (((token === import41.FormControlName) && (27 === requestNodeIndex))) { return this._FormControlName_27_4.context; }
    if (((token === import42.NgControl) && (27 === requestNodeIndex))) { return this._NgControl_27_5; }
    if (((token === import43.NgControlStatus) && (27 === requestNodeIndex))) { return this._NgControlStatus_27_6.context; }
    if (((token === import44.TextInput) && (27 === requestNodeIndex))) { return this._TextInput_27_7.context; }
    if (((token === import45.Item) && ((22 <= requestNodeIndex) && (requestNodeIndex <= 28)))) { return this._Item_22_4.context; }
    if (((token === import45.ItemContent) && ((22 <= requestNodeIndex) && (requestNodeIndex <= 28)))) { return this._ItemContent_22_5.context; }
    if (((token === import40.Label) && ((32 <= requestNodeIndex) && (requestNodeIndex <= 33)))) { return this._Label_32_3.context; }
    if (((token === import41.FormControlName) && (35 === requestNodeIndex))) { return this._FormControlName_35_4.context; }
    if (((token === import42.NgControl) && (35 === requestNodeIndex))) { return this._NgControl_35_5; }
    if (((token === import43.NgControlStatus) && (35 === requestNodeIndex))) { return this._NgControlStatus_35_6.context; }
    if (((token === import44.TextInput) && (35 === requestNodeIndex))) { return this._TextInput_35_7.context; }
    if (((token === import45.Item) && ((30 <= requestNodeIndex) && (requestNodeIndex <= 36)))) { return this._Item_30_4.context; }
    if (((token === import45.ItemContent) && ((30 <= requestNodeIndex) && (requestNodeIndex <= 36)))) { return this._ItemContent_30_5.context; }
    if (((token === import40.Label) && ((40 <= requestNodeIndex) && (requestNodeIndex <= 41)))) { return this._Label_40_3.context; }
    if (((token === import41.FormControlName) && (43 === requestNodeIndex))) { return this._FormControlName_43_4.context; }
    if (((token === import42.NgControl) && (43 === requestNodeIndex))) { return this._NgControl_43_5; }
    if (((token === import43.NgControlStatus) && (43 === requestNodeIndex))) { return this._NgControlStatus_43_6.context; }
    if (((token === import44.TextInput) && (43 === requestNodeIndex))) { return this._TextInput_43_7.context; }
    if (((token === import45.Item) && ((38 <= requestNodeIndex) && (requestNodeIndex <= 44)))) { return this._Item_38_4.context; }
    if (((token === import45.ItemContent) && ((38 <= requestNodeIndex) && (requestNodeIndex <= 44)))) { return this._ItemContent_38_5.context; }
    if (((token === import40.Label) && ((48 <= requestNodeIndex) && (requestNodeIndex <= 49)))) { return this._Label_48_3.context; }
    if (((token === import41.FormControlName) && (51 === requestNodeIndex))) { return this._FormControlName_51_4.context; }
    if (((token === import42.NgControl) && (51 === requestNodeIndex))) { return this._NgControl_51_5; }
    if (((token === import43.NgControlStatus) && (51 === requestNodeIndex))) { return this._NgControlStatus_51_6.context; }
    if (((token === import44.TextInput) && (51 === requestNodeIndex))) { return this._TextInput_51_7.context; }
    if (((token === import45.Item) && ((46 <= requestNodeIndex) && (requestNodeIndex <= 52)))) { return this._Item_46_4.context; }
    if (((token === import45.ItemContent) && ((46 <= requestNodeIndex) && (requestNodeIndex <= 52)))) { return this._ItemContent_46_5.context; }
    if (((token === import46.Button) && ((54 <= requestNodeIndex) && (requestNodeIndex <= 55)))) { return this._Button_54_4.context; }
    if (((token === import47.FormGroupDirective) && ((12 <= requestNodeIndex) && (requestNodeIndex <= 56)))) { return this._FormGroupDirective_12_3.context; }
    if (((token === import48.ControlContainer) && ((12 <= requestNodeIndex) && (requestNodeIndex <= 56)))) { return this._ControlContainer_12_4; }
    if (((token === import43.NgControlStatusGroup) && ((12 <= requestNodeIndex) && (requestNodeIndex <= 56)))) { return this._NgControlStatusGroup_12_5.context; }
    if (((token === import49.Content) && ((10 <= requestNodeIndex) && (requestNodeIndex <= 57)))) { return this._Content_10_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._Header_1_3.detectChangesInternal(this,this._el_1,throwOnChange);
    this._Navbar_3_4.detectChangesInternal(this,this._el_3,throwOnChange);
    if (this._ToolbarTitle_5_4.detectChangesInternal(this,this._el_5,throwOnChange)) { this._appEl_5.componentView.markAsCheckOnce(); }
    if (this._Content_10_4.detectChangesInternal(this,this._el_10,throwOnChange)) { this._appEl_10.componentView.markAsCheckOnce(); }
    const currVal_6:any = this.context.signupForm;
    this._FormGroupDirective_12_3.check_form(currVal_6,throwOnChange,false);
    this._FormGroupDirective_12_3.detectChangesInternal(this,this._el_12,throwOnChange);
    this._NgControlStatusGroup_12_5.detectChangesInternal(this,this._el_12,throwOnChange);
    if (this._Item_14_4.detectChangesInternal(this,this._el_14,throwOnChange)) { this._appEl_14.componentView.markAsCheckOnce(); }
    this._ItemContent_14_5.detectChangesInternal(this,this._el_14,throwOnChange);
    this._Label_16_3.detectChangesInternal(this,this._el_16,throwOnChange);
    const currVal_13:any = 'email';
    this._FormControlName_19_4.check_name(currVal_13,throwOnChange,false);
    this._FormControlName_19_4.detectChangesInternal(this,this._el_19,throwOnChange);
    this._NgControlStatus_19_6.detectChangesInternal(this,this._el_19,throwOnChange);
    const currVal_20:any = 'Your email address';
    this._TextInput_19_7.check_placeholder(currVal_20,throwOnChange,false);
    const currVal_21:any = 'email';
    this._TextInput_19_7.check_type(currVal_21,throwOnChange,false);
    this._TextInput_19_7.detectChangesInternal(this,this._el_19,throwOnChange);
    if (this._Item_22_4.detectChangesInternal(this,this._el_22,throwOnChange)) { this._appEl_22.componentView.markAsCheckOnce(); }
    this._ItemContent_22_5.detectChangesInternal(this,this._el_22,throwOnChange);
    this._Label_24_3.detectChangesInternal(this,this._el_24,throwOnChange);
    const currVal_22:any = 'password';
    this._FormControlName_27_4.check_name(currVal_22,throwOnChange,false);
    this._FormControlName_27_4.detectChangesInternal(this,this._el_27,throwOnChange);
    this._NgControlStatus_27_6.detectChangesInternal(this,this._el_27,throwOnChange);
    const currVal_29:any = 'Your password';
    this._TextInput_27_7.check_placeholder(currVal_29,throwOnChange,false);
    const currVal_30:any = 'password';
    this._TextInput_27_7.check_type(currVal_30,throwOnChange,false);
    this._TextInput_27_7.detectChangesInternal(this,this._el_27,throwOnChange);
    if (this._Item_30_4.detectChangesInternal(this,this._el_30,throwOnChange)) { this._appEl_30.componentView.markAsCheckOnce(); }
    this._ItemContent_30_5.detectChangesInternal(this,this._el_30,throwOnChange);
    this._Label_32_3.detectChangesInternal(this,this._el_32,throwOnChange);
    const currVal_31:any = 'username';
    this._FormControlName_35_4.check_name(currVal_31,throwOnChange,false);
    this._FormControlName_35_4.detectChangesInternal(this,this._el_35,throwOnChange);
    this._NgControlStatus_35_6.detectChangesInternal(this,this._el_35,throwOnChange);
    const currVal_38:any = 'Your username';
    this._TextInput_35_7.check_placeholder(currVal_38,throwOnChange,false);
    const currVal_39:any = 'text';
    this._TextInput_35_7.check_type(currVal_39,throwOnChange,false);
    this._TextInput_35_7.detectChangesInternal(this,this._el_35,throwOnChange);
    if (this._Item_38_4.detectChangesInternal(this,this._el_38,throwOnChange)) { this._appEl_38.componentView.markAsCheckOnce(); }
    this._ItemContent_38_5.detectChangesInternal(this,this._el_38,throwOnChange);
    this._Label_40_3.detectChangesInternal(this,this._el_40,throwOnChange);
    const currVal_40:any = 'name';
    this._FormControlName_43_4.check_name(currVal_40,throwOnChange,false);
    this._FormControlName_43_4.detectChangesInternal(this,this._el_43,throwOnChange);
    this._NgControlStatus_43_6.detectChangesInternal(this,this._el_43,throwOnChange);
    const currVal_47:any = 'Your name';
    this._TextInput_43_7.check_placeholder(currVal_47,throwOnChange,false);
    const currVal_48:any = 'text';
    this._TextInput_43_7.check_type(currVal_48,throwOnChange,false);
    this._TextInput_43_7.detectChangesInternal(this,this._el_43,throwOnChange);
    if (this._Item_46_4.detectChangesInternal(this,this._el_46,throwOnChange)) { this._appEl_46.componentView.markAsCheckOnce(); }
    this._ItemContent_46_5.detectChangesInternal(this,this._el_46,throwOnChange);
    this._Label_48_3.detectChangesInternal(this,this._el_48,throwOnChange);
    const currVal_49:any = 'surname';
    this._FormControlName_51_4.check_name(currVal_49,throwOnChange,false);
    this._FormControlName_51_4.detectChangesInternal(this,this._el_51,throwOnChange);
    this._NgControlStatus_51_6.detectChangesInternal(this,this._el_51,throwOnChange);
    const currVal_56:any = 'Your surname';
    this._TextInput_51_7.check_placeholder(currVal_56,throwOnChange,false);
    const currVal_57:any = 'text';
    this._TextInput_51_7.check_type(currVal_57,throwOnChange,false);
    this._TextInput_51_7.detectChangesInternal(this,this._el_51,throwOnChange);
    const currVal_58:any = '';
    this._Button_54_4.check_block(currVal_58,throwOnChange,false);
    if (this._Button_54_4.detectChangesInternal(this,this._el_54,throwOnChange)) { this._appEl_54.componentView.markAsCheckOnce(); }
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_14_1.dirty) {
        this._query_Button_14_1.reset(([] as any[]));
        this._Item_14_4.context._buttons = this._query_Button_14_1;
        this._query_Button_14_1.notifyOnChanges();
      }
      if (this._query_Icon_14_2.dirty) {
        this._query_Icon_14_2.reset(([] as any[]));
        this._Item_14_4.context._icons = this._query_Icon_14_2;
        this._query_Icon_14_2.notifyOnChanges();
      }
      if (this._query_Button_22_1.dirty) {
        this._query_Button_22_1.reset(([] as any[]));
        this._Item_22_4.context._buttons = this._query_Button_22_1;
        this._query_Button_22_1.notifyOnChanges();
      }
      if (this._query_Icon_22_2.dirty) {
        this._query_Icon_22_2.reset(([] as any[]));
        this._Item_22_4.context._icons = this._query_Icon_22_2;
        this._query_Icon_22_2.notifyOnChanges();
      }
      if (this._query_Button_30_1.dirty) {
        this._query_Button_30_1.reset(([] as any[]));
        this._Item_30_4.context._buttons = this._query_Button_30_1;
        this._query_Button_30_1.notifyOnChanges();
      }
      if (this._query_Icon_30_2.dirty) {
        this._query_Icon_30_2.reset(([] as any[]));
        this._Item_30_4.context._icons = this._query_Icon_30_2;
        this._query_Icon_30_2.notifyOnChanges();
      }
      if (this._query_Button_38_1.dirty) {
        this._query_Button_38_1.reset(([] as any[]));
        this._Item_38_4.context._buttons = this._query_Button_38_1;
        this._query_Button_38_1.notifyOnChanges();
      }
      if (this._query_Icon_38_2.dirty) {
        this._query_Icon_38_2.reset(([] as any[]));
        this._Item_38_4.context._icons = this._query_Icon_38_2;
        this._query_Icon_38_2.notifyOnChanges();
      }
      if (this._query_Button_46_1.dirty) {
        this._query_Button_46_1.reset(([] as any[]));
        this._Item_46_4.context._buttons = this._query_Button_46_1;
        this._query_Button_46_1.notifyOnChanges();
      }
      if (this._query_Icon_46_2.dirty) {
        this._query_Icon_46_2.reset(([] as any[]));
        this._Item_46_4.context._icons = this._query_Icon_46_2;
        this._query_Icon_46_2.notifyOnChanges();
      }
      this._TextInput_19_7.context.ngAfterContentChecked();
      if ((this.numberOfChecks === 0)) { this._Item_14_4.context.ngAfterContentInit(); }
      this._TextInput_27_7.context.ngAfterContentChecked();
      if ((this.numberOfChecks === 0)) { this._Item_22_4.context.ngAfterContentInit(); }
      this._TextInput_35_7.context.ngAfterContentChecked();
      if ((this.numberOfChecks === 0)) { this._Item_30_4.context.ngAfterContentInit(); }
      this._TextInput_43_7.context.ngAfterContentChecked();
      if ((this.numberOfChecks === 0)) { this._Item_38_4.context.ngAfterContentInit(); }
      this._TextInput_51_7.context.ngAfterContentChecked();
      if ((this.numberOfChecks === 0)) { this._Item_46_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Button_54_4.context.ngAfterContentInit(); }
    }
    const currVal_0:any = this._Navbar_3_4.context._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setElementProperty(this._el_3,'hidden',currVal_0);
      this._expr_0 = currVal_0;
    }
    const currVal_1:any = this._Navbar_3_4.context._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementClass(this._el_3,'statusbar-padding',currVal_1);
      this._expr_1 = currVal_1;
    }
    const currVal_2:any = this._Content_10_4.context._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setElementClass(this._el_10,'statusbar-padding',currVal_2);
      this._expr_2 = currVal_2;
    }
    const currVal_7:any = this._NgControlStatusGroup_12_5.context.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this.renderer.setElementClass(this._el_12,'ng-untouched',currVal_7);
      this._expr_7 = currVal_7;
    }
    const currVal_8:any = this._NgControlStatusGroup_12_5.context.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this.renderer.setElementClass(this._el_12,'ng-touched',currVal_8);
      this._expr_8 = currVal_8;
    }
    const currVal_9:any = this._NgControlStatusGroup_12_5.context.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_9,currVal_9)) {
      this.renderer.setElementClass(this._el_12,'ng-pristine',currVal_9);
      this._expr_9 = currVal_9;
    }
    const currVal_10:any = this._NgControlStatusGroup_12_5.context.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_10,currVal_10)) {
      this.renderer.setElementClass(this._el_12,'ng-dirty',currVal_10);
      this._expr_10 = currVal_10;
    }
    const currVal_11:any = this._NgControlStatusGroup_12_5.context.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_11,currVal_11)) {
      this.renderer.setElementClass(this._el_12,'ng-valid',currVal_11);
      this._expr_11 = currVal_11;
    }
    const currVal_12:any = this._NgControlStatusGroup_12_5.context.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_12,currVal_12)) {
      this.renderer.setElementClass(this._el_12,'ng-invalid',currVal_12);
      this._expr_12 = currVal_12;
    }
    const currVal_14:any = this._NgControlStatus_19_6.context.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_14,currVal_14)) {
      this.renderer.setElementClass(this._el_19,'ng-untouched',currVal_14);
      this._expr_14 = currVal_14;
    }
    const currVal_15:any = this._NgControlStatus_19_6.context.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_15,currVal_15)) {
      this.renderer.setElementClass(this._el_19,'ng-touched',currVal_15);
      this._expr_15 = currVal_15;
    }
    const currVal_16:any = this._NgControlStatus_19_6.context.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_16,currVal_16)) {
      this.renderer.setElementClass(this._el_19,'ng-pristine',currVal_16);
      this._expr_16 = currVal_16;
    }
    const currVal_17:any = this._NgControlStatus_19_6.context.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_17,currVal_17)) {
      this.renderer.setElementClass(this._el_19,'ng-dirty',currVal_17);
      this._expr_17 = currVal_17;
    }
    const currVal_18:any = this._NgControlStatus_19_6.context.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_18,currVal_18)) {
      this.renderer.setElementClass(this._el_19,'ng-valid',currVal_18);
      this._expr_18 = currVal_18;
    }
    const currVal_19:any = this._NgControlStatus_19_6.context.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_19,currVal_19)) {
      this.renderer.setElementClass(this._el_19,'ng-invalid',currVal_19);
      this._expr_19 = currVal_19;
    }
    const currVal_23:any = this._NgControlStatus_27_6.context.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_23,currVal_23)) {
      this.renderer.setElementClass(this._el_27,'ng-untouched',currVal_23);
      this._expr_23 = currVal_23;
    }
    const currVal_24:any = this._NgControlStatus_27_6.context.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_24,currVal_24)) {
      this.renderer.setElementClass(this._el_27,'ng-touched',currVal_24);
      this._expr_24 = currVal_24;
    }
    const currVal_25:any = this._NgControlStatus_27_6.context.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_25,currVal_25)) {
      this.renderer.setElementClass(this._el_27,'ng-pristine',currVal_25);
      this._expr_25 = currVal_25;
    }
    const currVal_26:any = this._NgControlStatus_27_6.context.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_26,currVal_26)) {
      this.renderer.setElementClass(this._el_27,'ng-dirty',currVal_26);
      this._expr_26 = currVal_26;
    }
    const currVal_27:any = this._NgControlStatus_27_6.context.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_27,currVal_27)) {
      this.renderer.setElementClass(this._el_27,'ng-valid',currVal_27);
      this._expr_27 = currVal_27;
    }
    const currVal_28:any = this._NgControlStatus_27_6.context.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_28,currVal_28)) {
      this.renderer.setElementClass(this._el_27,'ng-invalid',currVal_28);
      this._expr_28 = currVal_28;
    }
    const currVal_32:any = this._NgControlStatus_35_6.context.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_32,currVal_32)) {
      this.renderer.setElementClass(this._el_35,'ng-untouched',currVal_32);
      this._expr_32 = currVal_32;
    }
    const currVal_33:any = this._NgControlStatus_35_6.context.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_33,currVal_33)) {
      this.renderer.setElementClass(this._el_35,'ng-touched',currVal_33);
      this._expr_33 = currVal_33;
    }
    const currVal_34:any = this._NgControlStatus_35_6.context.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_34,currVal_34)) {
      this.renderer.setElementClass(this._el_35,'ng-pristine',currVal_34);
      this._expr_34 = currVal_34;
    }
    const currVal_35:any = this._NgControlStatus_35_6.context.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_35,currVal_35)) {
      this.renderer.setElementClass(this._el_35,'ng-dirty',currVal_35);
      this._expr_35 = currVal_35;
    }
    const currVal_36:any = this._NgControlStatus_35_6.context.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_36,currVal_36)) {
      this.renderer.setElementClass(this._el_35,'ng-valid',currVal_36);
      this._expr_36 = currVal_36;
    }
    const currVal_37:any = this._NgControlStatus_35_6.context.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_37,currVal_37)) {
      this.renderer.setElementClass(this._el_35,'ng-invalid',currVal_37);
      this._expr_37 = currVal_37;
    }
    const currVal_41:any = this._NgControlStatus_43_6.context.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_41,currVal_41)) {
      this.renderer.setElementClass(this._el_43,'ng-untouched',currVal_41);
      this._expr_41 = currVal_41;
    }
    const currVal_42:any = this._NgControlStatus_43_6.context.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_42,currVal_42)) {
      this.renderer.setElementClass(this._el_43,'ng-touched',currVal_42);
      this._expr_42 = currVal_42;
    }
    const currVal_43:any = this._NgControlStatus_43_6.context.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_43,currVal_43)) {
      this.renderer.setElementClass(this._el_43,'ng-pristine',currVal_43);
      this._expr_43 = currVal_43;
    }
    const currVal_44:any = this._NgControlStatus_43_6.context.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_44,currVal_44)) {
      this.renderer.setElementClass(this._el_43,'ng-dirty',currVal_44);
      this._expr_44 = currVal_44;
    }
    const currVal_45:any = this._NgControlStatus_43_6.context.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_45,currVal_45)) {
      this.renderer.setElementClass(this._el_43,'ng-valid',currVal_45);
      this._expr_45 = currVal_45;
    }
    const currVal_46:any = this._NgControlStatus_43_6.context.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_46,currVal_46)) {
      this.renderer.setElementClass(this._el_43,'ng-invalid',currVal_46);
      this._expr_46 = currVal_46;
    }
    const currVal_50:any = this._NgControlStatus_51_6.context.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_50,currVal_50)) {
      this.renderer.setElementClass(this._el_51,'ng-untouched',currVal_50);
      this._expr_50 = currVal_50;
    }
    const currVal_51:any = this._NgControlStatus_51_6.context.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_51,currVal_51)) {
      this.renderer.setElementClass(this._el_51,'ng-touched',currVal_51);
      this._expr_51 = currVal_51;
    }
    const currVal_52:any = this._NgControlStatus_51_6.context.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_52,currVal_52)) {
      this.renderer.setElementClass(this._el_51,'ng-pristine',currVal_52);
      this._expr_52 = currVal_52;
    }
    const currVal_53:any = this._NgControlStatus_51_6.context.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_53,currVal_53)) {
      this.renderer.setElementClass(this._el_51,'ng-dirty',currVal_53);
      this._expr_53 = currVal_53;
    }
    const currVal_54:any = this._NgControlStatus_51_6.context.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_54,currVal_54)) {
      this.renderer.setElementClass(this._el_51,'ng-valid',currVal_54);
      this._expr_54 = currVal_54;
    }
    const currVal_55:any = this._NgControlStatus_51_6.context.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_55,currVal_55)) {
      this.renderer.setElementClass(this._el_51,'ng-invalid',currVal_55);
      this._expr_55 = currVal_55;
    }
    this.detectViewChildrenChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._Navbar_3_4.context.ngAfterViewInit(); } }
  }
  destroyInternal():void {
    this._FormControlName_19_4.context.ngOnDestroy();
    this._TextInput_19_7.context.ngOnDestroy();
    this._FormControlName_27_4.context.ngOnDestroy();
    this._TextInput_27_7.context.ngOnDestroy();
    this._FormControlName_35_4.context.ngOnDestroy();
    this._TextInput_35_7.context.ngOnDestroy();
    this._FormControlName_43_4.context.ngOnDestroy();
    this._TextInput_43_7.context.ngOnDestroy();
    this._FormControlName_51_4.context.ngOnDestroy();
    this._TextInput_51_7.context.ngOnDestroy();
    this._Content_10_4.context.ngOnDestroy();
  }
  private _handle_submit_12_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.signupUser()) !== false);
    const pd_1:any = ((<any>this._FormGroupDirective_12_3.context.onSubmit($event)) !== false);
    return ((true && pd_0) && pd_1);
  }
  private _handle_reset_12_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._FormGroupDirective_12_3.context.onReset()) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_SignupPage0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<import0.SignupPage> {
  if ((renderType_SignupPage === (null as any))) { (renderType_SignupPage = viewUtils.createRenderComponentType('',0,import13.ViewEncapsulation.None,styles_SignupPage,{})); }
  return new _View_SignupPage0(viewUtils,parentInjector,declarationEl);
}