/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from './friend-details';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/element';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from 'ionic-angular/navigation/nav-controller';
import * as import9 from 'ionic-angular/navigation/nav-params';
import * as import10 from '@angular/core/src/metadata/view';
import * as import11 from '@angular/core/src/linker/component_factory';
import * as import12 from '../../node_modules/ionic-angular/components/toolbar/toolbar.ngfactory';
import * as import13 from '../../node_modules/ionic-angular/components/navbar/navbar.ngfactory';
import * as import14 from '../../node_modules/ionic-angular/components/toolbar/toolbar-title.ngfactory';
import * as import15 from '../../node_modules/ionic-angular/components/content/content.ngfactory';
import * as import16 from '../../node_modules/ionic-angular/components/segment/segment.ngfactory';
import * as import17 from '@angular/core/src/linker/query_list';
import * as import18 from '../../node_modules/ionic-angular/components/card/card.ngfactory';
import * as import19 from '../../node_modules/ionic-angular/components/item/item.ngfactory';
import * as import20 from '../../node_modules/ionic-angular/components/icon/icon.ngfactory';
import * as import21 from '../../node_modules/ionic-angular/components/badge/badge.ngfactory';
import * as import22 from 'ionic-angular/config/config';
import * as import23 from '@angular/core/src/linker/element_ref';
import * as import24 from 'ionic-angular/navigation/view-controller';
import * as import25 from 'ionic-angular/components/app/app';
import * as import26 from 'ionic-angular/components/toolbar/toolbar';
import * as import27 from 'ionic-angular/util/keyboard';
import * as import28 from '@angular/core/src/zone/ng_zone';
import * as import29 from 'ionic-angular/components/tabs/tabs';
import * as import30 from '@angular/forms/src/directives/ng_control';
import * as import31 from 'ionic-angular/util/form';
import * as import32 from 'ionic-angular/components/item/item-reorder';
import * as import33 from 'ionic-angular/components/toolbar/toolbar-title';
import * as import34 from 'ionic-angular/components/navbar/navbar';
import * as import35 from 'ionic-angular/components/segment/segment';
import * as import36 from 'ionic-angular/components/card/card';
import * as import37 from 'ionic-angular/components/icon/icon';
import * as import38 from 'ionic-angular/components/badge/badge';
import * as import39 from 'ionic-angular/components/item/item';
import * as import40 from 'ionic-angular/components/content/content';
import * as import41 from '@angular/core/src/security';
export class Wrapper_FriendDetails {
  context:import0.FriendDetails;
  changed:boolean;
  constructor(p0:any,p1:any) {
    this.changed = false;
    this.context = new import0.FriendDetails(p0,p1);
  }
  detectChangesInternal(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this.changed;
    this.changed = false;
    return changed;
  }
}
var renderType_FriendDetails_Host:import2.RenderComponentType = (null as any);
class _View_FriendDetails_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _FriendDetails_0_4:Wrapper_FriendDetails;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_FriendDetails_Host0,renderType_FriendDetails_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.selectOrCreateHostElement('page-friend-details',rootSelector,(null as any));
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_FriendDetails0(this.viewUtils,this.injector(0),this._appEl_0);
    this._FriendDetails_0_4 = new Wrapper_FriendDetails(this.parentInjector.get(import8.NavController),this.parentInjector.get(import9.NavParams));
    this._appEl_0.initComponent(this._FriendDetails_0_4.context,([] as any[]),compView_0);
    compView_0.create(this._FriendDetails_0_4.context,this.projectableNodes,(null as any));
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.FriendDetails) && (0 === requestNodeIndex))) { return this._FriendDetails_0_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._FriendDetails_0_4.detectChangesInternal(this,this._el_0,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_FriendDetails_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  if ((renderType_FriendDetails_Host === (null as any))) { (renderType_FriendDetails_Host = viewUtils.createRenderComponentType('',0,import10.ViewEncapsulation.None,([] as any[]),{})); }
  return new _View_FriendDetails_Host0(viewUtils,parentInjector,declarationEl);
}
export const FriendDetailsNgFactory:import11.ComponentFactory<import0.FriendDetails> = new import11.ComponentFactory<import0.FriendDetails>('page-friend-details',viewFactory_FriendDetails_Host0,import0.FriendDetails);
const styles_FriendDetails:any[] = ([] as any[]);
var renderType_FriendDetails:import2.RenderComponentType = (null as any);
class _View_FriendDetails0 extends import1.AppView<import0.FriendDetails> {
  _el_0:any;
  _Header_0_3:import12.Wrapper_Header;
  _text_1:any;
  _el_2:any;
  /*private*/ _appEl_2:import3.AppElement;
  _Navbar_2_4:import13.Wrapper_Navbar;
  _text_3:any;
  _el_4:any;
  /*private*/ _appEl_4:import3.AppElement;
  _ToolbarTitle_4_4:import14.Wrapper_ToolbarTitle;
  _text_5:any;
  _text_6:any;
  _text_7:any;
  _text_8:any;
  _el_9:any;
  /*private*/ _appEl_9:import3.AppElement;
  _Content_9_4:import15.Wrapper_Content;
  _text_10:any;
  _el_11:any;
  _text_12:any;
  _el_13:any;
  _Segment_13_3:import16.Wrapper_Segment;
  _query_SegmentButton_13_0:import17.QueryList<any>;
  _text_14:any;
  _el_15:any;
  /*private*/ _appEl_15:import3.AppElement;
  _SegmentButton_15_4:import16.Wrapper_SegmentButton;
  _text_16:any;
  _text_17:any;
  _el_18:any;
  /*private*/ _appEl_18:import3.AppElement;
  _SegmentButton_18_4:import16.Wrapper_SegmentButton;
  _text_19:any;
  _text_20:any;
  _el_21:any;
  /*private*/ _appEl_21:import3.AppElement;
  _SegmentButton_21_4:import16.Wrapper_SegmentButton;
  _text_22:any;
  _text_23:any;
  _text_24:any;
  _text_25:any;
  _el_26:any;
  _Card_26_3:import18.Wrapper_Card;
  _text_27:any;
  _el_28:any;
  _CardHeader_28_3:import18.Wrapper_CardHeader;
  _text_29:any;
  _text_30:any;
  _el_31:any;
  _CardContent_31_3:import18.Wrapper_CardContent;
  _text_32:any;
  _el_33:any;
  _text_34:any;
  _el_35:any;
  _text_36:any;
  _text_37:any;
  _el_38:any;
  /*private*/ _appEl_38:import3.AppElement;
  _Item_38_4:import19.Wrapper_Item;
  _ItemContent_38_5:import19.Wrapper_ItemContent;
  _query_Label_38_0:import17.QueryList<any>;
  _query_Button_38_1:import17.QueryList<any>;
  _query_Icon_38_2:import17.QueryList<any>;
  _text_39:any;
  _el_40:any;
  _Icon_40_3:import20.Wrapper_Icon;
  _text_41:any;
  _el_42:any;
  _Badge_42_3:import21.Wrapper_Badge;
  _text_43:any;
  _text_44:any;
  _text_45:any;
  _text_46:any;
  _text_47:any;
  _text_48:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_9:any;
  /*private*/ _expr_10:any;
  /*private*/ _expr_11:any;
  /*private*/ _expr_13:any;
  /*private*/ _expr_14:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_FriendDetails0,renderType_FriendDetails,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'ion-header',(null as any));
    this._Header_0_3 = new import12.Wrapper_Header(this.parentInjector.get(import22.Config),new import23.ElementRef(this._el_0),this.renderer,this.parentInjector.get(import24.ViewController,(null as any)));
    this._text_1 = this.renderer.createText(this._el_0,'\n\n  ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'ion-navbar',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','toolbar');
    this._appEl_2 = new import3.AppElement(2,0,this,this._el_2);
    var compView_2:any = import13.viewFactory_Navbar0(this.viewUtils,this.injector(2),this._appEl_2);
    this._Navbar_2_4 = new import13.Wrapper_Navbar(this.parentInjector.get(import25.App),this.parentInjector.get(import24.ViewController,(null as any)),this.parentInjector.get(import8.NavController,(null as any)),this.parentInjector.get(import22.Config),new import23.ElementRef(this._el_2),this.renderer);
    this._appEl_2.initComponent(this._Navbar_2_4.context,([] as any[]),compView_2);
    this._text_3 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_4 = this.renderer.createElement((null as any),'ion-title',(null as any));
    this._appEl_4 = new import3.AppElement(4,2,this,this._el_4);
    var compView_4:any = import14.viewFactory_ToolbarTitle0(this.viewUtils,this.injector(4),this._appEl_4);
    this._ToolbarTitle_4_4 = new import14.Wrapper_ToolbarTitle(this.parentInjector.get(import22.Config),new import23.ElementRef(this._el_4),this.renderer,this.parentInjector.get(import26.Toolbar,(null as any)),this._Navbar_2_4.context);
    this._appEl_4.initComponent(this._ToolbarTitle_4_4.context,([] as any[]),compView_4);
    this._text_5 = this.renderer.createText((null as any),'Friend Details',(null as any));
    compView_4.create(this._ToolbarTitle_4_4.context,[([] as any[]).concat([this._text_5])],(null as any));
    this._text_6 = this.renderer.createText((null as any),'\n  ',(null as any));
    compView_2.create(this._Navbar_2_4.context,[
      ([] as any[]),
      ([] as any[]),
      ([] as any[]),
      ([] as any[]).concat([
        this._text_3,
        this._el_4,
        this._text_6
      ]
      )
    ]
    ,(null as any));
    this._text_7 = this.renderer.createText(this._el_0,'\n\n',(null as any));
    this._text_8 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._el_9 = this.renderer.createElement(parentRenderNode,'ion-content',(null as any));
    this.renderer.setElementAttribute(this._el_9,'padding','');
    this._appEl_9 = new import3.AppElement(9,(null as any),this,this._el_9);
    var compView_9:any = import15.viewFactory_Content0(this.viewUtils,this.injector(9),this._appEl_9);
    this._Content_9_4 = new import15.Wrapper_Content(this.parentInjector.get(import22.Config),new import23.ElementRef(this._el_9),this.renderer,this.parentInjector.get(import25.App),this.parentInjector.get(import27.Keyboard),this.parentInjector.get(import28.NgZone),this.parentInjector.get(import24.ViewController,(null as any)),this.parentInjector.get(import29.Tabs,(null as any)));
    this._appEl_9.initComponent(this._Content_9_4.context,([] as any[]),compView_9);
    this._text_10 = this.renderer.createText((null as any),'\n\n  ',(null as any));
    this._el_11 = this.renderer.createElement((null as any),'div',(null as any));
    this.renderer.setElementAttribute(this._el_11,'end','');
    this.renderer.setElementAttribute(this._el_11,'padding','');
    this._text_12 = this.renderer.createText(this._el_11,'\n    ',(null as any));
    this._el_13 = this.renderer.createElement(this._el_11,'ion-segment',(null as any));
    this._Segment_13_3 = new import16.Wrapper_Segment(this.parentInjector.get(import22.Config),new import23.ElementRef(this._el_13),this.renderer,this.parentInjector.get(import30.NgControl,(null as any)));
    this._query_SegmentButton_13_0 = new import17.QueryList<any>();
    this._text_14 = this.renderer.createText(this._el_13,'\n      ',(null as any));
    this._el_15 = this.renderer.createElement(this._el_13,'ion-segment-button',(null as any));
    this.renderer.setElementAttribute(this._el_15,'class','segment-button');
    this.renderer.setElementAttribute(this._el_15,'role','button');
    this.renderer.setElementAttribute(this._el_15,'tappable','');
    this.renderer.setElementAttribute(this._el_15,'value','perfil');
    this._appEl_15 = new import3.AppElement(15,13,this,this._el_15);
    var compView_15:any = import16.viewFactory_SegmentButton0(this.viewUtils,this.injector(15),this._appEl_15);
    this._SegmentButton_15_4 = new import16.Wrapper_SegmentButton(this.renderer,new import23.ElementRef(this._el_15));
    this._appEl_15.initComponent(this._SegmentButton_15_4.context,([] as any[]),compView_15);
    this._text_16 = this.renderer.createText((null as any),'\n        Perfil\n      ',(null as any));
    compView_15.create(this._SegmentButton_15_4.context,[([] as any[]).concat([this._text_16])],(null as any));
    this._text_17 = this.renderer.createText(this._el_13,'\n      ',(null as any));
    this._el_18 = this.renderer.createElement(this._el_13,'ion-segment-button',(null as any));
    this.renderer.setElementAttribute(this._el_18,'class','segment-button');
    this.renderer.setElementAttribute(this._el_18,'role','button');
    this.renderer.setElementAttribute(this._el_18,'tappable','');
    this.renderer.setElementAttribute(this._el_18,'value','pr');
    this._appEl_18 = new import3.AppElement(18,13,this,this._el_18);
    var compView_18:any = import16.viewFactory_SegmentButton0(this.viewUtils,this.injector(18),this._appEl_18);
    this._SegmentButton_18_4 = new import16.Wrapper_SegmentButton(this.renderer,new import23.ElementRef(this._el_18));
    this._appEl_18.initComponent(this._SegmentButton_18_4.context,([] as any[]),compView_18);
    this._text_19 = this.renderer.createText((null as any),'\n        pr\n      ',(null as any));
    compView_18.create(this._SegmentButton_18_4.context,[([] as any[]).concat([this._text_19])],(null as any));
    this._text_20 = this.renderer.createText(this._el_13,'\n      ',(null as any));
    this._el_21 = this.renderer.createElement(this._el_13,'ion-segment-button',(null as any));
    this.renderer.setElementAttribute(this._el_21,'class','segment-button');
    this.renderer.setElementAttribute(this._el_21,'role','button');
    this.renderer.setElementAttribute(this._el_21,'tappable','');
    this.renderer.setElementAttribute(this._el_21,'value','program');
    this._appEl_21 = new import3.AppElement(21,13,this,this._el_21);
    var compView_21:any = import16.viewFactory_SegmentButton0(this.viewUtils,this.injector(21),this._appEl_21);
    this._SegmentButton_21_4 = new import16.Wrapper_SegmentButton(this.renderer,new import23.ElementRef(this._el_21));
    this._appEl_21.initComponent(this._SegmentButton_21_4.context,([] as any[]),compView_21);
    this._text_22 = this.renderer.createText((null as any),'\n        programs\n      ',(null as any));
    compView_21.create(this._SegmentButton_21_4.context,[([] as any[]).concat([this._text_22])],(null as any));
    this._text_23 = this.renderer.createText(this._el_13,'\n    ',(null as any));
    this._text_24 = this.renderer.createText(this._el_11,'\n  ',(null as any));
    this._text_25 = this.renderer.createText((null as any),'\n\n  ',(null as any));
    this._el_26 = this.renderer.createElement((null as any),'ion-card',(null as any));
    this._Card_26_3 = new import18.Wrapper_Card(this.parentInjector.get(import22.Config),new import23.ElementRef(this._el_26),this.renderer);
    this._text_27 = this.renderer.createText(this._el_26,'\n\n    ',(null as any));
    this._el_28 = this.renderer.createElement(this._el_26,'ion-card-header',(null as any));
    this._CardHeader_28_3 = new import18.Wrapper_CardHeader(this.parentInjector.get(import22.Config),new import23.ElementRef(this._el_28),this.renderer);
    this._text_29 = this.renderer.createText(this._el_28,'',(null as any));
    this._text_30 = this.renderer.createText(this._el_26,'\n\n    ',(null as any));
    this._el_31 = this.renderer.createElement(this._el_26,'ion-card-content',(null as any));
    this._CardContent_31_3 = new import18.Wrapper_CardContent(this.parentInjector.get(import22.Config),new import23.ElementRef(this._el_31),this.renderer);
    this._text_32 = this.renderer.createText(this._el_31,'\n      ',(null as any));
    this._el_33 = this.renderer.createElement(this._el_31,'img',(null as any));
    this._text_34 = this.renderer.createText(this._el_31,'\n      ',(null as any));
    this._el_35 = this.renderer.createElement(this._el_31,'p',(null as any));
    this._text_36 = this.renderer.createText(this._el_35,'',(null as any));
    this._text_37 = this.renderer.createText(this._el_31,'\n      ',(null as any));
    this._el_38 = this.renderer.createElement(this._el_31,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_38,'class','item item-block');
    this._appEl_38 = new import3.AppElement(38,31,this,this._el_38);
    var compView_38:any = import19.viewFactory_Item0(this.viewUtils,this.injector(38),this._appEl_38);
    this._Item_38_4 = new import19.Wrapper_Item(this.parentInjector.get(import31.Form),this.parentInjector.get(import22.Config),new import23.ElementRef(this._el_38),this.renderer,this.parentInjector.get(import32.ItemReorder,(null as any)));
    this._ItemContent_38_5 = new import19.Wrapper_ItemContent();
    this._query_Label_38_0 = new import17.QueryList<any>();
    this._query_Button_38_1 = new import17.QueryList<any>();
    this._query_Icon_38_2 = new import17.QueryList<any>();
    this._appEl_38.initComponent(this._Item_38_4.context,([] as any[]),compView_38);
    this._text_39 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_40 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_40,'item-left','');
    this.renderer.setElementAttribute(this._el_40,'name','people');
    this.renderer.setElementAttribute(this._el_40,'role','img');
    this._Icon_40_3 = new import20.Wrapper_Icon(this.parentInjector.get(import22.Config),new import23.ElementRef(this._el_40),this.renderer);
    this._text_41 = this.renderer.createText((null as any),' Friends\n        ',(null as any));
    this._el_42 = this.renderer.createElement((null as any),'ion-badge',(null as any));
    this.renderer.setElementAttribute(this._el_42,'item-right','');
    this._Badge_42_3 = new import21.Wrapper_Badge(this.parentInjector.get(import22.Config),new import23.ElementRef(this._el_42),this.renderer);
    this._text_43 = this.renderer.createText(this._el_42,'',(null as any));
    this._text_44 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._query_Label_38_0.reset(([] as any[]));
    this._Item_38_4.context.contentLabel = this._query_Label_38_0.first;
    compView_38.create(this._Item_38_4.context,[
      ([] as any[]).concat([this._el_40]),
      ([] as any[]),
      ([] as any[]).concat([
        this._text_39,
        this._text_41,
        this._text_44
      ]
      ),
      ([] as any[]),
      ([] as any[]).concat([this._el_42])
    ]
    ,(null as any));
    this._text_45 = this.renderer.createText(this._el_31,'\n    ',(null as any));
    this._text_46 = this.renderer.createText(this._el_26,'\n\n  ',(null as any));
    this._text_47 = this.renderer.createText((null as any),'\n\n',(null as any));
    compView_9.create(this._Content_9_4.context,[
      ([] as any[]),
      ([] as any[]).concat([
        this._text_10,
        this._el_11,
        this._text_25,
        this._el_26,
        this._text_47
      ]
      ),
      ([] as any[])
    ]
    ,(null as any));
    this._text_48 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this._expr_1 = import7.UNINITIALIZED;
    this._expr_2 = import7.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_15,'click',this.eventHandler(this._handle_click_15_0.bind(this)));
    var disposable_1:Function = this.renderer.listen(this._el_18,'click',this.eventHandler(this._handle_click_18_0.bind(this)));
    var disposable_2:Function = this.renderer.listen(this._el_21,'click',this.eventHandler(this._handle_click_21_0.bind(this)));
    this._expr_9 = import7.UNINITIALIZED;
    this._expr_10 = import7.UNINITIALIZED;
    this._expr_11 = import7.UNINITIALIZED;
    this._expr_13 = import7.UNINITIALIZED;
    this._expr_14 = import7.UNINITIALIZED;
    this.init(([] as any[]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._text_6,
      this._text_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._el_13,
      this._text_14,
      this._el_15,
      this._text_16,
      this._text_17,
      this._el_18,
      this._text_19,
      this._text_20,
      this._el_21,
      this._text_22,
      this._text_23,
      this._text_24,
      this._text_25,
      this._el_26,
      this._text_27,
      this._el_28,
      this._text_29,
      this._text_30,
      this._el_31,
      this._text_32,
      this._el_33,
      this._text_34,
      this._el_35,
      this._text_36,
      this._text_37,
      this._el_38,
      this._text_39,
      this._el_40,
      this._text_41,
      this._el_42,
      this._text_43,
      this._text_44,
      this._text_45,
      this._text_46,
      this._text_47,
      this._text_48
    ]
    ,[
      disposable_0,
      disposable_1,
      disposable_2
    ]
    ,([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import33.ToolbarTitle) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 5)))) { return this._ToolbarTitle_4_4.context; }
    if (((token === import34.Navbar) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 6)))) { return this._Navbar_2_4.context; }
    if (((token === import26.Header) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._Header_0_3.context; }
    if (((token === import35.SegmentButton) && ((15 <= requestNodeIndex) && (requestNodeIndex <= 16)))) { return this._SegmentButton_15_4.context; }
    if (((token === import35.SegmentButton) && ((18 <= requestNodeIndex) && (requestNodeIndex <= 19)))) { return this._SegmentButton_18_4.context; }
    if (((token === import35.SegmentButton) && ((21 <= requestNodeIndex) && (requestNodeIndex <= 22)))) { return this._SegmentButton_21_4.context; }
    if (((token === import35.Segment) && ((13 <= requestNodeIndex) && (requestNodeIndex <= 23)))) { return this._Segment_13_3.context; }
    if (((token === import36.CardHeader) && ((28 <= requestNodeIndex) && (requestNodeIndex <= 29)))) { return this._CardHeader_28_3.context; }
    if (((token === import37.Icon) && (40 === requestNodeIndex))) { return this._Icon_40_3.context; }
    if (((token === import38.Badge) && ((42 <= requestNodeIndex) && (requestNodeIndex <= 43)))) { return this._Badge_42_3.context; }
    if (((token === import39.Item) && ((38 <= requestNodeIndex) && (requestNodeIndex <= 44)))) { return this._Item_38_4.context; }
    if (((token === import39.ItemContent) && ((38 <= requestNodeIndex) && (requestNodeIndex <= 44)))) { return this._ItemContent_38_5.context; }
    if (((token === import36.CardContent) && ((31 <= requestNodeIndex) && (requestNodeIndex <= 45)))) { return this._CardContent_31_3.context; }
    if (((token === import36.Card) && ((26 <= requestNodeIndex) && (requestNodeIndex <= 46)))) { return this._Card_26_3.context; }
    if (((token === import40.Content) && ((9 <= requestNodeIndex) && (requestNodeIndex <= 47)))) { return this._Content_9_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._Header_0_3.detectChangesInternal(this,this._el_0,throwOnChange);
    this._Navbar_2_4.detectChangesInternal(this,this._el_2,throwOnChange);
    if (this._ToolbarTitle_4_4.detectChangesInternal(this,this._el_4,throwOnChange)) { this._appEl_4.componentView.markAsCheckOnce(); }
    if (this._Content_9_4.detectChangesInternal(this,this._el_9,throwOnChange)) { this._appEl_9.componentView.markAsCheckOnce(); }
    this._Segment_13_3.detectChangesInternal(this,this._el_13,throwOnChange);
    const currVal_4:any = 'perfil';
    this._SegmentButton_15_4.check_value(currVal_4,throwOnChange,false);
    this._SegmentButton_15_4.detectChangesInternal(this,this._el_15,throwOnChange);
    const currVal_6:any = 'pr';
    this._SegmentButton_18_4.check_value(currVal_6,throwOnChange,false);
    this._SegmentButton_18_4.detectChangesInternal(this,this._el_18,throwOnChange);
    const currVal_8:any = 'program';
    this._SegmentButton_21_4.check_value(currVal_8,throwOnChange,false);
    this._SegmentButton_21_4.detectChangesInternal(this,this._el_21,throwOnChange);
    this._Card_26_3.detectChangesInternal(this,this._el_26,throwOnChange);
    this._CardHeader_28_3.detectChangesInternal(this,this._el_28,throwOnChange);
    this._CardContent_31_3.detectChangesInternal(this,this._el_31,throwOnChange);
    if (this._Item_38_4.detectChangesInternal(this,this._el_38,throwOnChange)) { this._appEl_38.componentView.markAsCheckOnce(); }
    this._ItemContent_38_5.detectChangesInternal(this,this._el_38,throwOnChange);
    const currVal_12:any = 'people';
    this._Icon_40_3.check_name(currVal_12,throwOnChange,false);
    this._Icon_40_3.detectChangesInternal(this,this._el_40,throwOnChange);
    this._Badge_42_3.detectChangesInternal(this,this._el_42,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_SegmentButton_13_0.dirty) {
        this._query_SegmentButton_13_0.reset([
          this._SegmentButton_15_4.context,
          this._SegmentButton_18_4.context,
          this._SegmentButton_21_4.context
        ]
        );
        this._Segment_13_3.context._buttons = this._query_SegmentButton_13_0;
        this._query_SegmentButton_13_0.notifyOnChanges();
      }
      if (this._query_Button_38_1.dirty) {
        this._query_Button_38_1.reset(([] as any[]));
        this._Item_38_4.context._buttons = this._query_Button_38_1;
        this._query_Button_38_1.notifyOnChanges();
      }
      if (this._query_Icon_38_2.dirty) {
        this._query_Icon_38_2.reset([this._Icon_40_3.context]);
        this._Item_38_4.context._icons = this._query_Icon_38_2;
        this._query_Icon_38_2.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._Item_38_4.context.ngAfterContentInit(); }
    }
    const currVal_0:any = this._Navbar_2_4.context._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setElementProperty(this._el_2,'hidden',currVal_0);
      this._expr_0 = currVal_0;
    }
    const currVal_1:any = this._Navbar_2_4.context._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementClass(this._el_2,'statusbar-padding',currVal_1);
      this._expr_1 = currVal_1;
    }
    const currVal_2:any = this._Content_9_4.context._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setElementClass(this._el_9,'statusbar-padding',currVal_2);
      this._expr_2 = currVal_2;
    }
    const currVal_9:any = import4.interpolate(1,'\n      ',this.context.friend.username,'\n    ');
    if (import4.checkBinding(throwOnChange,this._expr_9,currVal_9)) {
      this.renderer.setText(this._text_29,currVal_9);
      this._expr_9 = currVal_9;
    }
    const currVal_10:any = import4.interpolate(1,'',this.context.friend.image,'');
    if (import4.checkBinding(throwOnChange,this._expr_10,currVal_10)) {
      this.renderer.setElementProperty(this._el_33,'src',this.viewUtils.sanitizer.sanitize(import41.SecurityContext.URL,currVal_10));
      this._expr_10 = currVal_10;
    }
    const currVal_11:any = import4.interpolate(2,' ',this.context.friend.name,' ',this.context.friend.surname,' ');
    if (import4.checkBinding(throwOnChange,this._expr_11,currVal_11)) {
      this.renderer.setText(this._text_36,currVal_11);
      this._expr_11 = currVal_11;
    }
    const currVal_13:any = this._Icon_40_3.context._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_13,currVal_13)) {
      this.renderer.setElementClass(this._el_40,'hide',currVal_13);
      this._expr_13 = currVal_13;
    }
    const currVal_14:any = import4.interpolate(1,'',this.context.friendCount,'');
    if (import4.checkBinding(throwOnChange,this._expr_14,currVal_14)) {
      this.renderer.setText(this._text_43,currVal_14);
      this._expr_14 = currVal_14;
    }
    this.detectViewChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if ((this.numberOfChecks === 0)) { this._Navbar_2_4.context.ngAfterViewInit(); }
      if ((this.numberOfChecks === 0)) { this._Segment_13_3.context.ngAfterViewInit(); }
    }
  }
  destroyInternal():void {
    this._Icon_40_3.context.ngOnDestroy();
    this._Content_9_4.context.ngOnDestroy();
  }
  private _handle_click_15_0($event:any):boolean {
    this._appEl_15.componentView.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._SegmentButton_15_4.context.onClick()) !== false);
    return (true && pd_0);
  }
  private _handle_click_18_0($event:any):boolean {
    this._appEl_18.componentView.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._SegmentButton_18_4.context.onClick()) !== false);
    return (true && pd_0);
  }
  private _handle_click_21_0($event:any):boolean {
    this._appEl_21.componentView.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._SegmentButton_21_4.context.onClick()) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_FriendDetails0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<import0.FriendDetails> {
  if ((renderType_FriendDetails === (null as any))) { (renderType_FriendDetails = viewUtils.createRenderComponentType('',0,import10.ViewEncapsulation.None,styles_FriendDetails,{})); }
  return new _View_FriendDetails0(viewUtils,parentInjector,declarationEl);
}