/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from './pr';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/element';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from 'ionic-angular/navigation/nav-controller';
import * as import9 from '@angular/forms/src/form_builder';
import * as import10 from 'ionic-angular/navigation/nav-params';
import * as import11 from '../../providers/exercise-data';
import * as import12 from 'ionic-angular/components/loading/loading';
import * as import13 from 'ionic-angular/components/alert/alert';
import * as import14 from 'ionic-angular/navigation/view-controller';
import * as import15 from '@angular/core/src/metadata/view';
import * as import16 from '@angular/core/src/linker/component_factory';
import * as import17 from '../../node_modules/ionic-angular/components/toolbar/toolbar.ngfactory';
import * as import18 from '../../node_modules/ionic-angular/components/navbar/navbar.ngfactory';
import * as import19 from '../../node_modules/ionic-angular/components/button/button.ngfactory';
import * as import20 from '../../node_modules/ionic-angular/components/icon/icon.ngfactory';
import * as import21 from '../../node_modules/ionic-angular/components/toolbar/toolbar-title.ngfactory';
import * as import22 from '../../node_modules/ionic-angular/components/content/content.ngfactory';
import * as import23 from '../../node_modules/ionic-angular/components/card/card.ngfactory';
import * as import24 from '../../node_modules/@angular/common/src/directives/ng_if.ngfactory';
import * as import25 from '../../node_modules/@angular/forms/src/directives/reactive_directives/form_group_directive.ngfactory';
import * as import26 from '../../node_modules/@angular/forms/src/directives/ng_control_status.ngfactory';
import * as import27 from '../../node_modules/ionic-angular/components/item/item.ngfactory';
import * as import28 from '@angular/core/src/linker/query_list';
import * as import29 from '../../node_modules/ionic-angular/components/label/label.ngfactory';
import * as import30 from '../../node_modules/@angular/forms/src/directives/reactive_directives/form_control_name.ngfactory';
import * as import31 from '../../node_modules/ionic-angular/components/input/input.ngfactory';
import * as import32 from '../../node_modules/ionic-angular/components/select/select.ngfactory';
import * as import33 from '../../node_modules/@angular/common/src/directives/ng_for.ngfactory';
import * as import34 from 'ionic-angular/config/config';
import * as import35 from '@angular/core/src/linker/element_ref';
import * as import36 from 'ionic-angular/components/app/app';
import * as import37 from 'ionic-angular/components/toolbar/toolbar';
import * as import38 from 'ionic-angular/util/keyboard';
import * as import39 from '@angular/core/src/zone/ng_zone';
import * as import40 from 'ionic-angular/components/tabs/tabs';
import * as import41 from '@angular/core/src/linker/template_ref';
import * as import42 from 'ionic-angular/util/form';
import * as import43 from 'ionic-angular/components/item/item-reorder';
import * as import44 from 'ionic-angular/platform/platform';
import * as import45 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import46 from 'ionic-angular/components/icon/icon';
import * as import47 from 'ionic-angular/components/button/button';
import * as import48 from 'ionic-angular/components/toolbar/toolbar-title';
import * as import49 from 'ionic-angular/components/navbar/navbar';
import * as import50 from 'ionic-angular/components/card/card';
import * as import51 from '@angular/common/src/directives/ng_if';
import * as import52 from 'ionic-angular/components/label/label';
import * as import53 from '@angular/forms/src/directives/reactive_directives/form_control_name';
import * as import54 from '@angular/forms/src/directives/ng_control';
import * as import55 from '@angular/forms/src/directives/ng_control_status';
import * as import56 from 'ionic-angular/components/input/input';
import * as import57 from 'ionic-angular/components/item/item';
import * as import58 from '@angular/common/src/directives/ng_for';
import * as import59 from 'ionic-angular/components/select/select';
import * as import60 from '@angular/forms/src/directives/control_value_accessor';
import * as import61 from '@angular/forms/src/directives/reactive_directives/form_group_directive';
import * as import62 from '@angular/forms/src/directives/control_container';
import * as import63 from 'ionic-angular/components/content/content';
import * as import64 from '../../node_modules/ionic-angular/components/option/option.ngfactory';
import * as import65 from 'ionic-angular/components/option/option';
export class Wrapper_PrPage {
  context:import0.PrPage;
  changed:boolean;
  constructor(p0:any,p1:any,p2:any,p3:any,p4:any,p5:any,p6:any) {
    this.changed = false;
    this.context = new import0.PrPage(p0,p1,p2,p3,p4,p5,p6);
  }
  detectChangesInternal(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this.changed;
    this.changed = false;
    return changed;
  }
}
var renderType_PrPage_Host:import2.RenderComponentType = (null as any);
class _View_PrPage_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _PrPage_0_4:Wrapper_PrPage;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_PrPage_Host0,renderType_PrPage_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.selectOrCreateHostElement('ng-component',rootSelector,(null as any));
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_PrPage0(this.viewUtils,this.injector(0),this._appEl_0);
    this._PrPage_0_4 = new Wrapper_PrPage(this.parentInjector.get(import8.NavController),this.parentInjector.get(import9.FormBuilder),this.parentInjector.get(import10.NavParams),this.parentInjector.get(import11.ExerciseData),this.parentInjector.get(import12.LoadingController),this.parentInjector.get(import13.AlertController),this.parentInjector.get(import14.ViewController));
    this._appEl_0.initComponent(this._PrPage_0_4.context,([] as any[]),compView_0);
    compView_0.create(this._PrPage_0_4.context,this.projectableNodes,(null as any));
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.PrPage) && (0 === requestNodeIndex))) { return this._PrPage_0_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._PrPage_0_4.detectChangesInternal(this,this._el_0,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_PrPage_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  if ((renderType_PrPage_Host === (null as any))) { (renderType_PrPage_Host = viewUtils.createRenderComponentType('',0,import15.ViewEncapsulation.None,([] as any[]),{})); }
  return new _View_PrPage_Host0(viewUtils,parentInjector,declarationEl);
}
export const PrPageNgFactory:import16.ComponentFactory<import0.PrPage> = new import16.ComponentFactory<import0.PrPage>('ng-component',viewFactory_PrPage_Host0,import0.PrPage);
const styles_PrPage:any[] = ([] as any[]);
var renderType_PrPage:import2.RenderComponentType = (null as any);
class _View_PrPage0 extends import1.AppView<import0.PrPage> {
  _el_0:any;
  _Header_0_3:import17.Wrapper_Header;
  _text_1:any;
  _el_2:any;
  /*private*/ _appEl_2:import3.AppElement;
  _Navbar_2_4:import18.Wrapper_Navbar;
  _text_3:any;
  _el_4:any;
  /*private*/ _appEl_4:import3.AppElement;
  _Button_4_4:import19.Wrapper_Button;
  _text_5:any;
  _el_6:any;
  _Icon_6_3:import20.Wrapper_Icon;
  _text_7:any;
  _text_8:any;
  _el_9:any;
  /*private*/ _appEl_9:import3.AppElement;
  _ToolbarTitle_9_4:import21.Wrapper_ToolbarTitle;
  _text_10:any;
  _text_11:any;
  _text_12:any;
  _text_13:any;
  _el_14:any;
  /*private*/ _appEl_14:import3.AppElement;
  _Content_14_4:import22.Wrapper_Content;
  _text_15:any;
  _el_16:any;
  _Card_16_3:import23.Wrapper_Card;
  _text_17:any;
  _el_18:any;
  _CardHeader_18_3:import23.Wrapper_CardHeader;
  _text_19:any;
  _text_20:any;
  _el_21:any;
  _CardContent_21_3:import23.Wrapper_CardContent;
  _text_22:any;
  _el_23:any;
  _text_24:any;
  _anchor_25:any;
  /*private*/ _appEl_25:import3.AppElement;
  _TemplateRef_25_5:any;
  _NgIf_25_6:import24.Wrapper_NgIf;
  _text_26:any;
  _anchor_27:any;
  /*private*/ _appEl_27:import3.AppElement;
  _TemplateRef_27_5:any;
  _NgIf_27_6:import24.Wrapper_NgIf;
  _text_28:any;
  _anchor_29:any;
  /*private*/ _appEl_29:import3.AppElement;
  _TemplateRef_29_5:any;
  _NgIf_29_6:import24.Wrapper_NgIf;
  _text_30:any;
  _text_31:any;
  _el_32:any;
  _text_33:any;
  _text_34:any;
  _el_35:any;
  _text_36:any;
  _text_37:any;
  _text_38:any;
  _text_39:any;
  _el_40:any;
  _FormGroupDirective_40_3:import25.Wrapper_FormGroupDirective;
  _ControlContainer_40_4:any;
  _NgControlStatusGroup_40_5:import26.Wrapper_NgControlStatusGroup;
  _text_41:any;
  _el_42:any;
  /*private*/ _appEl_42:import3.AppElement;
  _Item_42_4:import27.Wrapper_Item;
  _ItemContent_42_5:import27.Wrapper_ItemContent;
  _query_Label_42_0:import28.QueryList<any>;
  _query_Button_42_1:import28.QueryList<any>;
  _query_Icon_42_2:import28.QueryList<any>;
  _text_43:any;
  _el_44:any;
  _Label_44_3:import29.Wrapper_Label;
  _text_45:any;
  _text_46:any;
  _el_47:any;
  /*private*/ _appEl_47:import3.AppElement;
  _FormControlName_47_4:import30.Wrapper_FormControlName;
  _NgControl_47_5:any;
  _NgControlStatus_47_6:import26.Wrapper_NgControlStatus;
  _TextInput_47_7:import31.Wrapper_TextInput;
  _text_48:any;
  _text_49:any;
  _el_50:any;
  /*private*/ _appEl_50:import3.AppElement;
  _Item_50_4:import27.Wrapper_Item;
  _ItemContent_50_5:import27.Wrapper_ItemContent;
  _query_Label_50_0:import28.QueryList<any>;
  _query_Button_50_1:import28.QueryList<any>;
  _query_Icon_50_2:import28.QueryList<any>;
  _text_51:any;
  _el_52:any;
  _Label_52_3:import29.Wrapper_Label;
  _text_53:any;
  _text_54:any;
  _el_55:any;
  /*private*/ _appEl_55:import3.AppElement;
  _Select_55_4:import32.Wrapper_Select;
  _NG_VALUE_ACCESSOR_55_5:any[];
  _FormControlName_55_6:import30.Wrapper_FormControlName;
  _NgControl_55_7:any;
  _NgControlStatus_55_8:import26.Wrapper_NgControlStatus;
  _query_Option_55_0:import28.QueryList<any>;
  _text_56:any;
  _anchor_57:any;
  /*private*/ _appEl_57:import3.AppElement;
  _TemplateRef_57_5:any;
  _NgFor_57_6:import33.Wrapper_NgFor;
  _text_58:any;
  _text_59:any;
  _text_60:any;
  _el_61:any;
  /*private*/ _appEl_61:import3.AppElement;
  _Item_61_4:import27.Wrapper_Item;
  _ItemContent_61_5:import27.Wrapper_ItemContent;
  _query_Label_61_0:import28.QueryList<any>;
  _query_Button_61_1:import28.QueryList<any>;
  _query_Icon_61_2:import28.QueryList<any>;
  _text_62:any;
  _el_63:any;
  _Label_63_3:import29.Wrapper_Label;
  _text_64:any;
  _text_65:any;
  _el_66:any;
  /*private*/ _appEl_66:import3.AppElement;
  _Select_66_4:import32.Wrapper_Select;
  _NG_VALUE_ACCESSOR_66_5:any[];
  _FormControlName_66_6:import30.Wrapper_FormControlName;
  _NgControl_66_7:any;
  _NgControlStatus_66_8:import26.Wrapper_NgControlStatus;
  _query_Option_66_0:import28.QueryList<any>;
  _text_67:any;
  _anchor_68:any;
  /*private*/ _appEl_68:import3.AppElement;
  _TemplateRef_68_5:any;
  _NgFor_68_6:import33.Wrapper_NgFor;
  _text_69:any;
  _text_70:any;
  _text_71:any;
  _el_72:any;
  /*private*/ _appEl_72:import3.AppElement;
  _Button_72_4:import19.Wrapper_Button;
  _text_73:any;
  _text_74:any;
  _text_75:any;
  _text_76:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_5:any;
  /*private*/ _expr_6:any;
  /*private*/ _expr_7:any;
  /*private*/ _expr_8:any;
  /*private*/ _expr_12:any;
  /*private*/ _expr_13:any;
  /*private*/ _expr_18:any;
  /*private*/ _expr_19:any;
  /*private*/ _expr_20:any;
  /*private*/ _expr_21:any;
  /*private*/ _expr_22:any;
  /*private*/ _expr_23:any;
  /*private*/ _expr_24:any;
  /*private*/ _expr_26:any;
  /*private*/ _expr_27:any;
  /*private*/ _expr_28:any;
  /*private*/ _expr_29:any;
  /*private*/ _expr_30:any;
  /*private*/ _expr_31:any;
  /*private*/ _expr_38:any;
  /*private*/ _expr_41:any;
  /*private*/ _expr_42:any;
  /*private*/ _expr_43:any;
  /*private*/ _expr_44:any;
  /*private*/ _expr_45:any;
  /*private*/ _expr_46:any;
  /*private*/ _expr_52:any;
  /*private*/ _expr_55:any;
  /*private*/ _expr_56:any;
  /*private*/ _expr_57:any;
  /*private*/ _expr_58:any;
  /*private*/ _expr_59:any;
  /*private*/ _expr_60:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_PrPage0,renderType_PrPage,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'ion-header',(null as any));
    this._Header_0_3 = new import17.Wrapper_Header(this.parentInjector.get(import34.Config),new import35.ElementRef(this._el_0),this.renderer,this.parentInjector.get(import14.ViewController,(null as any)));
    this._text_1 = this.renderer.createText(this._el_0,'\n\n  ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'ion-navbar',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','toolbar');
    this._appEl_2 = new import3.AppElement(2,0,this,this._el_2);
    var compView_2:any = import18.viewFactory_Navbar0(this.viewUtils,this.injector(2),this._appEl_2);
    this._Navbar_2_4 = new import18.Wrapper_Navbar(this.parentInjector.get(import36.App),this.parentInjector.get(import14.ViewController,(null as any)),this.parentInjector.get(import8.NavController,(null as any)),this.parentInjector.get(import34.Config),new import35.ElementRef(this._el_2),this.renderer);
    this._appEl_2.initComponent(this._Navbar_2_4.context,([] as any[]),compView_2);
    this._text_3 = this.renderer.createText((null as any),'\n\n    ',(null as any));
    this._el_4 = this.renderer.createElement((null as any),'button',(null as any));
    this.renderer.setElementAttribute(this._el_4,'class','backButton');
    this.renderer.setElementAttribute(this._el_4,'clear','');
    this.renderer.setElementAttribute(this._el_4,'dark','');
    this.renderer.setElementAttribute(this._el_4,'ion-button','');
    this._appEl_4 = new import3.AppElement(4,2,this,this._el_4);
    var compView_4:any = import19.viewFactory_Button0(this.viewUtils,this.injector(4),this._appEl_4);
    this._Button_4_4 = new import19.Wrapper_Button((null as any),'',this.parentInjector.get(import34.Config),new import35.ElementRef(this._el_4),this.renderer);
    this._appEl_4.initComponent(this._Button_4_4.context,([] as any[]),compView_4);
    this._text_5 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_6 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_6,'name','md-arrow-back');
    this.renderer.setElementAttribute(this._el_6,'role','img');
    this._Icon_6_3 = new import20.Wrapper_Icon(this.parentInjector.get(import34.Config),new import35.ElementRef(this._el_6),this.renderer);
    this._text_7 = this.renderer.createText((null as any),'\n    ',(null as any));
      compView_4.create(this._Button_4_4.context,[([] as any[]).concat([
        this._text_5,
        this._el_6,
        this._text_7
      ]
    )],(null as any));
    this._text_8 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_9 = this.renderer.createElement((null as any),'ion-title',(null as any));
    this.renderer.setElementAttribute(this._el_9,'class','title');
    this._appEl_9 = new import3.AppElement(9,2,this,this._el_9);
    var compView_9:any = import21.viewFactory_ToolbarTitle0(this.viewUtils,this.injector(9),this._appEl_9);
    this._ToolbarTitle_9_4 = new import21.Wrapper_ToolbarTitle(this.parentInjector.get(import34.Config),new import35.ElementRef(this._el_9),this.renderer,this.parentInjector.get(import37.Toolbar,(null as any)),this._Navbar_2_4.context);
    this._appEl_9.initComponent(this._ToolbarTitle_9_4.context,([] as any[]),compView_9);
    this._text_10 = this.renderer.createText((null as any),'',(null as any));
    compView_9.create(this._ToolbarTitle_9_4.context,[([] as any[]).concat([this._text_10])],(null as any));
    this._text_11 = this.renderer.createText((null as any),'\n\n  ',(null as any));
    compView_2.create(this._Navbar_2_4.context,[
      ([] as any[]),
      ([] as any[]),
      ([] as any[]),
      ([] as any[]).concat([
        this._text_3,
        this._el_4,
        this._text_8,
        this._el_9,
        this._text_11
      ]
      )
    ]
    ,(null as any));
    this._text_12 = this.renderer.createText(this._el_0,'\n\n',(null as any));
    this._text_13 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._el_14 = this.renderer.createElement(parentRenderNode,'ion-content',(null as any));
    this.renderer.setElementAttribute(this._el_14,'padding','');
    this._appEl_14 = new import3.AppElement(14,(null as any),this,this._el_14);
    var compView_14:any = import22.viewFactory_Content0(this.viewUtils,this.injector(14),this._appEl_14);
    this._Content_14_4 = new import22.Wrapper_Content(this.parentInjector.get(import34.Config),new import35.ElementRef(this._el_14),this.renderer,this.parentInjector.get(import36.App),this.parentInjector.get(import38.Keyboard),this.parentInjector.get(import39.NgZone),this.parentInjector.get(import14.ViewController,(null as any)),this.parentInjector.get(import40.Tabs,(null as any)));
    this._appEl_14.initComponent(this._Content_14_4.context,([] as any[]),compView_14);
    this._text_15 = this.renderer.createText((null as any),'\n\n  ',(null as any));
    this._el_16 = this.renderer.createElement((null as any),'ion-card',(null as any));
    this._Card_16_3 = new import23.Wrapper_Card(this.parentInjector.get(import34.Config),new import35.ElementRef(this._el_16),this.renderer);
    this._text_17 = this.renderer.createText(this._el_16,'\n\n    ',(null as any));
    this._el_18 = this.renderer.createElement(this._el_16,'ion-card-header',(null as any));
    this._CardHeader_18_3 = new import23.Wrapper_CardHeader(this.parentInjector.get(import34.Config),new import35.ElementRef(this._el_18),this.renderer);
    this._text_19 = this.renderer.createText(this._el_18,'\n      Actual PR\n    ',(null as any));
    this._text_20 = this.renderer.createText(this._el_16,'\n\n    ',(null as any));
    this._el_21 = this.renderer.createElement(this._el_16,'ion-card-content',(null as any));
    this._CardContent_21_3 = new import23.Wrapper_CardContent(this.parentInjector.get(import34.Config),new import35.ElementRef(this._el_21),this.renderer);
    this._text_22 = this.renderer.createText(this._el_21,'\n      You have\n      ',(null as any));
    this._el_23 = this.renderer.createElement(this._el_21,'strong',(null as any));
    this._text_24 = this.renderer.createText(this._el_23,'',(null as any));
    this._anchor_25 = this.renderer.createTemplateAnchor(this._el_23,(null as any));
    this._appEl_25 = new import3.AppElement(25,23,this,this._anchor_25);
    this._TemplateRef_25_5 = new import41.TemplateRef_(this._appEl_25,viewFactory_PrPage1);
    this._NgIf_25_6 = new import24.Wrapper_NgIf(this._appEl_25.vcRef,this._TemplateRef_25_5);
    this._text_26 = this.renderer.createText(this._el_23,'\n        ',(null as any));
    this._anchor_27 = this.renderer.createTemplateAnchor(this._el_23,(null as any));
    this._appEl_27 = new import3.AppElement(27,23,this,this._anchor_27);
    this._TemplateRef_27_5 = new import41.TemplateRef_(this._appEl_27,viewFactory_PrPage2);
    this._NgIf_27_6 = new import24.Wrapper_NgIf(this._appEl_27.vcRef,this._TemplateRef_27_5);
    this._text_28 = this.renderer.createText(this._el_23,'\n        ',(null as any));
    this._anchor_29 = this.renderer.createTemplateAnchor(this._el_23,(null as any));
    this._appEl_29 = new import3.AppElement(29,23,this,this._anchor_29);
    this._TemplateRef_29_5 = new import41.TemplateRef_(this._appEl_29,viewFactory_PrPage3);
    this._NgIf_29_6 = new import24.Wrapper_NgIf(this._appEl_29.vcRef,this._TemplateRef_29_5);
    this._text_30 = this.renderer.createText(this._el_23,'\n      ',(null as any));
    this._text_31 = this.renderer.createText(this._el_21,'\n      in\n      ',(null as any));
    this._el_32 = this.renderer.createElement(this._el_21,'strong',(null as any));
    this._text_33 = this.renderer.createText(this._el_32,'',(null as any));
    this._text_34 = this.renderer.createText(this._el_21,'\n      and you did this score at\n      ',(null as any));
    this._el_35 = this.renderer.createElement(this._el_21,'i',(null as any));
    this._text_36 = this.renderer.createText(this._el_35,'',(null as any));
    this._text_37 = this.renderer.createText(this._el_21,'\n    ',(null as any));
    this._text_38 = this.renderer.createText(this._el_16,'\n\n  ',(null as any));
    this._text_39 = this.renderer.createText((null as any),'\n\n  ',(null as any));
    this._el_40 = this.renderer.createElement((null as any),'form',(null as any));
    this.renderer.setElementAttribute(this._el_40,'novalidate','');
    this._FormGroupDirective_40_3 = new import25.Wrapper_FormGroupDirective((null as any),(null as any));
    this._ControlContainer_40_4 = this._FormGroupDirective_40_3.context;
    this._NgControlStatusGroup_40_5 = new import26.Wrapper_NgControlStatusGroup(this._ControlContainer_40_4);
    this._text_41 = this.renderer.createText(this._el_40,'\n\n    ',(null as any));
    this._el_42 = this.renderer.createElement(this._el_40,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_42,'class','item item-block');
    this._appEl_42 = new import3.AppElement(42,40,this,this._el_42);
    var compView_42:any = import27.viewFactory_Item0(this.viewUtils,this.injector(42),this._appEl_42);
    this._Item_42_4 = new import27.Wrapper_Item(this.parentInjector.get(import42.Form),this.parentInjector.get(import34.Config),new import35.ElementRef(this._el_42),this.renderer,this.parentInjector.get(import43.ItemReorder,(null as any)));
    this._ItemContent_42_5 = new import27.Wrapper_ItemContent();
    this._query_Label_42_0 = new import28.QueryList<any>();
    this._query_Button_42_1 = new import28.QueryList<any>();
    this._query_Icon_42_2 = new import28.QueryList<any>();
    this._appEl_42.initComponent(this._Item_42_4.context,([] as any[]),compView_42);
    this._text_43 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_44 = this.renderer.createElement((null as any),'ion-label',(null as any));
    this.renderer.setElementAttribute(this._el_44,'stacked','');
    this._Label_44_3 = new import29.Wrapper_Label(this.parentInjector.get(import34.Config),new import35.ElementRef(this._el_44),this.renderer,(null as any),'',(null as any),(null as any));
    this._text_45 = this.renderer.createText(this._el_44,'',(null as any));
    this._text_46 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_47 = this.renderer.createElement((null as any),'ion-input',(null as any));
    this.renderer.setElementAttribute(this._el_47,'formControlName','pr');
    this.renderer.setElementAttribute(this._el_47,'placeholder','Enter new value');
    this.renderer.setElementAttribute(this._el_47,'type','pr');
    this._appEl_47 = new import3.AppElement(47,42,this,this._el_47);
    var compView_47:any = import31.viewFactory_TextInput0(this.viewUtils,this.injector(47),this._appEl_47);
    this._FormControlName_47_4 = new import30.Wrapper_FormControlName(this._ControlContainer_40_4,(null as any),(null as any),(null as any));
    this._NgControl_47_5 = this._FormControlName_47_4.context;
    this._NgControlStatus_47_6 = new import26.Wrapper_NgControlStatus(this._NgControl_47_5);
    this._TextInput_47_7 = new import31.Wrapper_TextInput(this.parentInjector.get(import34.Config),this.parentInjector.get(import42.Form),this._Item_42_4.context,this.parentInjector.get(import36.App),this.parentInjector.get(import44.Platform),new import35.ElementRef(this._el_47),this.renderer,this._Content_14_4.context,this.parentInjector.get(import8.NavController,(null as any)),this._NgControl_47_5);
    this._appEl_47.initComponent(this._TextInput_47_7.context,([] as any[]),compView_47);
    compView_47.create(this._TextInput_47_7.context,([] as any[]),(null as any));
    this._text_48 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._query_Label_42_0.reset([this._Label_44_3.context]);
    this._Item_42_4.context.contentLabel = this._query_Label_42_0.first;
    compView_42.create(this._Item_42_4.context,[
      ([] as any[]),
      ([] as any[]).concat([this._el_44]),
      ([] as any[]).concat([
        this._text_43,
        this._text_46,
        this._text_48
      ]
      ),
      ([] as any[]).concat([this._el_47]),
      ([] as any[])
    ]
    ,(null as any));
    this._text_49 = this.renderer.createText(this._el_40,'\n\n    ',(null as any));
    this._el_50 = this.renderer.createElement(this._el_40,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_50,'class','item item-block');
    this._appEl_50 = new import3.AppElement(50,40,this,this._el_50);
    var compView_50:any = import27.viewFactory_Item0(this.viewUtils,this.injector(50),this._appEl_50);
    this._Item_50_4 = new import27.Wrapper_Item(this.parentInjector.get(import42.Form),this.parentInjector.get(import34.Config),new import35.ElementRef(this._el_50),this.renderer,this.parentInjector.get(import43.ItemReorder,(null as any)));
    this._ItemContent_50_5 = new import27.Wrapper_ItemContent();
    this._query_Label_50_0 = new import28.QueryList<any>();
    this._query_Button_50_1 = new import28.QueryList<any>();
    this._query_Icon_50_2 = new import28.QueryList<any>();
    this._appEl_50.initComponent(this._Item_50_4.context,([] as any[]),compView_50);
    this._text_51 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_52 = this.renderer.createElement((null as any),'ion-label',(null as any));
    this.renderer.setElementAttribute(this._el_52,'stacked','');
    this._Label_52_3 = new import29.Wrapper_Label(this.parentInjector.get(import34.Config),new import35.ElementRef(this._el_52),this.renderer,(null as any),'',(null as any),(null as any));
    this._text_53 = this.renderer.createText(this._el_52,'Type of execerise',(null as any));
    this._text_54 = this.renderer.createText((null as any),'\n\n       ',(null as any));
    this._el_55 = this.renderer.createElement((null as any),'ion-select',(null as any));
    this.renderer.setElementAttribute(this._el_55,'formControlName','type');
    this.renderer.setElementAttribute(this._el_55,'placeholder','Select exercise type');
    this._appEl_55 = new import3.AppElement(55,50,this,this._el_55);
    var compView_55:any = import32.viewFactory_Select0(this.viewUtils,this.injector(55),this._appEl_55);
    this._Select_55_4 = new import32.Wrapper_Select(this.parentInjector.get(import36.App),this.parentInjector.get(import42.Form),this.parentInjector.get(import34.Config),new import35.ElementRef(this._el_55),this.renderer,this._Item_50_4.context,this.parentInjector.get(import8.NavController,(null as any)));
    this._NG_VALUE_ACCESSOR_55_5 = [this._Select_55_4.context];
    this._FormControlName_55_6 = new import30.Wrapper_FormControlName(this._ControlContainer_40_4,(null as any),(null as any),this._NG_VALUE_ACCESSOR_55_5);
    this._NgControl_55_7 = this._FormControlName_55_6.context;
    this._NgControlStatus_55_8 = new import26.Wrapper_NgControlStatus(this._NgControl_55_7);
    this._query_Option_55_0 = new import28.QueryList<any>();
    this._appEl_55.initComponent(this._Select_55_4.context,([] as any[]),compView_55);
    this._text_56 = this.renderer.createText((null as any),'\n         ',(null as any));
    this._anchor_57 = this.renderer.createTemplateAnchor((null as any),(null as any));
    this._appEl_57 = new import3.AppElement(57,55,this,this._anchor_57);
    this._TemplateRef_57_5 = new import41.TemplateRef_(this._appEl_57,viewFactory_PrPage4);
    this._NgFor_57_6 = new import33.Wrapper_NgFor(this._appEl_57.vcRef,this._TemplateRef_57_5,this.parentInjector.get(import45.IterableDiffers),this.ref);
    this._text_58 = this.renderer.createText((null as any),'\n       ',(null as any));
    compView_55.create(this._Select_55_4.context,([] as any[]),(null as any));
    this._text_59 = this.renderer.createText((null as any),'\n\n    ',(null as any));
    this._query_Label_50_0.reset([this._Label_52_3.context]);
    this._Item_50_4.context.contentLabel = this._query_Label_50_0.first;
    compView_50.create(this._Item_50_4.context,[
      ([] as any[]),
      ([] as any[]).concat([this._el_52]),
      ([] as any[]).concat([
        this._text_51,
        this._text_54,
        this._text_59
      ]
      ),
      ([] as any[]).concat([this._el_55]),
      ([] as any[])
    ]
    ,(null as any));
    this._text_60 = this.renderer.createText(this._el_40,'\n\n    ',(null as any));
    this._el_61 = this.renderer.createElement(this._el_40,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_61,'class','item item-block');
    this._appEl_61 = new import3.AppElement(61,40,this,this._el_61);
    var compView_61:any = import27.viewFactory_Item0(this.viewUtils,this.injector(61),this._appEl_61);
    this._Item_61_4 = new import27.Wrapper_Item(this.parentInjector.get(import42.Form),this.parentInjector.get(import34.Config),new import35.ElementRef(this._el_61),this.renderer,this.parentInjector.get(import43.ItemReorder,(null as any)));
    this._ItemContent_61_5 = new import27.Wrapper_ItemContent();
    this._query_Label_61_0 = new import28.QueryList<any>();
    this._query_Button_61_1 = new import28.QueryList<any>();
    this._query_Icon_61_2 = new import28.QueryList<any>();
    this._appEl_61.initComponent(this._Item_61_4.context,([] as any[]),compView_61);
    this._text_62 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_63 = this.renderer.createElement((null as any),'ion-label',(null as any));
    this.renderer.setElementAttribute(this._el_63,'stacked','');
    this._Label_63_3 = new import29.Wrapper_Label(this.parentInjector.get(import34.Config),new import35.ElementRef(this._el_63),this.renderer,(null as any),'',(null as any),(null as any));
    this._text_64 = this.renderer.createText(this._el_63,'Unit of execerise',(null as any));
    this._text_65 = this.renderer.createText((null as any),'\n\n       ',(null as any));
    this._el_66 = this.renderer.createElement((null as any),'ion-select',(null as any));
    this.renderer.setElementAttribute(this._el_66,'formControlName','unit');
    this.renderer.setElementAttribute(this._el_66,'placeholder','Select exercise unit');
    this._appEl_66 = new import3.AppElement(66,61,this,this._el_66);
    var compView_66:any = import32.viewFactory_Select0(this.viewUtils,this.injector(66),this._appEl_66);
    this._Select_66_4 = new import32.Wrapper_Select(this.parentInjector.get(import36.App),this.parentInjector.get(import42.Form),this.parentInjector.get(import34.Config),new import35.ElementRef(this._el_66),this.renderer,this._Item_61_4.context,this.parentInjector.get(import8.NavController,(null as any)));
    this._NG_VALUE_ACCESSOR_66_5 = [this._Select_66_4.context];
    this._FormControlName_66_6 = new import30.Wrapper_FormControlName(this._ControlContainer_40_4,(null as any),(null as any),this._NG_VALUE_ACCESSOR_66_5);
    this._NgControl_66_7 = this._FormControlName_66_6.context;
    this._NgControlStatus_66_8 = new import26.Wrapper_NgControlStatus(this._NgControl_66_7);
    this._query_Option_66_0 = new import28.QueryList<any>();
    this._appEl_66.initComponent(this._Select_66_4.context,([] as any[]),compView_66);
    this._text_67 = this.renderer.createText((null as any),'\n         ',(null as any));
    this._anchor_68 = this.renderer.createTemplateAnchor((null as any),(null as any));
    this._appEl_68 = new import3.AppElement(68,66,this,this._anchor_68);
    this._TemplateRef_68_5 = new import41.TemplateRef_(this._appEl_68,viewFactory_PrPage5);
    this._NgFor_68_6 = new import33.Wrapper_NgFor(this._appEl_68.vcRef,this._TemplateRef_68_5,this.parentInjector.get(import45.IterableDiffers),this.ref);
    this._text_69 = this.renderer.createText((null as any),'\n       ',(null as any));
    compView_66.create(this._Select_66_4.context,([] as any[]),(null as any));
    this._text_70 = this.renderer.createText((null as any),'\n\n    ',(null as any));
    this._query_Label_61_0.reset([this._Label_63_3.context]);
    this._Item_61_4.context.contentLabel = this._query_Label_61_0.first;
    compView_61.create(this._Item_61_4.context,[
      ([] as any[]),
      ([] as any[]).concat([this._el_63]),
      ([] as any[]).concat([
        this._text_62,
        this._text_65,
        this._text_70
      ]
      ),
      ([] as any[]).concat([this._el_66]),
      ([] as any[])
    ]
    ,(null as any));
    this._text_71 = this.renderer.createText(this._el_40,'\n\n    ',(null as any));
    this._el_72 = this.renderer.createElement(this._el_40,'button',(null as any));
    this.renderer.setElementAttribute(this._el_72,'block','');
    this.renderer.setElementAttribute(this._el_72,'ion-button','');
    this.renderer.setElementAttribute(this._el_72,'type','submit');
    this._appEl_72 = new import3.AppElement(72,40,this,this._el_72);
    var compView_72:any = import19.viewFactory_Button0(this.viewUtils,this.injector(72),this._appEl_72);
    this._Button_72_4 = new import19.Wrapper_Button((null as any),'',this.parentInjector.get(import34.Config),new import35.ElementRef(this._el_72),this.renderer);
    this._appEl_72.initComponent(this._Button_72_4.context,([] as any[]),compView_72);
    this._text_73 = this.renderer.createText((null as any),'\n      Update Pr value\n    ',(null as any));
    compView_72.create(this._Button_72_4.context,[([] as any[]).concat([this._text_73])],(null as any));
    this._text_74 = this.renderer.createText(this._el_40,'\n\n  ',(null as any));
    this._text_75 = this.renderer.createText((null as any),'\n\n',(null as any));
    compView_14.create(this._Content_14_4.context,[
      ([] as any[]),
      ([] as any[]).concat([
        this._text_15,
        this._el_16,
        this._text_39,
        this._el_40,
        this._text_75
      ]
      ),
      ([] as any[])
    ]
    ,(null as any));
    this._text_76 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this._expr_1 = import7.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_4,'click',this.eventHandler(this._handle_click_4_0.bind(this)));
    this._expr_5 = import7.UNINITIALIZED;
    this._expr_6 = import7.UNINITIALIZED;
    this._expr_7 = import7.UNINITIALIZED;
    this._expr_8 = import7.UNINITIALIZED;
    this._expr_12 = import7.UNINITIALIZED;
    this._expr_13 = import7.UNINITIALIZED;
    var disposable_1:Function = this.renderer.listen(this._el_40,'submit',this.eventHandler(this._handle_submit_40_0.bind(this)));
    var disposable_2:Function = this.renderer.listen(this._el_40,'reset',this.eventHandler(this._handle_reset_40_1.bind(this)));
    this._expr_18 = import7.UNINITIALIZED;
    this._expr_19 = import7.UNINITIALIZED;
    this._expr_20 = import7.UNINITIALIZED;
    this._expr_21 = import7.UNINITIALIZED;
    this._expr_22 = import7.UNINITIALIZED;
    this._expr_23 = import7.UNINITIALIZED;
    this._expr_24 = import7.UNINITIALIZED;
    this._expr_26 = import7.UNINITIALIZED;
    this._expr_27 = import7.UNINITIALIZED;
    this._expr_28 = import7.UNINITIALIZED;
    this._expr_29 = import7.UNINITIALIZED;
    this._expr_30 = import7.UNINITIALIZED;
    this._expr_31 = import7.UNINITIALIZED;
    var disposable_3:Function = this.renderer.listen(this._el_55,'ngModelChange',this.eventHandler(this._handle_ngModelChange_55_0.bind(this)));
    var disposable_4:Function = this.renderer.listen(this._el_55,'click',this.eventHandler(this._handle_click_55_1.bind(this)));
    var disposable_5:Function = this.renderer.listen(this._el_55,'keyup.space',this.eventHandler(this._handle_keyup_space_55_2.bind(this)));
    this._expr_38 = import7.UNINITIALIZED;
    const subscription_0:any = this._FormControlName_55_6.context.update.subscribe(this.eventHandler(this._handle_ngModelChange_55_0.bind(this)));
    this._expr_41 = import7.UNINITIALIZED;
    this._expr_42 = import7.UNINITIALIZED;
    this._expr_43 = import7.UNINITIALIZED;
    this._expr_44 = import7.UNINITIALIZED;
    this._expr_45 = import7.UNINITIALIZED;
    this._expr_46 = import7.UNINITIALIZED;
    var disposable_6:Function = this.renderer.listen(this._el_66,'ngModelChange',this.eventHandler(this._handle_ngModelChange_66_0.bind(this)));
    var disposable_7:Function = this.renderer.listen(this._el_66,'click',this.eventHandler(this._handle_click_66_1.bind(this)));
    var disposable_8:Function = this.renderer.listen(this._el_66,'keyup.space',this.eventHandler(this._handle_keyup_space_66_2.bind(this)));
    this._expr_52 = import7.UNINITIALIZED;
    const subscription_1:any = this._FormControlName_66_6.context.update.subscribe(this.eventHandler(this._handle_ngModelChange_66_0.bind(this)));
    this._expr_55 = import7.UNINITIALIZED;
    this._expr_56 = import7.UNINITIALIZED;
    this._expr_57 = import7.UNINITIALIZED;
    this._expr_58 = import7.UNINITIALIZED;
    this._expr_59 = import7.UNINITIALIZED;
    this._expr_60 = import7.UNINITIALIZED;
    this.init(([] as any[]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._text_11,
      this._text_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._el_16,
      this._text_17,
      this._el_18,
      this._text_19,
      this._text_20,
      this._el_21,
      this._text_22,
      this._el_23,
      this._text_24,
      this._anchor_25,
      this._text_26,
      this._anchor_27,
      this._text_28,
      this._anchor_29,
      this._text_30,
      this._text_31,
      this._el_32,
      this._text_33,
      this._text_34,
      this._el_35,
      this._text_36,
      this._text_37,
      this._text_38,
      this._text_39,
      this._el_40,
      this._text_41,
      this._el_42,
      this._text_43,
      this._el_44,
      this._text_45,
      this._text_46,
      this._el_47,
      this._text_48,
      this._text_49,
      this._el_50,
      this._text_51,
      this._el_52,
      this._text_53,
      this._text_54,
      this._el_55,
      this._text_56,
      this._anchor_57,
      this._text_58,
      this._text_59,
      this._text_60,
      this._el_61,
      this._text_62,
      this._el_63,
      this._text_64,
      this._text_65,
      this._el_66,
      this._text_67,
      this._anchor_68,
      this._text_69,
      this._text_70,
      this._text_71,
      this._el_72,
      this._text_73,
      this._text_74,
      this._text_75,
      this._text_76
    ]
    ,[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3,
      disposable_4,
      disposable_5,
      disposable_6,
      disposable_7,
      disposable_8
    ]
    ,[
      subscription_0,
      subscription_1
    ]
    );
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import46.Icon) && (6 === requestNodeIndex))) { return this._Icon_6_3.context; }
    if (((token === import47.Button) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._Button_4_4.context; }
    if (((token === import48.ToolbarTitle) && ((9 <= requestNodeIndex) && (requestNodeIndex <= 10)))) { return this._ToolbarTitle_9_4.context; }
    if (((token === import49.Navbar) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 11)))) { return this._Navbar_2_4.context; }
    if (((token === import37.Header) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 12)))) { return this._Header_0_3.context; }
    if (((token === import50.CardHeader) && ((18 <= requestNodeIndex) && (requestNodeIndex <= 19)))) { return this._CardHeader_18_3.context; }
    if (((token === import41.TemplateRef) && (25 === requestNodeIndex))) { return this._TemplateRef_25_5; }
    if (((token === import51.NgIf) && (25 === requestNodeIndex))) { return this._NgIf_25_6.context; }
    if (((token === import41.TemplateRef) && (27 === requestNodeIndex))) { return this._TemplateRef_27_5; }
    if (((token === import51.NgIf) && (27 === requestNodeIndex))) { return this._NgIf_27_6.context; }
    if (((token === import41.TemplateRef) && (29 === requestNodeIndex))) { return this._TemplateRef_29_5; }
    if (((token === import51.NgIf) && (29 === requestNodeIndex))) { return this._NgIf_29_6.context; }
    if (((token === import50.CardContent) && ((21 <= requestNodeIndex) && (requestNodeIndex <= 37)))) { return this._CardContent_21_3.context; }
    if (((token === import50.Card) && ((16 <= requestNodeIndex) && (requestNodeIndex <= 38)))) { return this._Card_16_3.context; }
    if (((token === import52.Label) && ((44 <= requestNodeIndex) && (requestNodeIndex <= 45)))) { return this._Label_44_3.context; }
    if (((token === import53.FormControlName) && (47 === requestNodeIndex))) { return this._FormControlName_47_4.context; }
    if (((token === import54.NgControl) && (47 === requestNodeIndex))) { return this._NgControl_47_5; }
    if (((token === import55.NgControlStatus) && (47 === requestNodeIndex))) { return this._NgControlStatus_47_6.context; }
    if (((token === import56.TextInput) && (47 === requestNodeIndex))) { return this._TextInput_47_7.context; }
    if (((token === import57.Item) && ((42 <= requestNodeIndex) && (requestNodeIndex <= 48)))) { return this._Item_42_4.context; }
    if (((token === import57.ItemContent) && ((42 <= requestNodeIndex) && (requestNodeIndex <= 48)))) { return this._ItemContent_42_5.context; }
    if (((token === import52.Label) && ((52 <= requestNodeIndex) && (requestNodeIndex <= 53)))) { return this._Label_52_3.context; }
    if (((token === import41.TemplateRef) && (57 === requestNodeIndex))) { return this._TemplateRef_57_5; }
    if (((token === import58.NgFor) && (57 === requestNodeIndex))) { return this._NgFor_57_6.context; }
    if (((token === import59.Select) && ((55 <= requestNodeIndex) && (requestNodeIndex <= 58)))) { return this._Select_55_4.context; }
    if (((token === import60.NG_VALUE_ACCESSOR) && ((55 <= requestNodeIndex) && (requestNodeIndex <= 58)))) { return this._NG_VALUE_ACCESSOR_55_5; }
    if (((token === import53.FormControlName) && ((55 <= requestNodeIndex) && (requestNodeIndex <= 58)))) { return this._FormControlName_55_6.context; }
    if (((token === import54.NgControl) && ((55 <= requestNodeIndex) && (requestNodeIndex <= 58)))) { return this._NgControl_55_7; }
    if (((token === import55.NgControlStatus) && ((55 <= requestNodeIndex) && (requestNodeIndex <= 58)))) { return this._NgControlStatus_55_8.context; }
    if (((token === import57.Item) && ((50 <= requestNodeIndex) && (requestNodeIndex <= 59)))) { return this._Item_50_4.context; }
    if (((token === import57.ItemContent) && ((50 <= requestNodeIndex) && (requestNodeIndex <= 59)))) { return this._ItemContent_50_5.context; }
    if (((token === import52.Label) && ((63 <= requestNodeIndex) && (requestNodeIndex <= 64)))) { return this._Label_63_3.context; }
    if (((token === import41.TemplateRef) && (68 === requestNodeIndex))) { return this._TemplateRef_68_5; }
    if (((token === import58.NgFor) && (68 === requestNodeIndex))) { return this._NgFor_68_6.context; }
    if (((token === import59.Select) && ((66 <= requestNodeIndex) && (requestNodeIndex <= 69)))) { return this._Select_66_4.context; }
    if (((token === import60.NG_VALUE_ACCESSOR) && ((66 <= requestNodeIndex) && (requestNodeIndex <= 69)))) { return this._NG_VALUE_ACCESSOR_66_5; }
    if (((token === import53.FormControlName) && ((66 <= requestNodeIndex) && (requestNodeIndex <= 69)))) { return this._FormControlName_66_6.context; }
    if (((token === import54.NgControl) && ((66 <= requestNodeIndex) && (requestNodeIndex <= 69)))) { return this._NgControl_66_7; }
    if (((token === import55.NgControlStatus) && ((66 <= requestNodeIndex) && (requestNodeIndex <= 69)))) { return this._NgControlStatus_66_8.context; }
    if (((token === import57.Item) && ((61 <= requestNodeIndex) && (requestNodeIndex <= 70)))) { return this._Item_61_4.context; }
    if (((token === import57.ItemContent) && ((61 <= requestNodeIndex) && (requestNodeIndex <= 70)))) { return this._ItemContent_61_5.context; }
    if (((token === import47.Button) && ((72 <= requestNodeIndex) && (requestNodeIndex <= 73)))) { return this._Button_72_4.context; }
    if (((token === import61.FormGroupDirective) && ((40 <= requestNodeIndex) && (requestNodeIndex <= 74)))) { return this._FormGroupDirective_40_3.context; }
    if (((token === import62.ControlContainer) && ((40 <= requestNodeIndex) && (requestNodeIndex <= 74)))) { return this._ControlContainer_40_4; }
    if (((token === import55.NgControlStatusGroup) && ((40 <= requestNodeIndex) && (requestNodeIndex <= 74)))) { return this._NgControlStatusGroup_40_5.context; }
    if (((token === import63.Content) && ((14 <= requestNodeIndex) && (requestNodeIndex <= 75)))) { return this._Content_14_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._Header_0_3.detectChangesInternal(this,this._el_0,throwOnChange);
    this._Navbar_2_4.detectChangesInternal(this,this._el_2,throwOnChange);
    const currVal_3:any = '';
    this._Button_4_4.check_clear(currVal_3,throwOnChange,false);
    if (this._Button_4_4.detectChangesInternal(this,this._el_4,throwOnChange)) { this._appEl_4.componentView.markAsCheckOnce(); }
    const currVal_4:any = 'md-arrow-back';
    this._Icon_6_3.check_name(currVal_4,throwOnChange,false);
    this._Icon_6_3.detectChangesInternal(this,this._el_6,throwOnChange);
    if (this._ToolbarTitle_9_4.detectChangesInternal(this,this._el_9,throwOnChange)) { this._appEl_9.componentView.markAsCheckOnce(); }
    if (this._Content_14_4.detectChangesInternal(this,this._el_14,throwOnChange)) { this._appEl_14.componentView.markAsCheckOnce(); }
    this._Card_16_3.detectChangesInternal(this,this._el_16,throwOnChange);
    this._CardHeader_18_3.detectChangesInternal(this,this._el_18,throwOnChange);
    this._CardContent_21_3.detectChangesInternal(this,this._el_21,throwOnChange);
    const currVal_9:any = (this.context.exercise.Unit === 'Kg');
    this._NgIf_25_6.check_ngIf(currVal_9,throwOnChange,false);
    this._NgIf_25_6.detectChangesInternal(this,this._anchor_25,throwOnChange);
    const currVal_10:any = (this.context.exercise.Unit === 'Time');
    this._NgIf_27_6.check_ngIf(currVal_10,throwOnChange,false);
    this._NgIf_27_6.detectChangesInternal(this,this._anchor_27,throwOnChange);
    const currVal_11:any = (this.context.exercise.Unit === 'Reps');
    this._NgIf_29_6.check_ngIf(currVal_11,throwOnChange,false);
    this._NgIf_29_6.detectChangesInternal(this,this._anchor_29,throwOnChange);
    const currVal_17:any = this.context.newPrForm;
    this._FormGroupDirective_40_3.check_form(currVal_17,throwOnChange,false);
    this._FormGroupDirective_40_3.detectChangesInternal(this,this._el_40,throwOnChange);
    this._NgControlStatusGroup_40_5.detectChangesInternal(this,this._el_40,throwOnChange);
    if (this._Item_42_4.detectChangesInternal(this,this._el_42,throwOnChange)) { this._appEl_42.componentView.markAsCheckOnce(); }
    this._ItemContent_42_5.detectChangesInternal(this,this._el_42,throwOnChange);
    this._Label_44_3.detectChangesInternal(this,this._el_44,throwOnChange);
    const currVal_25:any = 'pr';
    this._FormControlName_47_4.check_name(currVal_25,throwOnChange,false);
    this._FormControlName_47_4.detectChangesInternal(this,this._el_47,throwOnChange);
    this._NgControlStatus_47_6.detectChangesInternal(this,this._el_47,throwOnChange);
    const currVal_32:any = 'Enter new value';
    this._TextInput_47_7.check_placeholder(currVal_32,throwOnChange,false);
    const currVal_33:any = 'pr';
    this._TextInput_47_7.check_type(currVal_33,throwOnChange,false);
    this._TextInput_47_7.detectChangesInternal(this,this._el_47,throwOnChange);
    if (this._Item_50_4.detectChangesInternal(this,this._el_50,throwOnChange)) { this._appEl_50.componentView.markAsCheckOnce(); }
    this._ItemContent_50_5.detectChangesInternal(this,this._el_50,throwOnChange);
    this._Label_52_3.detectChangesInternal(this,this._el_52,throwOnChange);
    const currVal_37:any = 'Select exercise type';
    this._Select_55_4.check_placeholder(currVal_37,throwOnChange,false);
    this._Select_55_4.detectChangesInternal(this,this._el_55,throwOnChange);
    const currVal_39:any = 'type';
    this._FormControlName_55_6.check_name(currVal_39,throwOnChange,false);
    const currVal_40:any = this.context.selected.type;
    this._FormControlName_55_6.check_model(currVal_40,throwOnChange,false);
    this._FormControlName_55_6.detectChangesInternal(this,this._el_55,throwOnChange);
    this._NgControlStatus_55_8.detectChangesInternal(this,this._el_55,throwOnChange);
    const currVal_47:any = this.context.types;
    this._NgFor_57_6.check_ngForOf(currVal_47,throwOnChange,false);
    this._NgFor_57_6.detectChangesInternal(this,this._anchor_57,throwOnChange);
    if (this._Item_61_4.detectChangesInternal(this,this._el_61,throwOnChange)) { this._appEl_61.componentView.markAsCheckOnce(); }
    this._ItemContent_61_5.detectChangesInternal(this,this._el_61,throwOnChange);
    this._Label_63_3.detectChangesInternal(this,this._el_63,throwOnChange);
    const currVal_51:any = 'Select exercise unit';
    this._Select_66_4.check_placeholder(currVal_51,throwOnChange,false);
    this._Select_66_4.detectChangesInternal(this,this._el_66,throwOnChange);
    const currVal_53:any = 'unit';
    this._FormControlName_66_6.check_name(currVal_53,throwOnChange,false);
    const currVal_54:any = this.context.selected.unit;
    this._FormControlName_66_6.check_model(currVal_54,throwOnChange,false);
    this._FormControlName_66_6.detectChangesInternal(this,this._el_66,throwOnChange);
    this._NgControlStatus_66_8.detectChangesInternal(this,this._el_66,throwOnChange);
    const currVal_61:any = this.context.units;
    this._NgFor_68_6.check_ngForOf(currVal_61,throwOnChange,false);
    this._NgFor_68_6.detectChangesInternal(this,this._anchor_68,throwOnChange);
    const currVal_62:any = '';
    this._Button_72_4.check_block(currVal_62,throwOnChange,false);
    if (this._Button_72_4.detectChangesInternal(this,this._el_72,throwOnChange)) { this._appEl_72.componentView.markAsCheckOnce(); }
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_42_1.dirty) {
        this._query_Button_42_1.reset(([] as any[]));
        this._Item_42_4.context._buttons = this._query_Button_42_1;
        this._query_Button_42_1.notifyOnChanges();
      }
      if (this._query_Icon_42_2.dirty) {
        this._query_Icon_42_2.reset(([] as any[]));
        this._Item_42_4.context._icons = this._query_Icon_42_2;
        this._query_Icon_42_2.notifyOnChanges();
      }
      if (this._query_Option_55_0.dirty) {
          this._query_Option_55_0.reset([this._appEl_57.mapNestedViews(_View_PrPage4,(nestedView:_View_PrPage4):any => {
            return [nestedView._Option_0_3.context];
        })]);
        this._Select_55_4.context.options = this._query_Option_55_0;
        this._query_Option_55_0.notifyOnChanges();
      }
      if (this._query_Button_50_1.dirty) {
        this._query_Button_50_1.reset(([] as any[]));
        this._Item_50_4.context._buttons = this._query_Button_50_1;
        this._query_Button_50_1.notifyOnChanges();
      }
      if (this._query_Icon_50_2.dirty) {
        this._query_Icon_50_2.reset(([] as any[]));
        this._Item_50_4.context._icons = this._query_Icon_50_2;
        this._query_Icon_50_2.notifyOnChanges();
      }
      if (this._query_Option_66_0.dirty) {
          this._query_Option_66_0.reset([this._appEl_68.mapNestedViews(_View_PrPage5,(nestedView:_View_PrPage5):any => {
            return [nestedView._Option_0_3.context];
        })]);
        this._Select_66_4.context.options = this._query_Option_66_0;
        this._query_Option_66_0.notifyOnChanges();
      }
      if (this._query_Button_61_1.dirty) {
        this._query_Button_61_1.reset(([] as any[]));
        this._Item_61_4.context._buttons = this._query_Button_61_1;
        this._query_Button_61_1.notifyOnChanges();
      }
      if (this._query_Icon_61_2.dirty) {
        this._query_Icon_61_2.reset(([] as any[]));
        this._Item_61_4.context._icons = this._query_Icon_61_2;
        this._query_Icon_61_2.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._Button_4_4.context.ngAfterContentInit(); }
      this._TextInput_47_7.context.ngAfterContentChecked();
      if ((this.numberOfChecks === 0)) { this._Item_42_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Select_55_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_50_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Select_66_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_61_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Button_72_4.context.ngAfterContentInit(); }
    }
    const currVal_0:any = this._Navbar_2_4.context._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setElementProperty(this._el_2,'hidden',currVal_0);
      this._expr_0 = currVal_0;
    }
    const currVal_1:any = this._Navbar_2_4.context._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementClass(this._el_2,'statusbar-padding',currVal_1);
      this._expr_1 = currVal_1;
    }
    const currVal_5:any = this._Icon_6_3.context._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this.renderer.setElementClass(this._el_6,'hide',currVal_5);
      this._expr_5 = currVal_5;
    }
    const currVal_6:any = import4.interpolate(1,'PR - ',this.context.exercise.Name,'');
    if (import4.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this.renderer.setText(this._text_10,currVal_6);
      this._expr_6 = currVal_6;
    }
    const currVal_7:any = this._Content_14_4.context._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this.renderer.setElementClass(this._el_14,'statusbar-padding',currVal_7);
      this._expr_7 = currVal_7;
    }
    const currVal_8:any = import4.interpolate(1,'',this.context.exercise.Pr,'\n        ');
    if (import4.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this.renderer.setText(this._text_24,currVal_8);
      this._expr_8 = currVal_8;
    }
    const currVal_12:any = import4.interpolate(1,'',this.context.exercise.name,'');
    if (import4.checkBinding(throwOnChange,this._expr_12,currVal_12)) {
      this.renderer.setText(this._text_33,currVal_12);
      this._expr_12 = currVal_12;
    }
    const currVal_13:any = import4.interpolate(1,'',this.context.exercise.Date,'');
    if (import4.checkBinding(throwOnChange,this._expr_13,currVal_13)) {
      this.renderer.setText(this._text_36,currVal_13);
      this._expr_13 = currVal_13;
    }
    const currVal_18:any = this._NgControlStatusGroup_40_5.context.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_18,currVal_18)) {
      this.renderer.setElementClass(this._el_40,'ng-untouched',currVal_18);
      this._expr_18 = currVal_18;
    }
    const currVal_19:any = this._NgControlStatusGroup_40_5.context.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_19,currVal_19)) {
      this.renderer.setElementClass(this._el_40,'ng-touched',currVal_19);
      this._expr_19 = currVal_19;
    }
    const currVal_20:any = this._NgControlStatusGroup_40_5.context.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_20,currVal_20)) {
      this.renderer.setElementClass(this._el_40,'ng-pristine',currVal_20);
      this._expr_20 = currVal_20;
    }
    const currVal_21:any = this._NgControlStatusGroup_40_5.context.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_21,currVal_21)) {
      this.renderer.setElementClass(this._el_40,'ng-dirty',currVal_21);
      this._expr_21 = currVal_21;
    }
    const currVal_22:any = this._NgControlStatusGroup_40_5.context.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_22,currVal_22)) {
      this.renderer.setElementClass(this._el_40,'ng-valid',currVal_22);
      this._expr_22 = currVal_22;
    }
    const currVal_23:any = this._NgControlStatusGroup_40_5.context.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_23,currVal_23)) {
      this.renderer.setElementClass(this._el_40,'ng-invalid',currVal_23);
      this._expr_23 = currVal_23;
    }
    const currVal_24:any = import4.interpolate(1,'Nuevo Pr - ',this.context.exercise.name,'');
    if (import4.checkBinding(throwOnChange,this._expr_24,currVal_24)) {
      this.renderer.setText(this._text_45,currVal_24);
      this._expr_24 = currVal_24;
    }
    const currVal_26:any = this._NgControlStatus_47_6.context.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_26,currVal_26)) {
      this.renderer.setElementClass(this._el_47,'ng-untouched',currVal_26);
      this._expr_26 = currVal_26;
    }
    const currVal_27:any = this._NgControlStatus_47_6.context.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_27,currVal_27)) {
      this.renderer.setElementClass(this._el_47,'ng-touched',currVal_27);
      this._expr_27 = currVal_27;
    }
    const currVal_28:any = this._NgControlStatus_47_6.context.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_28,currVal_28)) {
      this.renderer.setElementClass(this._el_47,'ng-pristine',currVal_28);
      this._expr_28 = currVal_28;
    }
    const currVal_29:any = this._NgControlStatus_47_6.context.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_29,currVal_29)) {
      this.renderer.setElementClass(this._el_47,'ng-dirty',currVal_29);
      this._expr_29 = currVal_29;
    }
    const currVal_30:any = this._NgControlStatus_47_6.context.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_30,currVal_30)) {
      this.renderer.setElementClass(this._el_47,'ng-valid',currVal_30);
      this._expr_30 = currVal_30;
    }
    const currVal_31:any = this._NgControlStatus_47_6.context.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_31,currVal_31)) {
      this.renderer.setElementClass(this._el_47,'ng-invalid',currVal_31);
      this._expr_31 = currVal_31;
    }
    const currVal_38:any = this._Select_55_4.context._disabled;
    if (import4.checkBinding(throwOnChange,this._expr_38,currVal_38)) {
      this.renderer.setElementClass(this._el_55,'select-disabled',currVal_38);
      this._expr_38 = currVal_38;
    }
    const currVal_41:any = this._NgControlStatus_55_8.context.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_41,currVal_41)) {
      this.renderer.setElementClass(this._el_55,'ng-untouched',currVal_41);
      this._expr_41 = currVal_41;
    }
    const currVal_42:any = this._NgControlStatus_55_8.context.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_42,currVal_42)) {
      this.renderer.setElementClass(this._el_55,'ng-touched',currVal_42);
      this._expr_42 = currVal_42;
    }
    const currVal_43:any = this._NgControlStatus_55_8.context.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_43,currVal_43)) {
      this.renderer.setElementClass(this._el_55,'ng-pristine',currVal_43);
      this._expr_43 = currVal_43;
    }
    const currVal_44:any = this._NgControlStatus_55_8.context.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_44,currVal_44)) {
      this.renderer.setElementClass(this._el_55,'ng-dirty',currVal_44);
      this._expr_44 = currVal_44;
    }
    const currVal_45:any = this._NgControlStatus_55_8.context.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_45,currVal_45)) {
      this.renderer.setElementClass(this._el_55,'ng-valid',currVal_45);
      this._expr_45 = currVal_45;
    }
    const currVal_46:any = this._NgControlStatus_55_8.context.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_46,currVal_46)) {
      this.renderer.setElementClass(this._el_55,'ng-invalid',currVal_46);
      this._expr_46 = currVal_46;
    }
    const currVal_52:any = this._Select_66_4.context._disabled;
    if (import4.checkBinding(throwOnChange,this._expr_52,currVal_52)) {
      this.renderer.setElementClass(this._el_66,'select-disabled',currVal_52);
      this._expr_52 = currVal_52;
    }
    const currVal_55:any = this._NgControlStatus_66_8.context.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_55,currVal_55)) {
      this.renderer.setElementClass(this._el_66,'ng-untouched',currVal_55);
      this._expr_55 = currVal_55;
    }
    const currVal_56:any = this._NgControlStatus_66_8.context.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_56,currVal_56)) {
      this.renderer.setElementClass(this._el_66,'ng-touched',currVal_56);
      this._expr_56 = currVal_56;
    }
    const currVal_57:any = this._NgControlStatus_66_8.context.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_57,currVal_57)) {
      this.renderer.setElementClass(this._el_66,'ng-pristine',currVal_57);
      this._expr_57 = currVal_57;
    }
    const currVal_58:any = this._NgControlStatus_66_8.context.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_58,currVal_58)) {
      this.renderer.setElementClass(this._el_66,'ng-dirty',currVal_58);
      this._expr_58 = currVal_58;
    }
    const currVal_59:any = this._NgControlStatus_66_8.context.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_59,currVal_59)) {
      this.renderer.setElementClass(this._el_66,'ng-valid',currVal_59);
      this._expr_59 = currVal_59;
    }
    const currVal_60:any = this._NgControlStatus_66_8.context.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_60,currVal_60)) {
      this.renderer.setElementClass(this._el_66,'ng-invalid',currVal_60);
      this._expr_60 = currVal_60;
    }
    this.detectViewChildrenChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._Navbar_2_4.context.ngAfterViewInit(); } }
  }
  destroyInternal():void {
    this._Icon_6_3.context.ngOnDestroy();
    this._FormControlName_47_4.context.ngOnDestroy();
    this._TextInput_47_7.context.ngOnDestroy();
    this._Select_55_4.context.ngOnDestroy();
    this._FormControlName_55_6.context.ngOnDestroy();
    this._Select_66_4.context.ngOnDestroy();
    this._FormControlName_66_6.context.ngOnDestroy();
    this._Content_14_4.context.ngOnDestroy();
  }
  private _handle_click_4_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.dismiss()) !== false);
    return (true && pd_0);
  }
  private _handle_submit_40_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.updatePr(this.context.exercise.id)) !== false);
    const pd_1:any = ((<any>this._FormGroupDirective_40_3.context.onSubmit($event)) !== false);
    return ((true && pd_0) && pd_1);
  }
  private _handle_reset_40_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._FormGroupDirective_40_3.context.onReset()) !== false);
    return (true && pd_0);
  }
  private _handle_ngModelChange_55_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>(this.context.selected.type = $event)) !== false);
    return (true && pd_0);
  }
  private _handle_click_55_1($event:any):boolean {
    this._appEl_55.componentView.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._Select_55_4.context._click($event)) !== false);
    return (true && pd_0);
  }
  private _handle_keyup_space_55_2($event:any):boolean {
    this._appEl_55.componentView.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._Select_55_4.context._keyup()) !== false);
    return (true && pd_0);
  }
  private _handle_ngModelChange_66_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>(this.context.selected.unit = $event)) !== false);
    return (true && pd_0);
  }
  private _handle_click_66_1($event:any):boolean {
    this._appEl_66.componentView.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._Select_66_4.context._click($event)) !== false);
    return (true && pd_0);
  }
  private _handle_keyup_space_66_2($event:any):boolean {
    this._appEl_66.componentView.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._Select_66_4.context._keyup()) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_PrPage0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<import0.PrPage> {
  if ((renderType_PrPage === (null as any))) { (renderType_PrPage = viewUtils.createRenderComponentType('',0,import15.ViewEncapsulation.None,styles_PrPage,{})); }
  return new _View_PrPage0(viewUtils,parentInjector,declarationEl);
}
class _View_PrPage1 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_PrPage1,renderType_PrPage,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'span',(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'Kg',(null as any));
    this.init(([] as any[]).concat([this._el_0]),[
      this._el_0,
      this._text_1
    ]
    ,([] as any[]),([] as any[]));
    return (null as any);
  }
}
function viewFactory_PrPage1(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  return new _View_PrPage1(viewUtils,parentInjector,declarationEl);
}
class _View_PrPage2 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_PrPage2,renderType_PrPage,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'span',(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'Min',(null as any));
    this.init(([] as any[]).concat([this._el_0]),[
      this._el_0,
      this._text_1
    ]
    ,([] as any[]),([] as any[]));
    return (null as any);
  }
}
function viewFactory_PrPage2(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  return new _View_PrPage2(viewUtils,parentInjector,declarationEl);
}
class _View_PrPage3 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_PrPage3,renderType_PrPage,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'span',(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'Reps',(null as any));
    this.init(([] as any[]).concat([this._el_0]),[
      this._el_0,
      this._text_1
    ]
    ,([] as any[]),([] as any[]));
    return (null as any);
  }
}
function viewFactory_PrPage3(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  return new _View_PrPage3(viewUtils,parentInjector,declarationEl);
}
class _View_PrPage4 extends import1.AppView<any> {
  _el_0:any;
  _Option_0_3:import64.Wrapper_Option;
  _text_1:any;
  /*private*/ _expr_0:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_PrPage4,renderType_PrPage,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'ion-option',(null as any));
    this._Option_0_3 = new import64.Wrapper_Option(new import35.ElementRef(this._el_0));
    this._text_1 = this.renderer.createText(this._el_0,'',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this.init(([] as any[]).concat([this._el_0]),[
      this._el_0,
      this._text_1
    ]
    ,([] as any[]),([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import65.Option) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 1)))) { return this._Option_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._Option_0_3.detectChangesInternal(this,this._el_0,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_0:any = import4.interpolate(1,'',this.context.$implicit,'');
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setText(this._text_1,currVal_0);
      this._expr_0 = currVal_0;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  dirtyParentQueriesInternal():void {
    (<_View_PrPage0>this.parent)._query_Option_55_0.setDirty();
  }
}
function viewFactory_PrPage4(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  return new _View_PrPage4(viewUtils,parentInjector,declarationEl);
}
class _View_PrPage5 extends import1.AppView<any> {
  _el_0:any;
  _Option_0_3:import64.Wrapper_Option;
  _text_1:any;
  /*private*/ _expr_0:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_PrPage5,renderType_PrPage,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'ion-option',(null as any));
    this._Option_0_3 = new import64.Wrapper_Option(new import35.ElementRef(this._el_0));
    this._text_1 = this.renderer.createText(this._el_0,'',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this.init(([] as any[]).concat([this._el_0]),[
      this._el_0,
      this._text_1
    ]
    ,([] as any[]),([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import65.Option) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 1)))) { return this._Option_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._Option_0_3.detectChangesInternal(this,this._el_0,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_0:any = import4.interpolate(1,'',this.context.$implicit,'');
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setText(this._text_1,currVal_0);
      this._expr_0 = currVal_0;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  dirtyParentQueriesInternal():void {
    (<_View_PrPage0>this.parent)._query_Option_66_0.setDirty();
  }
}
function viewFactory_PrPage5(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  return new _View_PrPage5(viewUtils,parentInjector,declarationEl);
}