/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from './addexercise';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/element';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from 'ionic-angular/navigation/nav-controller';
import * as import9 from '@angular/forms/src/form_builder';
import * as import10 from 'ionic-angular/components/loading/loading';
import * as import11 from '../../providers/exercise-data';
import * as import12 from 'ionic-angular/components/alert/alert';
import * as import13 from '@angular/core/src/metadata/view';
import * as import14 from '@angular/core/src/linker/component_factory';
import * as import15 from '../../node_modules/ionic-angular/components/toolbar/toolbar.ngfactory';
import * as import16 from '../../node_modules/ionic-angular/components/navbar/navbar.ngfactory';
import * as import17 from '../../node_modules/ionic-angular/components/toolbar/toolbar-title.ngfactory';
import * as import18 from '../../node_modules/ionic-angular/components/content/content.ngfactory';
import * as import19 from '../../node_modules/@angular/forms/src/directives/reactive_directives/form_group_directive.ngfactory';
import * as import20 from '../../node_modules/@angular/forms/src/directives/ng_control_status.ngfactory';
import * as import21 from '../../node_modules/ionic-angular/components/item/item.ngfactory';
import * as import22 from '@angular/core/src/linker/query_list';
import * as import23 from '../../node_modules/ionic-angular/components/label/label.ngfactory';
import * as import24 from '../../node_modules/@angular/forms/src/directives/reactive_directives/form_control_name.ngfactory';
import * as import25 from '../../node_modules/ionic-angular/components/input/input.ngfactory';
import * as import26 from '../../node_modules/ionic-angular/components/select/select.ngfactory';
import * as import27 from '../../node_modules/@angular/common/src/directives/ng_for.ngfactory';
import * as import28 from '../../node_modules/ionic-angular/components/button/button.ngfactory';
import * as import29 from 'ionic-angular/config/config';
import * as import30 from '@angular/core/src/linker/element_ref';
import * as import31 from 'ionic-angular/navigation/view-controller';
import * as import32 from 'ionic-angular/components/app/app';
import * as import33 from 'ionic-angular/components/toolbar/toolbar';
import * as import34 from 'ionic-angular/util/keyboard';
import * as import35 from '@angular/core/src/zone/ng_zone';
import * as import36 from 'ionic-angular/components/tabs/tabs';
import * as import37 from 'ionic-angular/util/form';
import * as import38 from 'ionic-angular/components/item/item-reorder';
import * as import39 from 'ionic-angular/platform/platform';
import * as import40 from '@angular/core/src/linker/template_ref';
import * as import41 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import42 from 'ionic-angular/components/toolbar/toolbar-title';
import * as import43 from 'ionic-angular/components/navbar/navbar';
import * as import44 from 'ionic-angular/components/label/label';
import * as import45 from '@angular/forms/src/directives/reactive_directives/form_control_name';
import * as import46 from '@angular/forms/src/directives/ng_control';
import * as import47 from '@angular/forms/src/directives/ng_control_status';
import * as import48 from 'ionic-angular/components/input/input';
import * as import49 from 'ionic-angular/components/item/item';
import * as import50 from '@angular/common/src/directives/ng_for';
import * as import51 from 'ionic-angular/components/select/select';
import * as import52 from '@angular/forms/src/directives/control_value_accessor';
import * as import53 from 'ionic-angular/components/button/button';
import * as import54 from '@angular/forms/src/directives/reactive_directives/form_group_directive';
import * as import55 from '@angular/forms/src/directives/control_container';
import * as import56 from 'ionic-angular/components/content/content';
import * as import57 from '../../node_modules/ionic-angular/components/option/option.ngfactory';
import * as import58 from 'ionic-angular/components/option/option';
export class Wrapper_AddexercisePage {
  context:import0.AddexercisePage;
  changed:boolean;
  constructor(p0:any,p1:any,p2:any,p3:any,p4:any) {
    this.changed = false;
    this.context = new import0.AddexercisePage(p0,p1,p2,p3,p4);
  }
  detectChangesInternal(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this.changed;
    this.changed = false;
    return changed;
  }
}
var renderType_AddexercisePage_Host:import2.RenderComponentType = (null as any);
class _View_AddexercisePage_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _AddexercisePage_0_4:Wrapper_AddexercisePage;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_AddexercisePage_Host0,renderType_AddexercisePage_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.selectOrCreateHostElement('ng-component',rootSelector,(null as any));
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_AddexercisePage0(this.viewUtils,this.injector(0),this._appEl_0);
    this._AddexercisePage_0_4 = new Wrapper_AddexercisePage(this.parentInjector.get(import8.NavController),this.parentInjector.get(import9.FormBuilder),this.parentInjector.get(import10.LoadingController),this.parentInjector.get(import11.ExerciseData),this.parentInjector.get(import12.AlertController));
    this._appEl_0.initComponent(this._AddexercisePage_0_4.context,([] as any[]),compView_0);
    compView_0.create(this._AddexercisePage_0_4.context,this.projectableNodes,(null as any));
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.AddexercisePage) && (0 === requestNodeIndex))) { return this._AddexercisePage_0_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._AddexercisePage_0_4.detectChangesInternal(this,this._el_0,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_AddexercisePage_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  if ((renderType_AddexercisePage_Host === (null as any))) { (renderType_AddexercisePage_Host = viewUtils.createRenderComponentType('',0,import13.ViewEncapsulation.None,([] as any[]),{})); }
  return new _View_AddexercisePage_Host0(viewUtils,parentInjector,declarationEl);
}
export const AddexercisePageNgFactory:import14.ComponentFactory<import0.AddexercisePage> = new import14.ComponentFactory<import0.AddexercisePage>('ng-component',viewFactory_AddexercisePage_Host0,import0.AddexercisePage);
const styles_AddexercisePage:any[] = ([] as any[]);
var renderType_AddexercisePage:import2.RenderComponentType = (null as any);
class _View_AddexercisePage0 extends import1.AppView<import0.AddexercisePage> {
  _el_0:any;
  _Header_0_3:import15.Wrapper_Header;
  _text_1:any;
  _el_2:any;
  /*private*/ _appEl_2:import3.AppElement;
  _Navbar_2_4:import16.Wrapper_Navbar;
  _text_3:any;
  _el_4:any;
  /*private*/ _appEl_4:import3.AppElement;
  _ToolbarTitle_4_4:import17.Wrapper_ToolbarTitle;
  _text_5:any;
  _text_6:any;
  _text_7:any;
  _text_8:any;
  _el_9:any;
  /*private*/ _appEl_9:import3.AppElement;
  _Content_9_4:import18.Wrapper_Content;
  _text_10:any;
  _el_11:any;
  _FormGroupDirective_11_3:import19.Wrapper_FormGroupDirective;
  _ControlContainer_11_4:any;
  _NgControlStatusGroup_11_5:import20.Wrapper_NgControlStatusGroup;
  _text_12:any;
  _el_13:any;
  /*private*/ _appEl_13:import3.AppElement;
  _Item_13_4:import21.Wrapper_Item;
  _ItemContent_13_5:import21.Wrapper_ItemContent;
  _query_Label_13_0:import22.QueryList<any>;
  _query_Button_13_1:import22.QueryList<any>;
  _query_Icon_13_2:import22.QueryList<any>;
  _text_14:any;
  _el_15:any;
  _Label_15_3:import23.Wrapper_Label;
  _text_16:any;
  _text_17:any;
  _el_18:any;
  /*private*/ _appEl_18:import3.AppElement;
  _FormControlName_18_4:import24.Wrapper_FormControlName;
  _NgControl_18_5:any;
  _NgControlStatus_18_6:import20.Wrapper_NgControlStatus;
  _TextInput_18_7:import25.Wrapper_TextInput;
  _text_19:any;
  _text_20:any;
  _el_21:any;
  /*private*/ _appEl_21:import3.AppElement;
  _Item_21_4:import21.Wrapper_Item;
  _ItemContent_21_5:import21.Wrapper_ItemContent;
  _query_Label_21_0:import22.QueryList<any>;
  _query_Button_21_1:import22.QueryList<any>;
  _query_Icon_21_2:import22.QueryList<any>;
  _text_22:any;
  _el_23:any;
  _Label_23_3:import23.Wrapper_Label;
  _text_24:any;
  _text_25:any;
  _el_26:any;
  /*private*/ _appEl_26:import3.AppElement;
  _FormControlName_26_4:import24.Wrapper_FormControlName;
  _NgControl_26_5:any;
  _NgControlStatus_26_6:import20.Wrapper_NgControlStatus;
  _TextInput_26_7:import25.Wrapper_TextInput;
  _text_27:any;
  _text_28:any;
  _el_29:any;
  /*private*/ _appEl_29:import3.AppElement;
  _Item_29_4:import21.Wrapper_Item;
  _ItemContent_29_5:import21.Wrapper_ItemContent;
  _query_Label_29_0:import22.QueryList<any>;
  _query_Button_29_1:import22.QueryList<any>;
  _query_Icon_29_2:import22.QueryList<any>;
  _text_30:any;
  _el_31:any;
  _Label_31_3:import23.Wrapper_Label;
  _text_32:any;
  _text_33:any;
  _el_34:any;
  /*private*/ _appEl_34:import3.AppElement;
  _Select_34_4:import26.Wrapper_Select;
  _NG_VALUE_ACCESSOR_34_5:any[];
  _FormControlName_34_6:import24.Wrapper_FormControlName;
  _NgControl_34_7:any;
  _NgControlStatus_34_8:import20.Wrapper_NgControlStatus;
  _query_Option_34_0:import22.QueryList<any>;
  _text_35:any;
  _anchor_36:any;
  /*private*/ _appEl_36:import3.AppElement;
  _TemplateRef_36_5:any;
  _NgFor_36_6:import27.Wrapper_NgFor;
  _text_37:any;
  _text_38:any;
  _text_39:any;
  _el_40:any;
  /*private*/ _appEl_40:import3.AppElement;
  _Item_40_4:import21.Wrapper_Item;
  _ItemContent_40_5:import21.Wrapper_ItemContent;
  _query_Label_40_0:import22.QueryList<any>;
  _query_Button_40_1:import22.QueryList<any>;
  _query_Icon_40_2:import22.QueryList<any>;
  _text_41:any;
  _el_42:any;
  _Label_42_3:import23.Wrapper_Label;
  _text_43:any;
  _text_44:any;
  _el_45:any;
  /*private*/ _appEl_45:import3.AppElement;
  _Select_45_4:import26.Wrapper_Select;
  _NG_VALUE_ACCESSOR_45_5:any[];
  _FormControlName_45_6:import24.Wrapper_FormControlName;
  _NgControl_45_7:any;
  _NgControlStatus_45_8:import20.Wrapper_NgControlStatus;
  _query_Option_45_0:import22.QueryList<any>;
  _text_46:any;
  _anchor_47:any;
  /*private*/ _appEl_47:import3.AppElement;
  _TemplateRef_47_5:any;
  _NgFor_47_6:import27.Wrapper_NgFor;
  _text_48:any;
  _text_49:any;
  _text_50:any;
  _el_51:any;
  /*private*/ _appEl_51:import3.AppElement;
  _Button_51_4:import28.Wrapper_Button;
  _text_52:any;
  _text_53:any;
  _text_54:any;
  _text_55:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_7:any;
  /*private*/ _expr_8:any;
  /*private*/ _expr_9:any;
  /*private*/ _expr_10:any;
  /*private*/ _expr_11:any;
  /*private*/ _expr_12:any;
  /*private*/ _expr_14:any;
  /*private*/ _expr_15:any;
  /*private*/ _expr_16:any;
  /*private*/ _expr_17:any;
  /*private*/ _expr_18:any;
  /*private*/ _expr_19:any;
  /*private*/ _expr_23:any;
  /*private*/ _expr_24:any;
  /*private*/ _expr_25:any;
  /*private*/ _expr_26:any;
  /*private*/ _expr_27:any;
  /*private*/ _expr_28:any;
  /*private*/ _expr_34:any;
  /*private*/ _expr_36:any;
  /*private*/ _expr_37:any;
  /*private*/ _expr_38:any;
  /*private*/ _expr_39:any;
  /*private*/ _expr_40:any;
  /*private*/ _expr_41:any;
  /*private*/ _expr_46:any;
  /*private*/ _expr_48:any;
  /*private*/ _expr_49:any;
  /*private*/ _expr_50:any;
  /*private*/ _expr_51:any;
  /*private*/ _expr_52:any;
  /*private*/ _expr_53:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_AddexercisePage0,renderType_AddexercisePage,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'ion-header',(null as any));
    this._Header_0_3 = new import15.Wrapper_Header(this.parentInjector.get(import29.Config),new import30.ElementRef(this._el_0),this.renderer,this.parentInjector.get(import31.ViewController,(null as any)));
    this._text_1 = this.renderer.createText(this._el_0,'\n\n  ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'ion-navbar',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','toolbar');
    this._appEl_2 = new import3.AppElement(2,0,this,this._el_2);
    var compView_2:any = import16.viewFactory_Navbar0(this.viewUtils,this.injector(2),this._appEl_2);
    this._Navbar_2_4 = new import16.Wrapper_Navbar(this.parentInjector.get(import32.App),this.parentInjector.get(import31.ViewController,(null as any)),this.parentInjector.get(import8.NavController,(null as any)),this.parentInjector.get(import29.Config),new import30.ElementRef(this._el_2),this.renderer);
    this._appEl_2.initComponent(this._Navbar_2_4.context,([] as any[]),compView_2);
    this._text_3 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_4 = this.renderer.createElement((null as any),'ion-title',(null as any));
    this._appEl_4 = new import3.AppElement(4,2,this,this._el_4);
    var compView_4:any = import17.viewFactory_ToolbarTitle0(this.viewUtils,this.injector(4),this._appEl_4);
    this._ToolbarTitle_4_4 = new import17.Wrapper_ToolbarTitle(this.parentInjector.get(import29.Config),new import30.ElementRef(this._el_4),this.renderer,this.parentInjector.get(import33.Toolbar,(null as any)),this._Navbar_2_4.context);
    this._appEl_4.initComponent(this._ToolbarTitle_4_4.context,([] as any[]),compView_4);
    this._text_5 = this.renderer.createText((null as any),'Add new exercise',(null as any));
    compView_4.create(this._ToolbarTitle_4_4.context,[([] as any[]).concat([this._text_5])],(null as any));
    this._text_6 = this.renderer.createText((null as any),'\n  ',(null as any));
    compView_2.create(this._Navbar_2_4.context,[
      ([] as any[]),
      ([] as any[]),
      ([] as any[]),
      ([] as any[]).concat([
        this._text_3,
        this._el_4,
        this._text_6
      ]
      )
    ]
    ,(null as any));
    this._text_7 = this.renderer.createText(this._el_0,'\n\n',(null as any));
    this._text_8 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._el_9 = this.renderer.createElement(parentRenderNode,'ion-content',(null as any));
    this.renderer.setElementAttribute(this._el_9,'padding','');
    this._appEl_9 = new import3.AppElement(9,(null as any),this,this._el_9);
    var compView_9:any = import18.viewFactory_Content0(this.viewUtils,this.injector(9),this._appEl_9);
    this._Content_9_4 = new import18.Wrapper_Content(this.parentInjector.get(import29.Config),new import30.ElementRef(this._el_9),this.renderer,this.parentInjector.get(import32.App),this.parentInjector.get(import34.Keyboard),this.parentInjector.get(import35.NgZone),this.parentInjector.get(import31.ViewController,(null as any)),this.parentInjector.get(import36.Tabs,(null as any)));
    this._appEl_9.initComponent(this._Content_9_4.context,([] as any[]),compView_9);
    this._text_10 = this.renderer.createText((null as any),'\n\n  ',(null as any));
    this._el_11 = this.renderer.createElement((null as any),'form',(null as any));
    this.renderer.setElementAttribute(this._el_11,'novalidate','');
    this._FormGroupDirective_11_3 = new import19.Wrapper_FormGroupDirective((null as any),(null as any));
    this._ControlContainer_11_4 = this._FormGroupDirective_11_3.context;
    this._NgControlStatusGroup_11_5 = new import20.Wrapper_NgControlStatusGroup(this._ControlContainer_11_4);
    this._text_12 = this.renderer.createText(this._el_11,'\n\n    ',(null as any));
    this._el_13 = this.renderer.createElement(this._el_11,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_13,'class','item item-block');
    this._appEl_13 = new import3.AppElement(13,11,this,this._el_13);
    var compView_13:any = import21.viewFactory_Item0(this.viewUtils,this.injector(13),this._appEl_13);
    this._Item_13_4 = new import21.Wrapper_Item(this.parentInjector.get(import37.Form),this.parentInjector.get(import29.Config),new import30.ElementRef(this._el_13),this.renderer,this.parentInjector.get(import38.ItemReorder,(null as any)));
    this._ItemContent_13_5 = new import21.Wrapper_ItemContent();
    this._query_Label_13_0 = new import22.QueryList<any>();
    this._query_Button_13_1 = new import22.QueryList<any>();
    this._query_Icon_13_2 = new import22.QueryList<any>();
    this._appEl_13.initComponent(this._Item_13_4.context,([] as any[]),compView_13);
    this._text_14 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_15 = this.renderer.createElement((null as any),'ion-label',(null as any));
    this.renderer.setElementAttribute(this._el_15,'stacked','');
    this._Label_15_3 = new import23.Wrapper_Label(this.parentInjector.get(import29.Config),new import30.ElementRef(this._el_15),this.renderer,(null as any),'',(null as any),(null as any));
    this._text_16 = this.renderer.createText(this._el_15,'Exercise name',(null as any));
    this._text_17 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_18 = this.renderer.createElement((null as any),'ion-input',(null as any));
    this.renderer.setElementAttribute(this._el_18,'formControlName','name');
    this.renderer.setElementAttribute(this._el_18,'placeholder','Enter exercise name');
    this.renderer.setElementAttribute(this._el_18,'type','name');
    this._appEl_18 = new import3.AppElement(18,13,this,this._el_18);
    var compView_18:any = import25.viewFactory_TextInput0(this.viewUtils,this.injector(18),this._appEl_18);
    this._FormControlName_18_4 = new import24.Wrapper_FormControlName(this._ControlContainer_11_4,(null as any),(null as any),(null as any));
    this._NgControl_18_5 = this._FormControlName_18_4.context;
    this._NgControlStatus_18_6 = new import20.Wrapper_NgControlStatus(this._NgControl_18_5);
    this._TextInput_18_7 = new import25.Wrapper_TextInput(this.parentInjector.get(import29.Config),this.parentInjector.get(import37.Form),this._Item_13_4.context,this.parentInjector.get(import32.App),this.parentInjector.get(import39.Platform),new import30.ElementRef(this._el_18),this.renderer,this._Content_9_4.context,this.parentInjector.get(import8.NavController,(null as any)),this._NgControl_18_5);
    this._appEl_18.initComponent(this._TextInput_18_7.context,([] as any[]),compView_18);
    compView_18.create(this._TextInput_18_7.context,([] as any[]),(null as any));
    this._text_19 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._query_Label_13_0.reset([this._Label_15_3.context]);
    this._Item_13_4.context.contentLabel = this._query_Label_13_0.first;
    compView_13.create(this._Item_13_4.context,[
      ([] as any[]),
      ([] as any[]).concat([this._el_15]),
      ([] as any[]).concat([
        this._text_14,
        this._text_17,
        this._text_19
      ]
      ),
      ([] as any[]).concat([this._el_18]),
      ([] as any[])
    ]
    ,(null as any));
    this._text_20 = this.renderer.createText(this._el_11,'\n\n    ',(null as any));
    this._el_21 = this.renderer.createElement(this._el_11,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_21,'class','item item-block');
    this._appEl_21 = new import3.AppElement(21,11,this,this._el_21);
    var compView_21:any = import21.viewFactory_Item0(this.viewUtils,this.injector(21),this._appEl_21);
    this._Item_21_4 = new import21.Wrapper_Item(this.parentInjector.get(import37.Form),this.parentInjector.get(import29.Config),new import30.ElementRef(this._el_21),this.renderer,this.parentInjector.get(import38.ItemReorder,(null as any)));
    this._ItemContent_21_5 = new import21.Wrapper_ItemContent();
    this._query_Label_21_0 = new import22.QueryList<any>();
    this._query_Button_21_1 = new import22.QueryList<any>();
    this._query_Icon_21_2 = new import22.QueryList<any>();
    this._appEl_21.initComponent(this._Item_21_4.context,([] as any[]),compView_21);
    this._text_22 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_23 = this.renderer.createElement((null as any),'ion-label',(null as any));
    this.renderer.setElementAttribute(this._el_23,'stacked','');
    this._Label_23_3 = new import23.Wrapper_Label(this.parentInjector.get(import29.Config),new import30.ElementRef(this._el_23),this.renderer,(null as any),'',(null as any),(null as any));
    this._text_24 = this.renderer.createText(this._el_23,'Exercise Pr',(null as any));
    this._text_25 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_26 = this.renderer.createElement((null as any),'ion-input',(null as any));
    this.renderer.setElementAttribute(this._el_26,'formControlName','pr');
    this.renderer.setElementAttribute(this._el_26,'placeholder','Enter exercise pr');
    this.renderer.setElementAttribute(this._el_26,'type','pr');
    this._appEl_26 = new import3.AppElement(26,21,this,this._el_26);
    var compView_26:any = import25.viewFactory_TextInput0(this.viewUtils,this.injector(26),this._appEl_26);
    this._FormControlName_26_4 = new import24.Wrapper_FormControlName(this._ControlContainer_11_4,(null as any),(null as any),(null as any));
    this._NgControl_26_5 = this._FormControlName_26_4.context;
    this._NgControlStatus_26_6 = new import20.Wrapper_NgControlStatus(this._NgControl_26_5);
    this._TextInput_26_7 = new import25.Wrapper_TextInput(this.parentInjector.get(import29.Config),this.parentInjector.get(import37.Form),this._Item_21_4.context,this.parentInjector.get(import32.App),this.parentInjector.get(import39.Platform),new import30.ElementRef(this._el_26),this.renderer,this._Content_9_4.context,this.parentInjector.get(import8.NavController,(null as any)),this._NgControl_26_5);
    this._appEl_26.initComponent(this._TextInput_26_7.context,([] as any[]),compView_26);
    compView_26.create(this._TextInput_26_7.context,([] as any[]),(null as any));
    this._text_27 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._query_Label_21_0.reset([this._Label_23_3.context]);
    this._Item_21_4.context.contentLabel = this._query_Label_21_0.first;
    compView_21.create(this._Item_21_4.context,[
      ([] as any[]),
      ([] as any[]).concat([this._el_23]),
      ([] as any[]).concat([
        this._text_22,
        this._text_25,
        this._text_27
      ]
      ),
      ([] as any[]).concat([this._el_26]),
      ([] as any[])
    ]
    ,(null as any));
    this._text_28 = this.renderer.createText(this._el_11,'\n\n    ',(null as any));
    this._el_29 = this.renderer.createElement(this._el_11,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_29,'class','item item-block');
    this._appEl_29 = new import3.AppElement(29,11,this,this._el_29);
    var compView_29:any = import21.viewFactory_Item0(this.viewUtils,this.injector(29),this._appEl_29);
    this._Item_29_4 = new import21.Wrapper_Item(this.parentInjector.get(import37.Form),this.parentInjector.get(import29.Config),new import30.ElementRef(this._el_29),this.renderer,this.parentInjector.get(import38.ItemReorder,(null as any)));
    this._ItemContent_29_5 = new import21.Wrapper_ItemContent();
    this._query_Label_29_0 = new import22.QueryList<any>();
    this._query_Button_29_1 = new import22.QueryList<any>();
    this._query_Icon_29_2 = new import22.QueryList<any>();
    this._appEl_29.initComponent(this._Item_29_4.context,([] as any[]),compView_29);
    this._text_30 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_31 = this.renderer.createElement((null as any),'ion-label',(null as any));
    this.renderer.setElementAttribute(this._el_31,'stacked','');
    this._Label_31_3 = new import23.Wrapper_Label(this.parentInjector.get(import29.Config),new import30.ElementRef(this._el_31),this.renderer,(null as any),'',(null as any),(null as any));
    this._text_32 = this.renderer.createText(this._el_31,'Type of execerise',(null as any));
    this._text_33 = this.renderer.createText((null as any),'\n\n       ',(null as any));
    this._el_34 = this.renderer.createElement((null as any),'ion-select',(null as any));
    this.renderer.setElementAttribute(this._el_34,'formControlName','type');
    this.renderer.setElementAttribute(this._el_34,'placeholder','Select exercise type');
    this._appEl_34 = new import3.AppElement(34,29,this,this._el_34);
    var compView_34:any = import26.viewFactory_Select0(this.viewUtils,this.injector(34),this._appEl_34);
    this._Select_34_4 = new import26.Wrapper_Select(this.parentInjector.get(import32.App),this.parentInjector.get(import37.Form),this.parentInjector.get(import29.Config),new import30.ElementRef(this._el_34),this.renderer,this._Item_29_4.context,this.parentInjector.get(import8.NavController,(null as any)));
    this._NG_VALUE_ACCESSOR_34_5 = [this._Select_34_4.context];
    this._FormControlName_34_6 = new import24.Wrapper_FormControlName(this._ControlContainer_11_4,(null as any),(null as any),this._NG_VALUE_ACCESSOR_34_5);
    this._NgControl_34_7 = this._FormControlName_34_6.context;
    this._NgControlStatus_34_8 = new import20.Wrapper_NgControlStatus(this._NgControl_34_7);
    this._query_Option_34_0 = new import22.QueryList<any>();
    this._appEl_34.initComponent(this._Select_34_4.context,([] as any[]),compView_34);
    this._text_35 = this.renderer.createText((null as any),'\n         ',(null as any));
    this._anchor_36 = this.renderer.createTemplateAnchor((null as any),(null as any));
    this._appEl_36 = new import3.AppElement(36,34,this,this._anchor_36);
    this._TemplateRef_36_5 = new import40.TemplateRef_(this._appEl_36,viewFactory_AddexercisePage1);
    this._NgFor_36_6 = new import27.Wrapper_NgFor(this._appEl_36.vcRef,this._TemplateRef_36_5,this.parentInjector.get(import41.IterableDiffers),this.ref);
    this._text_37 = this.renderer.createText((null as any),'\n       ',(null as any));
    compView_34.create(this._Select_34_4.context,([] as any[]),(null as any));
    this._text_38 = this.renderer.createText((null as any),'\n\n    ',(null as any));
    this._query_Label_29_0.reset([this._Label_31_3.context]);
    this._Item_29_4.context.contentLabel = this._query_Label_29_0.first;
    compView_29.create(this._Item_29_4.context,[
      ([] as any[]),
      ([] as any[]).concat([this._el_31]),
      ([] as any[]).concat([
        this._text_30,
        this._text_33,
        this._text_38
      ]
      ),
      ([] as any[]).concat([this._el_34]),
      ([] as any[])
    ]
    ,(null as any));
    this._text_39 = this.renderer.createText(this._el_11,'\n\n    ',(null as any));
    this._el_40 = this.renderer.createElement(this._el_11,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_40,'class','item item-block');
    this._appEl_40 = new import3.AppElement(40,11,this,this._el_40);
    var compView_40:any = import21.viewFactory_Item0(this.viewUtils,this.injector(40),this._appEl_40);
    this._Item_40_4 = new import21.Wrapper_Item(this.parentInjector.get(import37.Form),this.parentInjector.get(import29.Config),new import30.ElementRef(this._el_40),this.renderer,this.parentInjector.get(import38.ItemReorder,(null as any)));
    this._ItemContent_40_5 = new import21.Wrapper_ItemContent();
    this._query_Label_40_0 = new import22.QueryList<any>();
    this._query_Button_40_1 = new import22.QueryList<any>();
    this._query_Icon_40_2 = new import22.QueryList<any>();
    this._appEl_40.initComponent(this._Item_40_4.context,([] as any[]),compView_40);
    this._text_41 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_42 = this.renderer.createElement((null as any),'ion-label',(null as any));
    this.renderer.setElementAttribute(this._el_42,'stacked','');
    this._Label_42_3 = new import23.Wrapper_Label(this.parentInjector.get(import29.Config),new import30.ElementRef(this._el_42),this.renderer,(null as any),'',(null as any),(null as any));
    this._text_43 = this.renderer.createText(this._el_42,'Unit',(null as any));
    this._text_44 = this.renderer.createText((null as any),'\n\n       ',(null as any));
    this._el_45 = this.renderer.createElement((null as any),'ion-select',(null as any));
    this.renderer.setElementAttribute(this._el_45,'formControlName','unit');
    this.renderer.setElementAttribute(this._el_45,'placeholder','Select unit for exercise');
    this._appEl_45 = new import3.AppElement(45,40,this,this._el_45);
    var compView_45:any = import26.viewFactory_Select0(this.viewUtils,this.injector(45),this._appEl_45);
    this._Select_45_4 = new import26.Wrapper_Select(this.parentInjector.get(import32.App),this.parentInjector.get(import37.Form),this.parentInjector.get(import29.Config),new import30.ElementRef(this._el_45),this.renderer,this._Item_40_4.context,this.parentInjector.get(import8.NavController,(null as any)));
    this._NG_VALUE_ACCESSOR_45_5 = [this._Select_45_4.context];
    this._FormControlName_45_6 = new import24.Wrapper_FormControlName(this._ControlContainer_11_4,(null as any),(null as any),this._NG_VALUE_ACCESSOR_45_5);
    this._NgControl_45_7 = this._FormControlName_45_6.context;
    this._NgControlStatus_45_8 = new import20.Wrapper_NgControlStatus(this._NgControl_45_7);
    this._query_Option_45_0 = new import22.QueryList<any>();
    this._appEl_45.initComponent(this._Select_45_4.context,([] as any[]),compView_45);
    this._text_46 = this.renderer.createText((null as any),'\n         ',(null as any));
    this._anchor_47 = this.renderer.createTemplateAnchor((null as any),(null as any));
    this._appEl_47 = new import3.AppElement(47,45,this,this._anchor_47);
    this._TemplateRef_47_5 = new import40.TemplateRef_(this._appEl_47,viewFactory_AddexercisePage2);
    this._NgFor_47_6 = new import27.Wrapper_NgFor(this._appEl_47.vcRef,this._TemplateRef_47_5,this.parentInjector.get(import41.IterableDiffers),this.ref);
    this._text_48 = this.renderer.createText((null as any),'\n       ',(null as any));
    compView_45.create(this._Select_45_4.context,([] as any[]),(null as any));
    this._text_49 = this.renderer.createText((null as any),'\n\n    ',(null as any));
    this._query_Label_40_0.reset([this._Label_42_3.context]);
    this._Item_40_4.context.contentLabel = this._query_Label_40_0.first;
    compView_40.create(this._Item_40_4.context,[
      ([] as any[]),
      ([] as any[]).concat([this._el_42]),
      ([] as any[]).concat([
        this._text_41,
        this._text_44,
        this._text_49
      ]
      ),
      ([] as any[]).concat([this._el_45]),
      ([] as any[])
    ]
    ,(null as any));
    this._text_50 = this.renderer.createText(this._el_11,'\n\n    ',(null as any));
    this._el_51 = this.renderer.createElement(this._el_11,'button',(null as any));
    this.renderer.setElementAttribute(this._el_51,'block','');
    this.renderer.setElementAttribute(this._el_51,'ion-button','');
    this.renderer.setElementAttribute(this._el_51,'type','submit');
    this._appEl_51 = new import3.AppElement(51,11,this,this._el_51);
    var compView_51:any = import28.viewFactory_Button0(this.viewUtils,this.injector(51),this._appEl_51);
    this._Button_51_4 = new import28.Wrapper_Button((null as any),'',this.parentInjector.get(import29.Config),new import30.ElementRef(this._el_51),this.renderer);
    this._appEl_51.initComponent(this._Button_51_4.context,([] as any[]),compView_51);
    this._text_52 = this.renderer.createText((null as any),'\n      Create exercise\n    ',(null as any));
    compView_51.create(this._Button_51_4.context,[([] as any[]).concat([this._text_52])],(null as any));
    this._text_53 = this.renderer.createText(this._el_11,'\n\n  ',(null as any));
    this._text_54 = this.renderer.createText((null as any),'\n\n',(null as any));
    compView_9.create(this._Content_9_4.context,[
      ([] as any[]),
      ([] as any[]).concat([
        this._text_10,
        this._el_11,
        this._text_54
      ]
      ),
      ([] as any[])
    ]
    ,(null as any));
    this._text_55 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this._expr_1 = import7.UNINITIALIZED;
    this._expr_2 = import7.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_11,'submit',this.eventHandler(this._handle_submit_11_0.bind(this)));
    var disposable_1:Function = this.renderer.listen(this._el_11,'reset',this.eventHandler(this._handle_reset_11_1.bind(this)));
    this._expr_7 = import7.UNINITIALIZED;
    this._expr_8 = import7.UNINITIALIZED;
    this._expr_9 = import7.UNINITIALIZED;
    this._expr_10 = import7.UNINITIALIZED;
    this._expr_11 = import7.UNINITIALIZED;
    this._expr_12 = import7.UNINITIALIZED;
    this._expr_14 = import7.UNINITIALIZED;
    this._expr_15 = import7.UNINITIALIZED;
    this._expr_16 = import7.UNINITIALIZED;
    this._expr_17 = import7.UNINITIALIZED;
    this._expr_18 = import7.UNINITIALIZED;
    this._expr_19 = import7.UNINITIALIZED;
    this._expr_23 = import7.UNINITIALIZED;
    this._expr_24 = import7.UNINITIALIZED;
    this._expr_25 = import7.UNINITIALIZED;
    this._expr_26 = import7.UNINITIALIZED;
    this._expr_27 = import7.UNINITIALIZED;
    this._expr_28 = import7.UNINITIALIZED;
    var disposable_2:Function = this.renderer.listen(this._el_34,'click',this.eventHandler(this._handle_click_34_0.bind(this)));
    var disposable_3:Function = this.renderer.listen(this._el_34,'keyup.space',this.eventHandler(this._handle_keyup_space_34_1.bind(this)));
    this._expr_34 = import7.UNINITIALIZED;
    this._expr_36 = import7.UNINITIALIZED;
    this._expr_37 = import7.UNINITIALIZED;
    this._expr_38 = import7.UNINITIALIZED;
    this._expr_39 = import7.UNINITIALIZED;
    this._expr_40 = import7.UNINITIALIZED;
    this._expr_41 = import7.UNINITIALIZED;
    var disposable_4:Function = this.renderer.listen(this._el_45,'click',this.eventHandler(this._handle_click_45_0.bind(this)));
    var disposable_5:Function = this.renderer.listen(this._el_45,'keyup.space',this.eventHandler(this._handle_keyup_space_45_1.bind(this)));
    this._expr_46 = import7.UNINITIALIZED;
    this._expr_48 = import7.UNINITIALIZED;
    this._expr_49 = import7.UNINITIALIZED;
    this._expr_50 = import7.UNINITIALIZED;
    this._expr_51 = import7.UNINITIALIZED;
    this._expr_52 = import7.UNINITIALIZED;
    this._expr_53 = import7.UNINITIALIZED;
    this.init(([] as any[]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._text_6,
      this._text_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._el_13,
      this._text_14,
      this._el_15,
      this._text_16,
      this._text_17,
      this._el_18,
      this._text_19,
      this._text_20,
      this._el_21,
      this._text_22,
      this._el_23,
      this._text_24,
      this._text_25,
      this._el_26,
      this._text_27,
      this._text_28,
      this._el_29,
      this._text_30,
      this._el_31,
      this._text_32,
      this._text_33,
      this._el_34,
      this._text_35,
      this._anchor_36,
      this._text_37,
      this._text_38,
      this._text_39,
      this._el_40,
      this._text_41,
      this._el_42,
      this._text_43,
      this._text_44,
      this._el_45,
      this._text_46,
      this._anchor_47,
      this._text_48,
      this._text_49,
      this._text_50,
      this._el_51,
      this._text_52,
      this._text_53,
      this._text_54,
      this._text_55
    ]
    ,[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3,
      disposable_4,
      disposable_5
    ]
    ,([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import42.ToolbarTitle) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 5)))) { return this._ToolbarTitle_4_4.context; }
    if (((token === import43.Navbar) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 6)))) { return this._Navbar_2_4.context; }
    if (((token === import33.Header) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._Header_0_3.context; }
    if (((token === import44.Label) && ((15 <= requestNodeIndex) && (requestNodeIndex <= 16)))) { return this._Label_15_3.context; }
    if (((token === import45.FormControlName) && (18 === requestNodeIndex))) { return this._FormControlName_18_4.context; }
    if (((token === import46.NgControl) && (18 === requestNodeIndex))) { return this._NgControl_18_5; }
    if (((token === import47.NgControlStatus) && (18 === requestNodeIndex))) { return this._NgControlStatus_18_6.context; }
    if (((token === import48.TextInput) && (18 === requestNodeIndex))) { return this._TextInput_18_7.context; }
    if (((token === import49.Item) && ((13 <= requestNodeIndex) && (requestNodeIndex <= 19)))) { return this._Item_13_4.context; }
    if (((token === import49.ItemContent) && ((13 <= requestNodeIndex) && (requestNodeIndex <= 19)))) { return this._ItemContent_13_5.context; }
    if (((token === import44.Label) && ((23 <= requestNodeIndex) && (requestNodeIndex <= 24)))) { return this._Label_23_3.context; }
    if (((token === import45.FormControlName) && (26 === requestNodeIndex))) { return this._FormControlName_26_4.context; }
    if (((token === import46.NgControl) && (26 === requestNodeIndex))) { return this._NgControl_26_5; }
    if (((token === import47.NgControlStatus) && (26 === requestNodeIndex))) { return this._NgControlStatus_26_6.context; }
    if (((token === import48.TextInput) && (26 === requestNodeIndex))) { return this._TextInput_26_7.context; }
    if (((token === import49.Item) && ((21 <= requestNodeIndex) && (requestNodeIndex <= 27)))) { return this._Item_21_4.context; }
    if (((token === import49.ItemContent) && ((21 <= requestNodeIndex) && (requestNodeIndex <= 27)))) { return this._ItemContent_21_5.context; }
    if (((token === import44.Label) && ((31 <= requestNodeIndex) && (requestNodeIndex <= 32)))) { return this._Label_31_3.context; }
    if (((token === import40.TemplateRef) && (36 === requestNodeIndex))) { return this._TemplateRef_36_5; }
    if (((token === import50.NgFor) && (36 === requestNodeIndex))) { return this._NgFor_36_6.context; }
    if (((token === import51.Select) && ((34 <= requestNodeIndex) && (requestNodeIndex <= 37)))) { return this._Select_34_4.context; }
    if (((token === import52.NG_VALUE_ACCESSOR) && ((34 <= requestNodeIndex) && (requestNodeIndex <= 37)))) { return this._NG_VALUE_ACCESSOR_34_5; }
    if (((token === import45.FormControlName) && ((34 <= requestNodeIndex) && (requestNodeIndex <= 37)))) { return this._FormControlName_34_6.context; }
    if (((token === import46.NgControl) && ((34 <= requestNodeIndex) && (requestNodeIndex <= 37)))) { return this._NgControl_34_7; }
    if (((token === import47.NgControlStatus) && ((34 <= requestNodeIndex) && (requestNodeIndex <= 37)))) { return this._NgControlStatus_34_8.context; }
    if (((token === import49.Item) && ((29 <= requestNodeIndex) && (requestNodeIndex <= 38)))) { return this._Item_29_4.context; }
    if (((token === import49.ItemContent) && ((29 <= requestNodeIndex) && (requestNodeIndex <= 38)))) { return this._ItemContent_29_5.context; }
    if (((token === import44.Label) && ((42 <= requestNodeIndex) && (requestNodeIndex <= 43)))) { return this._Label_42_3.context; }
    if (((token === import40.TemplateRef) && (47 === requestNodeIndex))) { return this._TemplateRef_47_5; }
    if (((token === import50.NgFor) && (47 === requestNodeIndex))) { return this._NgFor_47_6.context; }
    if (((token === import51.Select) && ((45 <= requestNodeIndex) && (requestNodeIndex <= 48)))) { return this._Select_45_4.context; }
    if (((token === import52.NG_VALUE_ACCESSOR) && ((45 <= requestNodeIndex) && (requestNodeIndex <= 48)))) { return this._NG_VALUE_ACCESSOR_45_5; }
    if (((token === import45.FormControlName) && ((45 <= requestNodeIndex) && (requestNodeIndex <= 48)))) { return this._FormControlName_45_6.context; }
    if (((token === import46.NgControl) && ((45 <= requestNodeIndex) && (requestNodeIndex <= 48)))) { return this._NgControl_45_7; }
    if (((token === import47.NgControlStatus) && ((45 <= requestNodeIndex) && (requestNodeIndex <= 48)))) { return this._NgControlStatus_45_8.context; }
    if (((token === import49.Item) && ((40 <= requestNodeIndex) && (requestNodeIndex <= 49)))) { return this._Item_40_4.context; }
    if (((token === import49.ItemContent) && ((40 <= requestNodeIndex) && (requestNodeIndex <= 49)))) { return this._ItemContent_40_5.context; }
    if (((token === import53.Button) && ((51 <= requestNodeIndex) && (requestNodeIndex <= 52)))) { return this._Button_51_4.context; }
    if (((token === import54.FormGroupDirective) && ((11 <= requestNodeIndex) && (requestNodeIndex <= 53)))) { return this._FormGroupDirective_11_3.context; }
    if (((token === import55.ControlContainer) && ((11 <= requestNodeIndex) && (requestNodeIndex <= 53)))) { return this._ControlContainer_11_4; }
    if (((token === import47.NgControlStatusGroup) && ((11 <= requestNodeIndex) && (requestNodeIndex <= 53)))) { return this._NgControlStatusGroup_11_5.context; }
    if (((token === import56.Content) && ((9 <= requestNodeIndex) && (requestNodeIndex <= 54)))) { return this._Content_9_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._Header_0_3.detectChangesInternal(this,this._el_0,throwOnChange);
    this._Navbar_2_4.detectChangesInternal(this,this._el_2,throwOnChange);
    if (this._ToolbarTitle_4_4.detectChangesInternal(this,this._el_4,throwOnChange)) { this._appEl_4.componentView.markAsCheckOnce(); }
    if (this._Content_9_4.detectChangesInternal(this,this._el_9,throwOnChange)) { this._appEl_9.componentView.markAsCheckOnce(); }
    const currVal_6:any = this.context.newExerciseForm;
    this._FormGroupDirective_11_3.check_form(currVal_6,throwOnChange,false);
    this._FormGroupDirective_11_3.detectChangesInternal(this,this._el_11,throwOnChange);
    this._NgControlStatusGroup_11_5.detectChangesInternal(this,this._el_11,throwOnChange);
    if (this._Item_13_4.detectChangesInternal(this,this._el_13,throwOnChange)) { this._appEl_13.componentView.markAsCheckOnce(); }
    this._ItemContent_13_5.detectChangesInternal(this,this._el_13,throwOnChange);
    this._Label_15_3.detectChangesInternal(this,this._el_15,throwOnChange);
    const currVal_13:any = 'name';
    this._FormControlName_18_4.check_name(currVal_13,throwOnChange,false);
    this._FormControlName_18_4.detectChangesInternal(this,this._el_18,throwOnChange);
    this._NgControlStatus_18_6.detectChangesInternal(this,this._el_18,throwOnChange);
    const currVal_20:any = 'Enter exercise name';
    this._TextInput_18_7.check_placeholder(currVal_20,throwOnChange,false);
    const currVal_21:any = 'name';
    this._TextInput_18_7.check_type(currVal_21,throwOnChange,false);
    this._TextInput_18_7.detectChangesInternal(this,this._el_18,throwOnChange);
    if (this._Item_21_4.detectChangesInternal(this,this._el_21,throwOnChange)) { this._appEl_21.componentView.markAsCheckOnce(); }
    this._ItemContent_21_5.detectChangesInternal(this,this._el_21,throwOnChange);
    this._Label_23_3.detectChangesInternal(this,this._el_23,throwOnChange);
    const currVal_22:any = 'pr';
    this._FormControlName_26_4.check_name(currVal_22,throwOnChange,false);
    this._FormControlName_26_4.detectChangesInternal(this,this._el_26,throwOnChange);
    this._NgControlStatus_26_6.detectChangesInternal(this,this._el_26,throwOnChange);
    const currVal_29:any = 'Enter exercise pr';
    this._TextInput_26_7.check_placeholder(currVal_29,throwOnChange,false);
    const currVal_30:any = 'pr';
    this._TextInput_26_7.check_type(currVal_30,throwOnChange,false);
    this._TextInput_26_7.detectChangesInternal(this,this._el_26,throwOnChange);
    if (this._Item_29_4.detectChangesInternal(this,this._el_29,throwOnChange)) { this._appEl_29.componentView.markAsCheckOnce(); }
    this._ItemContent_29_5.detectChangesInternal(this,this._el_29,throwOnChange);
    this._Label_31_3.detectChangesInternal(this,this._el_31,throwOnChange);
    const currVal_33:any = 'Select exercise type';
    this._Select_34_4.check_placeholder(currVal_33,throwOnChange,false);
    this._Select_34_4.detectChangesInternal(this,this._el_34,throwOnChange);
    const currVal_35:any = 'type';
    this._FormControlName_34_6.check_name(currVal_35,throwOnChange,false);
    this._FormControlName_34_6.detectChangesInternal(this,this._el_34,throwOnChange);
    this._NgControlStatus_34_8.detectChangesInternal(this,this._el_34,throwOnChange);
    const currVal_42:any = this.context.types;
    this._NgFor_36_6.check_ngForOf(currVal_42,throwOnChange,false);
    this._NgFor_36_6.detectChangesInternal(this,this._anchor_36,throwOnChange);
    if (this._Item_40_4.detectChangesInternal(this,this._el_40,throwOnChange)) { this._appEl_40.componentView.markAsCheckOnce(); }
    this._ItemContent_40_5.detectChangesInternal(this,this._el_40,throwOnChange);
    this._Label_42_3.detectChangesInternal(this,this._el_42,throwOnChange);
    const currVal_45:any = 'Select unit for exercise';
    this._Select_45_4.check_placeholder(currVal_45,throwOnChange,false);
    this._Select_45_4.detectChangesInternal(this,this._el_45,throwOnChange);
    const currVal_47:any = 'unit';
    this._FormControlName_45_6.check_name(currVal_47,throwOnChange,false);
    this._FormControlName_45_6.detectChangesInternal(this,this._el_45,throwOnChange);
    this._NgControlStatus_45_8.detectChangesInternal(this,this._el_45,throwOnChange);
    const currVal_54:any = this.context.units;
    this._NgFor_47_6.check_ngForOf(currVal_54,throwOnChange,false);
    this._NgFor_47_6.detectChangesInternal(this,this._anchor_47,throwOnChange);
    const currVal_55:any = '';
    this._Button_51_4.check_block(currVal_55,throwOnChange,false);
    if (this._Button_51_4.detectChangesInternal(this,this._el_51,throwOnChange)) { this._appEl_51.componentView.markAsCheckOnce(); }
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_13_1.dirty) {
        this._query_Button_13_1.reset(([] as any[]));
        this._Item_13_4.context._buttons = this._query_Button_13_1;
        this._query_Button_13_1.notifyOnChanges();
      }
      if (this._query_Icon_13_2.dirty) {
        this._query_Icon_13_2.reset(([] as any[]));
        this._Item_13_4.context._icons = this._query_Icon_13_2;
        this._query_Icon_13_2.notifyOnChanges();
      }
      if (this._query_Button_21_1.dirty) {
        this._query_Button_21_1.reset(([] as any[]));
        this._Item_21_4.context._buttons = this._query_Button_21_1;
        this._query_Button_21_1.notifyOnChanges();
      }
      if (this._query_Icon_21_2.dirty) {
        this._query_Icon_21_2.reset(([] as any[]));
        this._Item_21_4.context._icons = this._query_Icon_21_2;
        this._query_Icon_21_2.notifyOnChanges();
      }
      if (this._query_Option_34_0.dirty) {
          this._query_Option_34_0.reset([this._appEl_36.mapNestedViews(_View_AddexercisePage1,(nestedView:_View_AddexercisePage1):any => {
            return [nestedView._Option_0_3.context];
        })]);
        this._Select_34_4.context.options = this._query_Option_34_0;
        this._query_Option_34_0.notifyOnChanges();
      }
      if (this._query_Button_29_1.dirty) {
        this._query_Button_29_1.reset(([] as any[]));
        this._Item_29_4.context._buttons = this._query_Button_29_1;
        this._query_Button_29_1.notifyOnChanges();
      }
      if (this._query_Icon_29_2.dirty) {
        this._query_Icon_29_2.reset(([] as any[]));
        this._Item_29_4.context._icons = this._query_Icon_29_2;
        this._query_Icon_29_2.notifyOnChanges();
      }
      if (this._query_Option_45_0.dirty) {
          this._query_Option_45_0.reset([this._appEl_47.mapNestedViews(_View_AddexercisePage2,(nestedView:_View_AddexercisePage2):any => {
            return [nestedView._Option_0_3.context];
        })]);
        this._Select_45_4.context.options = this._query_Option_45_0;
        this._query_Option_45_0.notifyOnChanges();
      }
      if (this._query_Button_40_1.dirty) {
        this._query_Button_40_1.reset(([] as any[]));
        this._Item_40_4.context._buttons = this._query_Button_40_1;
        this._query_Button_40_1.notifyOnChanges();
      }
      if (this._query_Icon_40_2.dirty) {
        this._query_Icon_40_2.reset(([] as any[]));
        this._Item_40_4.context._icons = this._query_Icon_40_2;
        this._query_Icon_40_2.notifyOnChanges();
      }
      this._TextInput_18_7.context.ngAfterContentChecked();
      if ((this.numberOfChecks === 0)) { this._Item_13_4.context.ngAfterContentInit(); }
      this._TextInput_26_7.context.ngAfterContentChecked();
      if ((this.numberOfChecks === 0)) { this._Item_21_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Select_34_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_29_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Select_45_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_40_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Button_51_4.context.ngAfterContentInit(); }
    }
    const currVal_0:any = this._Navbar_2_4.context._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setElementProperty(this._el_2,'hidden',currVal_0);
      this._expr_0 = currVal_0;
    }
    const currVal_1:any = this._Navbar_2_4.context._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementClass(this._el_2,'statusbar-padding',currVal_1);
      this._expr_1 = currVal_1;
    }
    const currVal_2:any = this._Content_9_4.context._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setElementClass(this._el_9,'statusbar-padding',currVal_2);
      this._expr_2 = currVal_2;
    }
    const currVal_7:any = this._NgControlStatusGroup_11_5.context.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this.renderer.setElementClass(this._el_11,'ng-untouched',currVal_7);
      this._expr_7 = currVal_7;
    }
    const currVal_8:any = this._NgControlStatusGroup_11_5.context.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this.renderer.setElementClass(this._el_11,'ng-touched',currVal_8);
      this._expr_8 = currVal_8;
    }
    const currVal_9:any = this._NgControlStatusGroup_11_5.context.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_9,currVal_9)) {
      this.renderer.setElementClass(this._el_11,'ng-pristine',currVal_9);
      this._expr_9 = currVal_9;
    }
    const currVal_10:any = this._NgControlStatusGroup_11_5.context.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_10,currVal_10)) {
      this.renderer.setElementClass(this._el_11,'ng-dirty',currVal_10);
      this._expr_10 = currVal_10;
    }
    const currVal_11:any = this._NgControlStatusGroup_11_5.context.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_11,currVal_11)) {
      this.renderer.setElementClass(this._el_11,'ng-valid',currVal_11);
      this._expr_11 = currVal_11;
    }
    const currVal_12:any = this._NgControlStatusGroup_11_5.context.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_12,currVal_12)) {
      this.renderer.setElementClass(this._el_11,'ng-invalid',currVal_12);
      this._expr_12 = currVal_12;
    }
    const currVal_14:any = this._NgControlStatus_18_6.context.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_14,currVal_14)) {
      this.renderer.setElementClass(this._el_18,'ng-untouched',currVal_14);
      this._expr_14 = currVal_14;
    }
    const currVal_15:any = this._NgControlStatus_18_6.context.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_15,currVal_15)) {
      this.renderer.setElementClass(this._el_18,'ng-touched',currVal_15);
      this._expr_15 = currVal_15;
    }
    const currVal_16:any = this._NgControlStatus_18_6.context.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_16,currVal_16)) {
      this.renderer.setElementClass(this._el_18,'ng-pristine',currVal_16);
      this._expr_16 = currVal_16;
    }
    const currVal_17:any = this._NgControlStatus_18_6.context.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_17,currVal_17)) {
      this.renderer.setElementClass(this._el_18,'ng-dirty',currVal_17);
      this._expr_17 = currVal_17;
    }
    const currVal_18:any = this._NgControlStatus_18_6.context.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_18,currVal_18)) {
      this.renderer.setElementClass(this._el_18,'ng-valid',currVal_18);
      this._expr_18 = currVal_18;
    }
    const currVal_19:any = this._NgControlStatus_18_6.context.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_19,currVal_19)) {
      this.renderer.setElementClass(this._el_18,'ng-invalid',currVal_19);
      this._expr_19 = currVal_19;
    }
    const currVal_23:any = this._NgControlStatus_26_6.context.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_23,currVal_23)) {
      this.renderer.setElementClass(this._el_26,'ng-untouched',currVal_23);
      this._expr_23 = currVal_23;
    }
    const currVal_24:any = this._NgControlStatus_26_6.context.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_24,currVal_24)) {
      this.renderer.setElementClass(this._el_26,'ng-touched',currVal_24);
      this._expr_24 = currVal_24;
    }
    const currVal_25:any = this._NgControlStatus_26_6.context.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_25,currVal_25)) {
      this.renderer.setElementClass(this._el_26,'ng-pristine',currVal_25);
      this._expr_25 = currVal_25;
    }
    const currVal_26:any = this._NgControlStatus_26_6.context.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_26,currVal_26)) {
      this.renderer.setElementClass(this._el_26,'ng-dirty',currVal_26);
      this._expr_26 = currVal_26;
    }
    const currVal_27:any = this._NgControlStatus_26_6.context.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_27,currVal_27)) {
      this.renderer.setElementClass(this._el_26,'ng-valid',currVal_27);
      this._expr_27 = currVal_27;
    }
    const currVal_28:any = this._NgControlStatus_26_6.context.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_28,currVal_28)) {
      this.renderer.setElementClass(this._el_26,'ng-invalid',currVal_28);
      this._expr_28 = currVal_28;
    }
    const currVal_34:any = this._Select_34_4.context._disabled;
    if (import4.checkBinding(throwOnChange,this._expr_34,currVal_34)) {
      this.renderer.setElementClass(this._el_34,'select-disabled',currVal_34);
      this._expr_34 = currVal_34;
    }
    const currVal_36:any = this._NgControlStatus_34_8.context.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_36,currVal_36)) {
      this.renderer.setElementClass(this._el_34,'ng-untouched',currVal_36);
      this._expr_36 = currVal_36;
    }
    const currVal_37:any = this._NgControlStatus_34_8.context.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_37,currVal_37)) {
      this.renderer.setElementClass(this._el_34,'ng-touched',currVal_37);
      this._expr_37 = currVal_37;
    }
    const currVal_38:any = this._NgControlStatus_34_8.context.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_38,currVal_38)) {
      this.renderer.setElementClass(this._el_34,'ng-pristine',currVal_38);
      this._expr_38 = currVal_38;
    }
    const currVal_39:any = this._NgControlStatus_34_8.context.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_39,currVal_39)) {
      this.renderer.setElementClass(this._el_34,'ng-dirty',currVal_39);
      this._expr_39 = currVal_39;
    }
    const currVal_40:any = this._NgControlStatus_34_8.context.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_40,currVal_40)) {
      this.renderer.setElementClass(this._el_34,'ng-valid',currVal_40);
      this._expr_40 = currVal_40;
    }
    const currVal_41:any = this._NgControlStatus_34_8.context.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_41,currVal_41)) {
      this.renderer.setElementClass(this._el_34,'ng-invalid',currVal_41);
      this._expr_41 = currVal_41;
    }
    const currVal_46:any = this._Select_45_4.context._disabled;
    if (import4.checkBinding(throwOnChange,this._expr_46,currVal_46)) {
      this.renderer.setElementClass(this._el_45,'select-disabled',currVal_46);
      this._expr_46 = currVal_46;
    }
    const currVal_48:any = this._NgControlStatus_45_8.context.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_48,currVal_48)) {
      this.renderer.setElementClass(this._el_45,'ng-untouched',currVal_48);
      this._expr_48 = currVal_48;
    }
    const currVal_49:any = this._NgControlStatus_45_8.context.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_49,currVal_49)) {
      this.renderer.setElementClass(this._el_45,'ng-touched',currVal_49);
      this._expr_49 = currVal_49;
    }
    const currVal_50:any = this._NgControlStatus_45_8.context.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_50,currVal_50)) {
      this.renderer.setElementClass(this._el_45,'ng-pristine',currVal_50);
      this._expr_50 = currVal_50;
    }
    const currVal_51:any = this._NgControlStatus_45_8.context.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_51,currVal_51)) {
      this.renderer.setElementClass(this._el_45,'ng-dirty',currVal_51);
      this._expr_51 = currVal_51;
    }
    const currVal_52:any = this._NgControlStatus_45_8.context.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_52,currVal_52)) {
      this.renderer.setElementClass(this._el_45,'ng-valid',currVal_52);
      this._expr_52 = currVal_52;
    }
    const currVal_53:any = this._NgControlStatus_45_8.context.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_53,currVal_53)) {
      this.renderer.setElementClass(this._el_45,'ng-invalid',currVal_53);
      this._expr_53 = currVal_53;
    }
    this.detectViewChildrenChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._Navbar_2_4.context.ngAfterViewInit(); } }
  }
  destroyInternal():void {
    this._FormControlName_18_4.context.ngOnDestroy();
    this._TextInput_18_7.context.ngOnDestroy();
    this._FormControlName_26_4.context.ngOnDestroy();
    this._TextInput_26_7.context.ngOnDestroy();
    this._Select_34_4.context.ngOnDestroy();
    this._FormControlName_34_6.context.ngOnDestroy();
    this._Select_45_4.context.ngOnDestroy();
    this._FormControlName_45_6.context.ngOnDestroy();
    this._Content_9_4.context.ngOnDestroy();
  }
  private _handle_submit_11_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.addExercise()) !== false);
    const pd_1:any = ((<any>this._FormGroupDirective_11_3.context.onSubmit($event)) !== false);
    return ((true && pd_0) && pd_1);
  }
  private _handle_reset_11_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._FormGroupDirective_11_3.context.onReset()) !== false);
    return (true && pd_0);
  }
  private _handle_click_34_0($event:any):boolean {
    this._appEl_34.componentView.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._Select_34_4.context._click($event)) !== false);
    return (true && pd_0);
  }
  private _handle_keyup_space_34_1($event:any):boolean {
    this._appEl_34.componentView.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._Select_34_4.context._keyup()) !== false);
    return (true && pd_0);
  }
  private _handle_click_45_0($event:any):boolean {
    this._appEl_45.componentView.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._Select_45_4.context._click($event)) !== false);
    return (true && pd_0);
  }
  private _handle_keyup_space_45_1($event:any):boolean {
    this._appEl_45.componentView.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._Select_45_4.context._keyup()) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_AddexercisePage0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<import0.AddexercisePage> {
  if ((renderType_AddexercisePage === (null as any))) { (renderType_AddexercisePage = viewUtils.createRenderComponentType('',0,import13.ViewEncapsulation.None,styles_AddexercisePage,{})); }
  return new _View_AddexercisePage0(viewUtils,parentInjector,declarationEl);
}
class _View_AddexercisePage1 extends import1.AppView<any> {
  _el_0:any;
  _Option_0_3:import57.Wrapper_Option;
  _text_1:any;
  /*private*/ _expr_0:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_AddexercisePage1,renderType_AddexercisePage,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'ion-option',(null as any));
    this._Option_0_3 = new import57.Wrapper_Option(new import30.ElementRef(this._el_0));
    this._text_1 = this.renderer.createText(this._el_0,'',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this.init(([] as any[]).concat([this._el_0]),[
      this._el_0,
      this._text_1
    ]
    ,([] as any[]),([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import58.Option) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 1)))) { return this._Option_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._Option_0_3.detectChangesInternal(this,this._el_0,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_0:any = import4.interpolate(1,'',this.context.$implicit,'');
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setText(this._text_1,currVal_0);
      this._expr_0 = currVal_0;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  dirtyParentQueriesInternal():void {
    (<_View_AddexercisePage0>this.parent)._query_Option_34_0.setDirty();
  }
}
function viewFactory_AddexercisePage1(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  return new _View_AddexercisePage1(viewUtils,parentInjector,declarationEl);
}
class _View_AddexercisePage2 extends import1.AppView<any> {
  _el_0:any;
  _Option_0_3:import57.Wrapper_Option;
  _text_1:any;
  /*private*/ _expr_0:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_AddexercisePage2,renderType_AddexercisePage,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'ion-option',(null as any));
    this._Option_0_3 = new import57.Wrapper_Option(new import30.ElementRef(this._el_0));
    this._text_1 = this.renderer.createText(this._el_0,'',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this.init(([] as any[]).concat([this._el_0]),[
      this._el_0,
      this._text_1
    ]
    ,([] as any[]),([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import58.Option) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 1)))) { return this._Option_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._Option_0_3.detectChangesInternal(this,this._el_0,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_0:any = import4.interpolate(1,'',this.context.$implicit,'');
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setText(this._text_1,currVal_0);
      this._expr_0 = currVal_0;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  dirtyParentQueriesInternal():void {
    (<_View_AddexercisePage0>this.parent)._query_Option_45_0.setDirty();
  }
}
function viewFactory_AddexercisePage2(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  return new _View_AddexercisePage2(viewUtils,parentInjector,declarationEl);
}